---
title: "CV Average VS Aggregate"
author: "Qi Wang"
date: "2023/7/29"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
set.seed(1024)
# sample size
N = 30000
# X: continuous predictors
mu_X = c(0,0,0)
Sigma_X = matrix(c(1, 0.5, 0.1,
                   0.5, 1, 0.3,
                   0.1, 0.3, 1), nrow = 3, ncol = 3, byrow = TRUE)
coef_X = c(0.3, 0.5, 0.7)
# V: discrete predictors
p_V = c(0.7, 0.4)
coef_V = c(0.4, 0.6)

# W: racial and ethnic group
ps_W = c(0.5, 0.8) # proportion of white
coef_W = 0.8

# The probability of case
ps_case = c(0.2, 0.05)

paras = expand.grid(Proportion_White = ps_W, Prob_Case = ps_case)
NN = 1e5
candi_as = seq(-5, -1, 0.01)
as = NULL
for(i in 1:nrow(paras)){
  p_W = paras$Proportion_White[i]
  p_case = paras$Prob_Case[i]
  candi_prevals = NULL
  for(candi_a in candi_as){
    X = MASS::mvrnorm(n = NN, mu = mu_X, Sigma = Sigma_X)
    V = sapply(p_V, function(p){rbinom(n = NN, size = 1, prob = p)})
    W = rbinom(n = NN, size = 1, prob = p_W)
    pos_prob = exp(candi_a + X %*% coef_X + V %*% coef_V + W * coef_W) / (1 + exp(candi_a + X %*% coef_X + V %*% coef_V + W * coef_W))
    case = rbinom(NN, 1, pos_prob)
    candi_prevals = c(candi_prevals, mean(case))
  }
  cat(min(abs(candi_prevals - p_case)), "\n")
  as[i] = candi_as[which.min(abs(candi_prevals - p_case))]
  cat(as[i], "\n")
}
paras$alpha = as

for(i in 1:nrow(paras)){
  p_W = paras$Proportion_White[i]
  p_case = paras$Prob_Case[i]
  a = paras$alpha[i]
  X = MASS::mvrnorm(n = N, mu = mu_X, Sigma = Sigma_X)
  V = sapply(p_V, function(p){rbinom(n = N, size = 1, prob = p)})
  W = rbinom(n = N, size = 1, prob = p_W)
  pos_prob = exp(a + X %*% coef_X + V %*% coef_V + W * coef_W) / (1 + exp(a + X %*% coef_X + V %*% coef_V + W * coef_W))
  case = rbinom(N, 1, pos_prob)
  print(table(case, W))
}

# Number of iteration
n_iter = 1000
source("funcs_calibrationMetrics.R")
library(caret)
library(pROC)
library(tidyverse)
library(doParallel)
library(foreach)
library(parallel)
paras = merge(paras, data.frame(num_folds = c(5,10)))
```

# Full stratification
```{r}
out_AUC = paras

out_AUC[, c("W0_AUC_byAvg", "W1_AUC_byAvg", "W0_AUC_byAgt", "W1_AUC_byAgt", "W0_AUC_ext", "W1_AUC_ext", "W0_AUC_byAvg_estsd", "W1_AUC_byAvg_estsd", "W0_AUC_byAgt_estsd", "W1_AUC_byAgt_estsd", "W0_AUC_ext_estsd", "W1_AUC_ext_estsd", "W0_AUC_byAvg_sd", "W1_AUC_byAvg_sd", "W0_AUC_byAgt_sd", "W1_AUC_byAgt_sd", "W0_AUC_ext_sd", "W1_AUC_ext_sd")] = 0


out_EOR = paras
out_EOR[, c("W0_EOR_byAvg", "W1_EOR_byAvg", "W0_EOR_byAgt", "W1_EOR_byAgt", "W0_EOR_ext", "W1_EOR_ext", "W0_EOR_byAvg_estsd", "W1_EOR_byAvg_estsd", "W0_EOR_byAgt_estsd", "W1_EOR_byAgt_estsd", "W0_EOR_ext_estsd", "W1_EOR_ext_estsd", "W0_EOR_byAvg_rej_rate", "W1_EOR_byAvg_rej_rate", "W0_EOR_byAgt_rej_rate", "W1_EOR_byAgt_rej_rate", "W0_EOR_ext_rej_rate", "W1_EOR_ext_rej_rate", "W0_EOR_byAvg_sd", "W1_EOR_byAvg_sd", "W0_EOR_byAgt_sd", "W1_EOR_byAgt_sd", "W0_EOR_ext_sd", "W1_EOR_ext_sd")] = 0

out_cali_intc = paras
out_cali_intc[, c("W0_cali_intc_byAvg", "W1_cali_intc_byAvg", "W0_cali_intc_byAgt", "W1_cali_intc_byAgt", "W0_cali_intc_ext", "W1_cali_intc_ext", "W0_cali_intc_byAvg_estsd", "W1_cali_intc_byAvg_estsd", "W0_cali_intc_byAgt_estsd", "W1_cali_intc_byAgt_estsd", "W0_cali_intc_ext_estsd", "W1_cali_intc_ext_estsd", "W0_cali_intc_byAvg_rej_rate", "W1_cali_intc_byAvg_rej_rate", "W0_cali_intc_byAgt_rej_rate", "W1_cali_intc_byAgt_rej_rate", "W0_cali_intc_ext_rej_rate", "W1_cali_intc_ext_rej_rate", "W0_cali_intc_byAvg_sd", "W1_cali_intc_byAvg_sd", "W0_cali_intc_byAgt_sd", "W1_cali_intc_byAgt_sd", "W0_cali_intc_ext_sd", "W1_cali_intc_ext_sd")] = 0

out_cali_slp = paras
out_cali_slp[, c("W0_cali_slp_byAvg", "W1_cali_slp_byAvg", "W0_cali_slp_byAgt", "W1_cali_slp_byAgt", "W0_cali_slp_ext", "W1_cali_slp_ext", "W0_cali_slp_byAvg_estsd", "W1_cali_slp_byAvg_estsd", "W0_cali_slp_byAgt_estsd", "W1_cali_slp_byAgt_estsd", "W0_cali_slp_ext_estsd", "W1_cali_slp_ext_estsd", "W0_cali_slp_byAvg_rej_rate", "W1_cali_slp_byAvg_rej_rate", "W0_cali_slp_byAgt_rej_rate", "W1_cali_slp_byAgt_rej_rate", "W0_cali_slp_ext_rej_rate", "W1_cali_slp_ext_rej_rate", "W0_cali_slp_byAvg_sd", "W1_cali_slp_byAvg_sd", "W0_cali_slp_byAgt_sd", "W1_cali_slp_byAgt_sd", "W0_cali_slp_ext_sd", "W1_cali_slp_ext_sd")] = 0

myCluster <- makeCluster(detectCores()-1, type = "PSOCK")
registerDoParallel(myCluster)
start.t = Sys.time()
for(i in 1:nrow(paras)){
  cat("\n", i, "\n")
  p_W = paras$Proportion_White[i]
  p_case = paras$Prob_Case[i]
  a = paras$alpha[i]
  num_folds = paras$num_folds[i]
  res = foreach(iter=1:n_iter, .combine = 'rbind', .packages = c("caret", "pROC", "tidyverse")) %dopar%{
    X = MASS::mvrnorm(n = N, mu = mu_X, Sigma = Sigma_X)
    V = sapply(p_V, function(p){rbinom(n = N, size = 1, prob = p)})
    W = rbinom(n = N, size = 1, prob = p_W)
    pos_prob = exp(a + X %*% coef_X + V %*% coef_V + W * coef_W) / (1 + exp(a + X %*% coef_X + V %*% coef_V + W * coef_W))
    case = rbinom(N, 1, pos_prob)
    sim_data = data.frame(X=X, V=V, W=W, case=case)
    
    ext_X = MASS::mvrnorm(n = N, mu = mu_X, Sigma = Sigma_X)
    ext_V = sapply(p_V, function(p){rbinom(n = N, size = 1, prob = p)})
    ext_W = rbinom(n = N, size = 1, prob = p_W)
    ext_pos_prob = exp(a + ext_X %*% coef_X + ext_V %*% coef_V + ext_W * coef_W) / (1 + exp(a + ext_X %*% coef_X + ext_V %*% coef_V + ext_W * coef_W))
    ext_case = rbinom(N, 1, ext_pos_prob)
    ext_data = data.frame(X=ext_X, V=ext_V, W=ext_W, case=ext_case)
    
    full_data_model = glm(case ~ ., data = sim_data, family = binomial())
    ext_data$Y_pred = predict(full_data_model, ext_data, type = "response")
    
    suppressMessages(ext_auc_obj_W0 <- with(ext_data %>% filter(W==0), auc(case, Y_pred)))
    suppressMessages(ext_auc_obj_W1 <- with(ext_data %>% filter(W==1), auc(case, Y_pred)))
    AUC_ext_rep = c(ext_auc_obj_W0[1], ext_auc_obj_W1[1])
    AUC_estsd_ext_rep = c(sqrt(var(ext_auc_obj_W0)), sqrt(var(ext_auc_obj_W1)))
    
    ext_cali_res_W0 = ext_data %>% filter(W==0) %>% calibrationMetrics(risk_var = "Y_pred", weak_cali_ind = FALSE, correlated = FALSE)
    ext_cali_res_W1 = ext_data %>% filter(W==1) %>% calibrationMetrics(risk_var = "Y_pred", weak_cali_ind = FALSE, correlated = FALSE)
    
    group = apply(sim_data[,c("W", "case")], 1, function(x){
      if(x[1]==0 & x[2]==0){return(1)}
      else if(x[1]==0 & x[2]==1){return(2)}
      else if(x[1]==1 & x[2]==0){return(3)}
      else {return(4)}
    })
    CVTrainFolds = createFolds(as.factor(group), k = num_folds, list = TRUE, returnTrain = TRUE)
    
    test_Y_true = NULL
    test_Y_pred = NULL
    test_W = NULL
    AUC_byAvg_vec_folds = matrix(0, nrow = num_folds, ncol = length(p_W) + 1)
    EOR_byAvg_vec_folds = matrix(0, nrow = num_folds, ncol = length(p_W) + 1)
    cali_intc_byAvg_vec_folds = matrix(0, nrow = num_folds, ncol = length(p_W) + 1)
    cali_slp_byAvg_vec_folds = matrix(0, nrow = num_folds, ncol = length(p_W) + 1)
    AUC_estsd_byAvg_vec_folds = matrix(0, nrow = num_folds, ncol = length(p_W) + 1)
    EOR_estsd_byAvg_vec_folds = matrix(0, nrow = num_folds, ncol = length(p_W) + 1)
    cali_intc_estsd_byAvg_vec_folds = matrix(0, nrow = num_folds, ncol = length(p_W) + 1)
    cali_slp_estsd_byAvg_vec_folds = matrix(0, nrow = num_folds, ncol = length(p_W) + 1)
    for(cv_iter in 1:num_folds){
      train_id = CVTrainFolds[[cv_iter]]
      cv_train_data = sim_data[train_id, ]
      cv_test_data = sim_data[-train_id, ]
      test_Y_true = c(test_Y_true, cv_test_data$case)
      test_W = c(test_W, cv_test_data$W)
      cv_model = glm(case ~ ., data = cv_train_data, family = binomial())
      cv_Y_ped = predict(cv_model, cv_test_data, type = "response")
      test_Y_pred = c(test_Y_pred, cv_Y_ped)
      cv_test_data$Y_pred = cv_Y_ped
      suppressMessages(auc_byAvg_obj_W0 <- with(cv_test_data %>% filter(W==0), auc(case, Y_pred)))
      suppressMessages(auc_byAvg_obj_W1 <- with(cv_test_data %>% filter(W==1), auc(case, Y_pred)))
      
      AUC_byAvg_vec_folds[cv_iter, ] = c(auc_byAvg_obj_W0[1], auc_byAvg_obj_W1[1])
      AUC_estsd_byAvg_vec_folds[cv_iter, ] = c(sqrt(var(auc_byAvg_obj_W0)), sqrt(var(auc_byAvg_obj_W1)))
      
      cv_cali_res_W0 = cv_test_data %>% filter(W==0) %>% calibrationMetrics(risk_var = "Y_pred", weak_cali_ind = FALSE, correlated = FALSE)
      cv_cali_res_W1 = cv_test_data %>% filter(W==1) %>% calibrationMetrics(risk_var = "Y_pred", weak_cali_ind = FALSE, correlated = FALSE)
      
      EOR_byAvg_vec_folds[cv_iter, ] = c(cv_cali_res_W0$EORatio["EORatio"][[1]], cv_cali_res_W1$EORatio["EORatio"][[1]])
      cali_intc_byAvg_vec_folds[cv_iter, ] = c(cv_cali_res_W0$cox_intercept["cox_intercept"][[1]], cv_cali_res_W1$cox_intercept["cox_intercept"][[1]])
      cali_slp_byAvg_vec_folds[cv_iter, ] = c(cv_cali_res_W0$cox_slope["cox_slope"][[1]], cv_cali_res_W1$cox_slope["cox_slope"][[1]])
      
      EOR_estsd_byAvg_vec_folds[cv_iter, ] = c(cv_cali_res_W0$EORatio["se_EORatio"][[1]], cv_cali_res_W1$EORatio["se_EORatio"][[1]])
      cali_intc_estsd_byAvg_vec_folds[cv_iter, ] = c(cv_cali_res_W0$cox_intercept["cox_intercept_se"][[1]], cv_cali_res_W1$cox_intercept["cox_intercept_se"][[1]])
      cali_slp_estsd_byAvg_vec_folds[cv_iter, ] = c(cv_cali_res_W0$cox_slope["cox_slope_se"][[1]], cv_cali_res_W1$cox_slope["cox_slope_se"][[1]])
    }
    AUC_byAvg_rep = colMeans(AUC_byAvg_vec_folds)
    EOR_byAvg_rep = colMeans(EOR_byAvg_vec_folds)
    cali_intc_byAvg_rep = colMeans(cali_intc_byAvg_vec_folds)
    cali_slp_byAvg_rep = colMeans(cali_slp_byAvg_vec_folds)
    
    AUC_estsd_byAvg_rep = colMeans(AUC_estsd_byAvg_vec_folds)/sqrt(num_folds)
    EOR_estsd_byAvg_rep = colMeans(EOR_estsd_byAvg_vec_folds)/sqrt(num_folds)
    cali_intc_estsd_byAvg_rep = colMeans(cali_intc_estsd_byAvg_vec_folds)/sqrt(num_folds)
    cali_slp_estsd_byAvg_rep = colMeans(cali_slp_estsd_byAvg_vec_folds)/sqrt(num_folds)
    
    all_test_dt = data.frame(W=test_W, case=test_Y_true, Y_pred=test_Y_pred)
    suppressMessages(auc_byAgt_obj_W0 <- with(all_test_dt %>% filter(W==0), auc(case, Y_pred)))
    suppressMessages(auc_byAgt_obj_W1 <- with(all_test_dt %>% filter(W==1), auc(case, Y_pred)))
    
    AUC_byAgt_rep = c(auc_byAgt_obj_W0[1], auc_byAgt_obj_W1[1])
    AUC_estsd_byAgt_rep = c(sqrt(var(auc_byAgt_obj_W0)), sqrt(var(auc_byAgt_obj_W1)))
    
    cali_res_byAgt_W0 = all_test_dt %>% filter(W==0) %>% calibrationMetrics(risk_var = "Y_pred", weak_cali_ind = FALSE, correlated = FALSE)
    cali_res_byAgt_W1 = all_test_dt %>% filter(W==1) %>% calibrationMetrics(risk_var = "Y_pred", weak_cali_ind = FALSE, correlated = FALSE)
    
    c("AUC_ext_W0"=AUC_ext_rep[1], "AUC_ext_W1"=AUC_ext_rep[2],
      "AUC_estsd_ext_W0"=AUC_estsd_ext_rep[1], "AUC_estsd_ext_W1"=AUC_estsd_ext_rep[2],
      
      "EOR_ext_W0"=ext_cali_res_W0$EORatio["EORatio"][[1]], "EOR_ext_W1"=ext_cali_res_W1$EORatio["EORatio"][[1]],
      "EOR_estsd_ext_W0"=ext_cali_res_W0$EORatio["se_EORatio"][[1]], "EOR_estsd_ext_W1"=ext_cali_res_W1$EORatio["se_EORatio"][[1]],
      "EOR_rej_ext_W0"= 1 < ext_cali_res_W0$EORatio["EORatio_cilb"][[1]] | 1 > ext_cali_res_W0$EORatio["EORatio_ciub"][[1]],
      "EOR_rej_ext_W1"= 1 < ext_cali_res_W1$EORatio["EORatio_cilb"][[1]] | 1 > ext_cali_res_W1$EORatio["EORatio_ciub"][[1]],
      
      "cali_intc_ext_W0"=ext_cali_res_W0$cox_intercept["cox_intercept"][[1]], "cali_intc_ext_W1"=ext_cali_res_W1$cox_intercept["cox_intercept"][[1]],
      "cali_intc_estsd_ext_W0"=ext_cali_res_W0$cox_intercept["cox_intercept_se"][[1]], "cali_intc_estsd_ext_W1"=ext_cali_res_W1$cox_intercept["cox_intercept_se"][[1]],
      "cali_intc_rej_ext_W0" = 0 < ext_cali_res_W0$cox_intercept["cox_intercept_cilb"][[1]] | 0 > ext_cali_res_W0$cox_intercept["cox_intercept_ciub"][[1]],
      "cali_intc_rej_ext_W1" = 0 < ext_cali_res_W1$cox_intercept["cox_intercept_cilb"][[1]] | 0 > ext_cali_res_W1$cox_intercept["cox_intercept_ciub"][[1]],
      
      "cali_slp_ext_W0"=ext_cali_res_W0$cox_slope["cox_slope"][[1]], "cali_slp_ext_W1"=ext_cali_res_W1$cox_slope["cox_slope"][[1]],
      "cali_slp_estsd_ext_W0"=ext_cali_res_W0$cox_slope["cox_slope_se"][[1]], "cali_slp_estsd_ext_W1"=ext_cali_res_W1$cox_slope["cox_slope_se"][[1]],
      "cali_slp_rej_ext_W0" = 1 < ext_cali_res_W0$cox_slope["cox_slope_cilb"][[1]] | 1 > ext_cali_res_W0$cox_slope["cox_slope_ciub"][[1]],
      "cali_slp_rej_ext_W1" = 1 < ext_cali_res_W1$cox_slope["cox_slope_cilb"][[1]] | 1 > ext_cali_res_W1$cox_slope["cox_slope_ciub"][[1]],
      
      "AUC_byAvg_W0"=AUC_byAvg_rep[1], "AUC_byAvg_W1"=AUC_byAvg_rep[2],
      "AUC_estsd_byAvg_W0"=AUC_estsd_byAvg_rep[1], "AUC_estsd_byAvg_W1"=AUC_estsd_byAvg_rep[2],
      
      "EOR_byAvg_W0"=EOR_byAvg_rep[1], "EOR_byAvg_W1"=EOR_byAvg_rep[2],
      "EOR_estsd_byAvg_W0" = EOR_estsd_byAvg_rep[1], "EOR_estsd_byAvg_W1"=EOR_estsd_byAvg_rep[2],
      "EOR_rej_byAvg_W0" = 1 < EOR_byAvg_rep[1] - qnorm(0.975) * EOR_estsd_byAvg_rep[1] | 1 > EOR_byAvg_rep[1] + qnorm(0.975) * EOR_estsd_byAvg_rep[1],
      "EOR_rej_byAvg_W1" = 1 < EOR_byAvg_rep[2] - qnorm(0.975) * EOR_estsd_byAvg_rep[2] | 1 > EOR_byAvg_rep[2] + qnorm(0.975) * EOR_estsd_byAvg_rep[2],
      
      "cali_intc_byAvg_W0"=cali_intc_byAvg_rep[1], "cali_intc_byAvg_W1"=cali_intc_byAvg_rep[2],
      "cali_intc_estsd_byAvg_W0" = cali_intc_estsd_byAvg_rep[1], "cali_intc_estsd_byAvg_W1"=cali_intc_estsd_byAvg_rep[2],
      "cali_intc_rej_byAvg_W0" = 0 < cali_intc_byAvg_rep[1] - qnorm(0.975) * cali_intc_estsd_byAvg_rep[1] | 0 > cali_intc_byAvg_rep[1] + qnorm(0.975) * cali_intc_estsd_byAvg_rep[1],
      "cali_intc_rej_byAvg_W1" = 0 < cali_intc_byAvg_rep[2] - qnorm(0.975) * cali_intc_estsd_byAvg_rep[2] | 0 > cali_intc_byAvg_rep[2] + qnorm(0.975) * cali_intc_estsd_byAvg_rep[2],
      
      "cali_slp_byAvg_W0"=cali_slp_byAvg_rep[1], "cali_slp_byAvg_W1"=cali_slp_byAvg_rep[2],
      "cali_slp_estsd_byAvg_W0" = cali_slp_estsd_byAvg_rep[1], "cali_slp_estsd_byAvg_W1"=cali_slp_estsd_byAvg_rep[2],
      "cali_slp_rej_byAvg_W0" = 1 < cali_slp_byAvg_rep[1] - qnorm(0.975) * cali_slp_estsd_byAvg_rep[1] | 1 > cali_slp_byAvg_rep[1] + qnorm(0.975) * cali_slp_estsd_byAvg_rep[1],
      "cali_slp_rej_byAvg_W1" = 1 < cali_slp_byAvg_rep[2] - qnorm(0.975) * cali_slp_estsd_byAvg_rep[2] | 1 > cali_slp_byAvg_rep[2] + qnorm(0.975) * cali_slp_estsd_byAvg_rep[2],
      
      "AUC_byAgt_W0"=AUC_byAgt_rep[1], "AUC_byAgt_W1"=AUC_byAgt_rep[2],
      "AUC_estsd_byAgt_W0"=AUC_estsd_byAgt_rep[1], "AUC_estsd_byAgt_W1"=AUC_estsd_byAgt_rep[2],
      
      "EOR_byAgt_W0"=cali_res_byAgt_W0$EORatio["EORatio"][[1]], "EOR_byAgt_W1"=cali_res_byAgt_W1$EORatio["EORatio"][[1]],
      "EOR_estsd_byAgt_W0"=cali_res_byAgt_W0$EORatio["se_EORatio"][[1]], "EOR_estsd_byAgt_W1"=cali_res_byAgt_W1$EORatio["se_EORatio"][[1]],
      "EOR_rej_byAgt_W0"= 1 < cali_res_byAgt_W0$EORatio["EORatio_cilb"][[1]] | 1 > cali_res_byAgt_W0$EORatio["EORatio_ciub"][[1]],
      "EOR_rej_byAgt_W1"= 1 < cali_res_byAgt_W1$EORatio["EORatio_cilb"][[1]] | 1 > cali_res_byAgt_W1$EORatio["EORatio_ciub"][[1]],
      
      "cali_intc_byAgt_W0"=cali_res_byAgt_W0$cox_intercept["cox_intercept"][[1]], "cali_intc_byAgt_W1"=cali_res_byAgt_W1$cox_intercept["cox_intercept"][[1]],
      "cali_intc_estsd_byAgt_W0"=cali_res_byAgt_W0$cox_intercept["cox_intercept_se"][[1]], "cali_intc_estsd_byAgt_W1"=cali_res_byAgt_W1$cox_intercept["cox_intercept_se"][[1]],
      "cali_intc_rej_byAgt_W0" = 0 < cali_res_byAgt_W0$cox_intercept["cox_intercept_cilb"][[1]] | 0 > cali_res_byAgt_W0$cox_intercept["cox_intercept_ciub"][[1]],
      "cali_intc_rej_byAgt_W1" = 0 < cali_res_byAgt_W1$cox_intercept["cox_intercept_cilb"][[1]] | 0 > cali_res_byAgt_W1$cox_intercept["cox_intercept_ciub"][[1]],
      
      "cali_slp_byAgt_W0"=cali_res_byAgt_W0$cox_slope["cox_slope"][[1]], "cali_slp_byAgt_W1"=cali_res_byAgt_W1$cox_slope["cox_slope"][[1]],
      "cali_slp_estsd_byAgt_W0"=cali_res_byAgt_W0$cox_slope["cox_slope_se"][[1]], "cali_slp_estsd_byAgt_W1"=cali_res_byAgt_W1$cox_slope["cox_slope_se"][[1]],
      "cali_slp_rej_byAgt_W0" = 1 < cali_res_byAgt_W0$cox_slope["cox_slope_cilb"][[1]] | 1 > cali_res_byAgt_W0$cox_slope["cox_slope_ciub"][[1]],
      "cali_slp_rej_byAgt_W1" = 1 < cali_res_byAgt_W1$cox_slope["cox_slope_cilb"][[1]] | 1 > cali_res_byAgt_W1$cox_slope["cox_slope_ciub"][[1]])
  }
  
  
  out_AUC[i, c("W0_AUC_byAvg", "W1_AUC_byAvg", "W0_AUC_byAgt", "W1_AUC_byAgt", "W0_AUC_ext", "W1_AUC_ext", "W0_AUC_byAvg_estsd", "W1_AUC_byAvg_estsd", "W0_AUC_byAgt_estsd", "W1_AUC_byAgt_estsd", "W0_AUC_ext_estsd", "W1_AUC_ext_estsd")] = colMeans(res[, c("AUC_byAvg_W0", "AUC_byAvg_W1", "AUC_byAgt_W0", "AUC_byAgt_W1", "AUC_ext_W0", "AUC_ext_W1", "AUC_estsd_byAvg_W0", "AUC_estsd_byAvg_W1", "AUC_estsd_byAgt_W0", "AUC_estsd_byAgt_W1", "AUC_estsd_ext_W0", "AUC_estsd_ext_W1")])
  
  out_AUC[i, c("W0_AUC_byAvg_sd", "W1_AUC_byAvg_sd", "W0_AUC_byAgt_sd", "W1_AUC_byAgt_sd", "W0_AUC_ext_sd", "W1_AUC_ext_sd")] = apply(res[, c("AUC_byAvg_W0", "AUC_byAvg_W1", "AUC_byAgt_W0", "AUC_byAgt_W1", "AUC_ext_W0", "AUC_ext_W1")], MARGIN = 2, sd)
  
  out_EOR[i, c("W0_EOR_byAvg", "W1_EOR_byAvg", "W0_EOR_byAgt", "W1_EOR_byAgt", "W0_EOR_ext", "W1_EOR_ext", "W0_EOR_byAvg_estsd", "W1_EOR_byAvg_estsd", "W0_EOR_byAgt_estsd", "W1_EOR_byAgt_estsd", "W0_EOR_ext_estsd", "W1_EOR_ext_estsd", "W0_EOR_byAvg_rej_rate", "W1_EOR_byAvg_rej_rate", "W0_EOR_byAgt_rej_rate", "W1_EOR_byAgt_rej_rate", "W0_EOR_ext_rej_rate", "W1_EOR_ext_rej_rate")] = colMeans(res[, c("EOR_byAvg_W0", "EOR_byAvg_W1", "EOR_byAgt_W0", "EOR_byAgt_W1", "EOR_ext_W0", "EOR_ext_W1", "EOR_estsd_byAvg_W0", "EOR_estsd_byAvg_W1", "EOR_estsd_byAgt_W0", "EOR_estsd_byAgt_W1", "EOR_estsd_ext_W0", "EOR_estsd_ext_W1", "EOR_rej_byAvg_W0", "EOR_rej_byAvg_W1", "EOR_rej_byAgt_W0", "EOR_rej_byAgt_W1", "EOR_rej_ext_W0", "EOR_rej_ext_W1")])
  
  out_EOR[i, c("W0_EOR_byAvg_sd", "W1_EOR_byAvg_sd", "W0_EOR_byAgt_sd", "W1_EOR_byAgt_sd", "W0_EOR_ext_sd", "W1_EOR_ext_sd")] = apply(res[, c("EOR_byAvg_W0", "EOR_byAvg_W1", "EOR_byAgt_W0", "EOR_byAgt_W1", "EOR_ext_W0", "EOR_ext_W1")], MARGIN = 2, sd)
  
  out_cali_intc[i, c("W0_cali_intc_byAvg", "W1_cali_intc_byAvg", "W0_cali_intc_byAgt", "W1_cali_intc_byAgt", "W0_cali_intc_ext", "W1_cali_intc_ext", "W0_cali_intc_byAvg_estsd", "W1_cali_intc_byAvg_estsd", "W0_cali_intc_byAgt_estsd", "W1_cali_intc_byAgt_estsd", "W0_cali_intc_ext_estsd", "W1_cali_intc_ext_estsd", "W0_cali_intc_byAvg_rej_rate", "W1_cali_intc_byAvg_rej_rate", "W0_cali_intc_byAgt_rej_rate", "W1_cali_intc_byAgt_rej_rate", "W0_cali_intc_ext_rej_rate", "W1_cali_intc_ext_rej_rate")] = colMeans(res[, c("cali_intc_byAvg_W0", "cali_intc_byAvg_W1", "cali_intc_byAgt_W0", "cali_intc_byAgt_W1", "cali_intc_ext_W0", "cali_intc_ext_W1", "cali_intc_estsd_byAvg_W0", "cali_intc_estsd_byAvg_W1", "cali_intc_estsd_byAgt_W0", "cali_intc_estsd_byAgt_W1", "cali_intc_estsd_ext_W0", "cali_intc_estsd_ext_W1", "cali_intc_rej_byAvg_W0", "cali_intc_rej_byAvg_W1", "cali_intc_rej_byAgt_W0", "cali_intc_rej_byAgt_W1", "cali_intc_rej_ext_W0", "cali_intc_rej_ext_W1")])
  
  out_cali_intc[i, c("W0_cali_intc_byAvg_sd", "W1_cali_intc_byAvg_sd", "W0_cali_intc_byAgt_sd", "W1_cali_intc_byAgt_sd", "W0_cali_intc_ext_sd", "W1_cali_intc_ext_sd")] = apply(res[, c("cali_intc_byAvg_W0", "cali_intc_byAvg_W1", "cali_intc_byAgt_W0", "cali_intc_byAgt_W1", "cali_intc_ext_W0", "cali_intc_ext_W1")], MARGIN = 2, sd)
  
  out_cali_slp[i, c("W0_cali_slp_byAvg", "W1_cali_slp_byAvg", "W0_cali_slp_byAgt", "W1_cali_slp_byAgt", "W0_cali_slp_ext", "W1_cali_slp_ext", "W0_cali_slp_byAvg_estsd", "W1_cali_slp_byAvg_estsd", "W0_cali_slp_byAgt_estsd", "W1_cali_slp_byAgt_estsd", "W0_cali_slp_ext_estsd", "W1_cali_slp_ext_estsd", "W0_cali_slp_byAvg_rej_rate", "W1_cali_slp_byAvg_rej_rate", "W0_cali_slp_byAgt_rej_rate", "W1_cali_slp_byAgt_rej_rate", "W0_cali_slp_ext_rej_rate", "W1_cali_slp_ext_rej_rate")] = colMeans(res[, c("cali_slp_byAvg_W0", "cali_slp_byAvg_W1", "cali_slp_byAgt_W0", "cali_slp_byAgt_W1", "cali_slp_ext_W0", "cali_slp_ext_W1", "cali_slp_estsd_byAvg_W0", "cali_slp_estsd_byAvg_W1", "cali_slp_estsd_byAgt_W0", "cali_slp_estsd_byAgt_W1", "cali_slp_estsd_ext_W0", "cali_slp_estsd_ext_W1", "cali_slp_rej_byAvg_W0", "cali_slp_rej_byAvg_W1", "cali_slp_rej_byAgt_W0", "cali_slp_rej_byAgt_W1", "cali_slp_rej_ext_W0", "cali_slp_rej_ext_W1")])
  
  out_cali_slp[i, c("W0_cali_slp_byAvg_sd", "W1_cali_slp_byAvg_sd", "W0_cali_slp_byAgt_sd", "W1_cali_slp_byAgt_sd", "W0_cali_slp_ext_sd", "W1_cali_slp_ext_sd")] = apply(res[, c("cali_slp_byAvg_W0", "cali_slp_byAvg_W1", "cali_slp_byAgt_W0", "cali_slp_byAgt_W1", "cali_slp_ext_W0", "cali_slp_ext_W1")], MARGIN = 2, sd)
}
end.t = Sys.time()
cat(end.t - start.t)
stopCluster(myCluster)
out_AUC %>% write.csv("./Full stratification/AUC.csv", row.names = FALSE)
out_EOR %>% write.csv("./Full stratification/EOR.csv", row.names = FALSE)
out_cali_intc %>% write.csv("./Full stratification/Cali_intercept.csv", row.names = FALSE)
out_cali_slp %>% write.csv("./Full stratification/Cali_slope.csv", row.names = FALSE)
```


# Stratified by race
```{r}
out_AUC = paras

out_AUC[, c("W0_AUC_byAvg", "W1_AUC_byAvg", "W0_AUC_byAgt", "W1_AUC_byAgt", "W0_AUC_ext", "W1_AUC_ext", "W0_AUC_byAvg_estsd", "W1_AUC_byAvg_estsd", "W0_AUC_byAgt_estsd", "W1_AUC_byAgt_estsd", "W0_AUC_ext_estsd", "W1_AUC_ext_estsd", "W0_AUC_byAvg_sd", "W1_AUC_byAvg_sd", "W0_AUC_byAgt_sd", "W1_AUC_byAgt_sd", "W0_AUC_ext_sd", "W1_AUC_ext_sd")] = 0


out_EOR = paras
out_EOR[, c("W0_EOR_byAvg", "W1_EOR_byAvg", "W0_EOR_byAgt", "W1_EOR_byAgt", "W0_EOR_ext", "W1_EOR_ext", "W0_EOR_byAvg_estsd", "W1_EOR_byAvg_estsd", "W0_EOR_byAgt_estsd", "W1_EOR_byAgt_estsd", "W0_EOR_ext_estsd", "W1_EOR_ext_estsd", "W0_EOR_byAvg_rej_rate", "W1_EOR_byAvg_rej_rate", "W0_EOR_byAgt_rej_rate", "W1_EOR_byAgt_rej_rate", "W0_EOR_ext_rej_rate", "W1_EOR_ext_rej_rate", "W0_EOR_byAvg_sd", "W1_EOR_byAvg_sd", "W0_EOR_byAgt_sd", "W1_EOR_byAgt_sd", "W0_EOR_ext_sd", "W1_EOR_ext_sd")] = 0

out_cali_intc = paras
out_cali_intc[, c("W0_cali_intc_byAvg", "W1_cali_intc_byAvg", "W0_cali_intc_byAgt", "W1_cali_intc_byAgt", "W0_cali_intc_ext", "W1_cali_intc_ext", "W0_cali_intc_byAvg_estsd", "W1_cali_intc_byAvg_estsd", "W0_cali_intc_byAgt_estsd", "W1_cali_intc_byAgt_estsd", "W0_cali_intc_ext_estsd", "W1_cali_intc_ext_estsd", "W0_cali_intc_byAvg_rej_rate", "W1_cali_intc_byAvg_rej_rate", "W0_cali_intc_byAgt_rej_rate", "W1_cali_intc_byAgt_rej_rate", "W0_cali_intc_ext_rej_rate", "W1_cali_intc_ext_rej_rate", "W0_cali_intc_byAvg_sd", "W1_cali_intc_byAvg_sd", "W0_cali_intc_byAgt_sd", "W1_cali_intc_byAgt_sd", "W0_cali_intc_ext_sd", "W1_cali_intc_ext_sd")] = 0

out_cali_slp = paras
out_cali_slp[, c("W0_cali_slp_byAvg", "W1_cali_slp_byAvg", "W0_cali_slp_byAgt", "W1_cali_slp_byAgt", "W0_cali_slp_ext", "W1_cali_slp_ext", "W0_cali_slp_byAvg_estsd", "W1_cali_slp_byAvg_estsd", "W0_cali_slp_byAgt_estsd", "W1_cali_slp_byAgt_estsd", "W0_cali_slp_ext_estsd", "W1_cali_slp_ext_estsd", "W0_cali_slp_byAvg_rej_rate", "W1_cali_slp_byAvg_rej_rate", "W0_cali_slp_byAgt_rej_rate", "W1_cali_slp_byAgt_rej_rate", "W0_cali_slp_ext_rej_rate", "W1_cali_slp_ext_rej_rate", "W0_cali_slp_byAvg_sd", "W1_cali_slp_byAvg_sd", "W0_cali_slp_byAgt_sd", "W1_cali_slp_byAgt_sd", "W0_cali_slp_ext_sd", "W1_cali_slp_ext_sd")] = 0

myCluster <- makeCluster(detectCores()-1, type = "PSOCK")
registerDoParallel(myCluster)
start.t = Sys.time()
for(i in 1:nrow(paras)){
  cat("\n", i, "\n")
  p_W = paras$Proportion_White[i]
  p_case = paras$Prob_Case[i]
  a = paras$alpha[i]
  num_folds = paras$num_folds[i]
  res = foreach(iter=1:n_iter, .combine = 'rbind', .packages = c("caret", "pROC", "tidyverse")) %dopar%{
    X = MASS::mvrnorm(n = N, mu = mu_X, Sigma = Sigma_X)
    V = sapply(p_V, function(p){rbinom(n = N, size = 1, prob = p)})
    W = rbinom(n = N, size = 1, prob = p_W)
    pos_prob = exp(a + X %*% coef_X + V %*% coef_V + W * coef_W) / (1 + exp(a + X %*% coef_X + V %*% coef_V + W * coef_W))
    case = rbinom(N, 1, pos_prob)
    sim_data = data.frame(X=X, V=V, W=W, case=case)
    
    ext_X = MASS::mvrnorm(n = N, mu = mu_X, Sigma = Sigma_X)
    ext_V = sapply(p_V, function(p){rbinom(n = N, size = 1, prob = p)})
    ext_W = rbinom(n = N, size = 1, prob = p_W)
    ext_pos_prob = exp(a + ext_X %*% coef_X + ext_V %*% coef_V + ext_W * coef_W) / (1 + exp(a + ext_X %*% coef_X + ext_V %*% coef_V + ext_W * coef_W))
    ext_case = rbinom(N, 1, ext_pos_prob)
    ext_data = data.frame(X=ext_X, V=ext_V, W=ext_W, case=ext_case)
    
    full_data_model = glm(case ~ ., data = sim_data, family = binomial())
    ext_data$Y_pred = predict(full_data_model, ext_data, type = "response")
    
    suppressMessages(ext_auc_obj_W0 <- with(ext_data %>% filter(W==0), auc(case, Y_pred)))
    suppressMessages(ext_auc_obj_W1 <- with(ext_data %>% filter(W==1), auc(case, Y_pred)))
    AUC_ext_rep = c(ext_auc_obj_W0[1], ext_auc_obj_W1[1])
    AUC_estsd_ext_rep = c(sqrt(var(ext_auc_obj_W0)), sqrt(var(ext_auc_obj_W1)))
    
    ext_cali_res_W0 = ext_data %>% filter(W==0) %>% calibrationMetrics(risk_var = "Y_pred", weak_cali_ind = FALSE, correlated = FALSE)
    ext_cali_res_W1 = ext_data %>% filter(W==1) %>% calibrationMetrics(risk_var = "Y_pred", weak_cali_ind = FALSE, correlated = FALSE)
    
    CVTrainFolds = createFolds(as.factor(sim_data$W), k = num_folds, list = TRUE, returnTrain = TRUE)
    
    test_Y_true = NULL
    test_Y_pred = NULL
    test_W = NULL
    AUC_byAvg_vec_folds = matrix(0, nrow = num_folds, ncol = length(p_W) + 1)
    EOR_byAvg_vec_folds = matrix(0, nrow = num_folds, ncol = length(p_W) + 1)
    cali_intc_byAvg_vec_folds = matrix(0, nrow = num_folds, ncol = length(p_W) + 1)
    cali_slp_byAvg_vec_folds = matrix(0, nrow = num_folds, ncol = length(p_W) + 1)
    AUC_estsd_byAvg_vec_folds = matrix(0, nrow = num_folds, ncol = length(p_W) + 1)
    EOR_estsd_byAvg_vec_folds = matrix(0, nrow = num_folds, ncol = length(p_W) + 1)
    cali_intc_estsd_byAvg_vec_folds = matrix(0, nrow = num_folds, ncol = length(p_W) + 1)
    cali_slp_estsd_byAvg_vec_folds = matrix(0, nrow = num_folds, ncol = length(p_W) + 1)
    for(cv_iter in 1:num_folds){
      train_id = CVTrainFolds[[cv_iter]]
      cv_train_data = sim_data[train_id, ]
      cv_test_data = sim_data[-train_id, ]
      test_Y_true = c(test_Y_true, cv_test_data$case)
      test_W = c(test_W, cv_test_data$W)
      cv_model = glm(case ~ ., data = cv_train_data, family = binomial())
      cv_Y_ped = predict(cv_model, cv_test_data, type = "response")
      test_Y_pred = c(test_Y_pred, cv_Y_ped)
      cv_test_data$Y_pred = cv_Y_ped
      suppressMessages(auc_byAvg_obj_W0 <- with(cv_test_data %>% filter(W==0), auc(case, Y_pred)))
      suppressMessages(auc_byAvg_obj_W1 <- with(cv_test_data %>% filter(W==1), auc(case, Y_pred)))
      
      AUC_byAvg_vec_folds[cv_iter, ] = c(auc_byAvg_obj_W0[1], auc_byAvg_obj_W1[1])
      AUC_estsd_byAvg_vec_folds[cv_iter, ] = c(sqrt(var(auc_byAvg_obj_W0)), sqrt(var(auc_byAvg_obj_W1)))
      
      cv_cali_res_W0 = cv_test_data %>% filter(W==0) %>% calibrationMetrics(risk_var = "Y_pred", weak_cali_ind = FALSE, correlated = FALSE)
      cv_cali_res_W1 = cv_test_data %>% filter(W==1) %>% calibrationMetrics(risk_var = "Y_pred", weak_cali_ind = FALSE, correlated = FALSE)
      
      EOR_byAvg_vec_folds[cv_iter, ] = c(cv_cali_res_W0$EORatio["EORatio"][[1]], cv_cali_res_W1$EORatio["EORatio"][[1]])
      cali_intc_byAvg_vec_folds[cv_iter, ] = c(cv_cali_res_W0$cox_intercept["cox_intercept"][[1]], cv_cali_res_W1$cox_intercept["cox_intercept"][[1]])
      cali_slp_byAvg_vec_folds[cv_iter, ] = c(cv_cali_res_W0$cox_slope["cox_slope"][[1]], cv_cali_res_W1$cox_slope["cox_slope"][[1]])
      
      EOR_estsd_byAvg_vec_folds[cv_iter, ] = c(cv_cali_res_W0$EORatio["se_EORatio"][[1]], cv_cali_res_W1$EORatio["se_EORatio"][[1]])
      cali_intc_estsd_byAvg_vec_folds[cv_iter, ] = c(cv_cali_res_W0$cox_intercept["cox_intercept_se"][[1]], cv_cali_res_W1$cox_intercept["cox_intercept_se"][[1]])
      cali_slp_estsd_byAvg_vec_folds[cv_iter, ] = c(cv_cali_res_W0$cox_slope["cox_slope_se"][[1]], cv_cali_res_W1$cox_slope["cox_slope_se"][[1]])
    }
    AUC_byAvg_rep = colMeans(AUC_byAvg_vec_folds)
    EOR_byAvg_rep = colMeans(EOR_byAvg_vec_folds)
    cali_intc_byAvg_rep = colMeans(cali_intc_byAvg_vec_folds)
    cali_slp_byAvg_rep = colMeans(cali_slp_byAvg_vec_folds)
    
    AUC_estsd_byAvg_rep = colMeans(AUC_estsd_byAvg_vec_folds)/sqrt(num_folds)
    EOR_estsd_byAvg_rep = colMeans(EOR_estsd_byAvg_vec_folds)/sqrt(num_folds)
    cali_intc_estsd_byAvg_rep = colMeans(cali_intc_estsd_byAvg_vec_folds)/sqrt(num_folds)
    cali_slp_estsd_byAvg_rep = colMeans(cali_slp_estsd_byAvg_vec_folds)/sqrt(num_folds)
    
    all_test_dt = data.frame(W=test_W, case=test_Y_true, Y_pred=test_Y_pred)
    suppressMessages(auc_byAgt_obj_W0 <- with(all_test_dt %>% filter(W==0), auc(case, Y_pred)))
    suppressMessages(auc_byAgt_obj_W1 <- with(all_test_dt %>% filter(W==1), auc(case, Y_pred)))
    
    AUC_byAgt_rep = c(auc_byAgt_obj_W0[1], auc_byAgt_obj_W1[1])
    AUC_estsd_byAgt_rep = c(sqrt(var(auc_byAgt_obj_W0)), sqrt(var(auc_byAgt_obj_W1)))
    
    cali_res_byAgt_W0 = all_test_dt %>% filter(W==0) %>% calibrationMetrics(risk_var = "Y_pred", weak_cali_ind = FALSE, correlated = FALSE)
    cali_res_byAgt_W1 = all_test_dt %>% filter(W==1) %>% calibrationMetrics(risk_var = "Y_pred", weak_cali_ind = FALSE, correlated = FALSE)
    
    c("AUC_ext_W0"=AUC_ext_rep[1], "AUC_ext_W1"=AUC_ext_rep[2],
      "AUC_estsd_ext_W0"=AUC_estsd_ext_rep[1], "AUC_estsd_ext_W1"=AUC_estsd_ext_rep[2],
      
      "EOR_ext_W0"=ext_cali_res_W0$EORatio["EORatio"][[1]], "EOR_ext_W1"=ext_cali_res_W1$EORatio["EORatio"][[1]],
      "EOR_estsd_ext_W0"=ext_cali_res_W0$EORatio["se_EORatio"][[1]], "EOR_estsd_ext_W1"=ext_cali_res_W1$EORatio["se_EORatio"][[1]],
      "EOR_rej_ext_W0"= 1 < ext_cali_res_W0$EORatio["EORatio_cilb"][[1]] | 1 > ext_cali_res_W0$EORatio["EORatio_ciub"][[1]],
      "EOR_rej_ext_W1"= 1 < ext_cali_res_W1$EORatio["EORatio_cilb"][[1]] | 1 > ext_cali_res_W1$EORatio["EORatio_ciub"][[1]],
      
      "cali_intc_ext_W0"=ext_cali_res_W0$cox_intercept["cox_intercept"][[1]], "cali_intc_ext_W1"=ext_cali_res_W1$cox_intercept["cox_intercept"][[1]],
      "cali_intc_estsd_ext_W0"=ext_cali_res_W0$cox_intercept["cox_intercept_se"][[1]], "cali_intc_estsd_ext_W1"=ext_cali_res_W1$cox_intercept["cox_intercept_se"][[1]],
      "cali_intc_rej_ext_W0" = 0 < ext_cali_res_W0$cox_intercept["cox_intercept_cilb"][[1]] | 0 > ext_cali_res_W0$cox_intercept["cox_intercept_ciub"][[1]],
      "cali_intc_rej_ext_W1" = 0 < ext_cali_res_W1$cox_intercept["cox_intercept_cilb"][[1]] | 0 > ext_cali_res_W1$cox_intercept["cox_intercept_ciub"][[1]],
      
      "cali_slp_ext_W0"=ext_cali_res_W0$cox_slope["cox_slope"][[1]], "cali_slp_ext_W1"=ext_cali_res_W1$cox_slope["cox_slope"][[1]],
      "cali_slp_estsd_ext_W0"=ext_cali_res_W0$cox_slope["cox_slope_se"][[1]], "cali_slp_estsd_ext_W1"=ext_cali_res_W1$cox_slope["cox_slope_se"][[1]],
      "cali_slp_rej_ext_W0" = 1 < ext_cali_res_W0$cox_slope["cox_slope_cilb"][[1]] | 1 > ext_cali_res_W0$cox_slope["cox_slope_ciub"][[1]],
      "cali_slp_rej_ext_W1" = 1 < ext_cali_res_W1$cox_slope["cox_slope_cilb"][[1]] | 1 > ext_cali_res_W1$cox_slope["cox_slope_ciub"][[1]],
      
      "AUC_byAvg_W0"=AUC_byAvg_rep[1], "AUC_byAvg_W1"=AUC_byAvg_rep[2],
      "AUC_estsd_byAvg_W0"=AUC_estsd_byAvg_rep[1], "AUC_estsd_byAvg_W1"=AUC_estsd_byAvg_rep[2],
      
      "EOR_byAvg_W0"=EOR_byAvg_rep[1], "EOR_byAvg_W1"=EOR_byAvg_rep[2],
      "EOR_estsd_byAvg_W0" = EOR_estsd_byAvg_rep[1], "EOR_estsd_byAvg_W1"=EOR_estsd_byAvg_rep[2],
      "EOR_rej_byAvg_W0" = 1 < EOR_byAvg_rep[1] - qnorm(0.975) * EOR_estsd_byAvg_rep[1] | 1 > EOR_byAvg_rep[1] + qnorm(0.975) * EOR_estsd_byAvg_rep[1],
      "EOR_rej_byAvg_W1" = 1 < EOR_byAvg_rep[2] - qnorm(0.975) * EOR_estsd_byAvg_rep[2] | 1 > EOR_byAvg_rep[2] + qnorm(0.975) * EOR_estsd_byAvg_rep[2],
      
      "cali_intc_byAvg_W0"=cali_intc_byAvg_rep[1], "cali_intc_byAvg_W1"=cali_intc_byAvg_rep[2],
      "cali_intc_estsd_byAvg_W0" = cali_intc_estsd_byAvg_rep[1], "cali_intc_estsd_byAvg_W1"=cali_intc_estsd_byAvg_rep[2],
      "cali_intc_rej_byAvg_W0" = 0 < cali_intc_byAvg_rep[1] - qnorm(0.975) * cali_intc_estsd_byAvg_rep[1] | 0 > cali_intc_byAvg_rep[1] + qnorm(0.975) * cali_intc_estsd_byAvg_rep[1],
      "cali_intc_rej_byAvg_W1" = 0 < cali_intc_byAvg_rep[2] - qnorm(0.975) * cali_intc_estsd_byAvg_rep[2] | 0 > cali_intc_byAvg_rep[2] + qnorm(0.975) * cali_intc_estsd_byAvg_rep[2],
      
      "cali_slp_byAvg_W0"=cali_slp_byAvg_rep[1], "cali_slp_byAvg_W1"=cali_slp_byAvg_rep[2],
      "cali_slp_estsd_byAvg_W0" = cali_slp_estsd_byAvg_rep[1], "cali_slp_estsd_byAvg_W1"=cali_slp_estsd_byAvg_rep[2],
      "cali_slp_rej_byAvg_W0" = 1 < cali_slp_byAvg_rep[1] - qnorm(0.975) * cali_slp_estsd_byAvg_rep[1] | 1 > cali_slp_byAvg_rep[1] + qnorm(0.975) * cali_slp_estsd_byAvg_rep[1],
      "cali_slp_rej_byAvg_W1" = 1 < cali_slp_byAvg_rep[2] - qnorm(0.975) * cali_slp_estsd_byAvg_rep[2] | 1 > cali_slp_byAvg_rep[2] + qnorm(0.975) * cali_slp_estsd_byAvg_rep[2],
      
      "AUC_byAgt_W0"=AUC_byAgt_rep[1], "AUC_byAgt_W1"=AUC_byAgt_rep[2],
      "AUC_estsd_byAgt_W0"=AUC_estsd_byAgt_rep[1], "AUC_estsd_byAgt_W1"=AUC_estsd_byAgt_rep[2],
      
      "EOR_byAgt_W0"=cali_res_byAgt_W0$EORatio["EORatio"][[1]], "EOR_byAgt_W1"=cali_res_byAgt_W1$EORatio["EORatio"][[1]],
      "EOR_estsd_byAgt_W0"=cali_res_byAgt_W0$EORatio["se_EORatio"][[1]], "EOR_estsd_byAgt_W1"=cali_res_byAgt_W1$EORatio["se_EORatio"][[1]],
      "EOR_rej_byAgt_W0"= 1 < cali_res_byAgt_W0$EORatio["EORatio_cilb"][[1]] | 1 > cali_res_byAgt_W0$EORatio["EORatio_ciub"][[1]],
      "EOR_rej_byAgt_W1"= 1 < cali_res_byAgt_W1$EORatio["EORatio_cilb"][[1]] | 1 > cali_res_byAgt_W1$EORatio["EORatio_ciub"][[1]],
      
      "cali_intc_byAgt_W0"=cali_res_byAgt_W0$cox_intercept["cox_intercept"][[1]], "cali_intc_byAgt_W1"=cali_res_byAgt_W1$cox_intercept["cox_intercept"][[1]],
      "cali_intc_estsd_byAgt_W0"=cali_res_byAgt_W0$cox_intercept["cox_intercept_se"][[1]], "cali_intc_estsd_byAgt_W1"=cali_res_byAgt_W1$cox_intercept["cox_intercept_se"][[1]],
      "cali_intc_rej_byAgt_W0" = 0 < cali_res_byAgt_W0$cox_intercept["cox_intercept_cilb"][[1]] | 0 > cali_res_byAgt_W0$cox_intercept["cox_intercept_ciub"][[1]],
      "cali_intc_rej_byAgt_W1" = 0 < cali_res_byAgt_W1$cox_intercept["cox_intercept_cilb"][[1]] | 0 > cali_res_byAgt_W1$cox_intercept["cox_intercept_ciub"][[1]],
      
      "cali_slp_byAgt_W0"=cali_res_byAgt_W0$cox_slope["cox_slope"][[1]], "cali_slp_byAgt_W1"=cali_res_byAgt_W1$cox_slope["cox_slope"][[1]],
      "cali_slp_estsd_byAgt_W0"=cali_res_byAgt_W0$cox_slope["cox_slope_se"][[1]], "cali_slp_estsd_byAgt_W1"=cali_res_byAgt_W1$cox_slope["cox_slope_se"][[1]],
      "cali_slp_rej_byAgt_W0" = 1 < cali_res_byAgt_W0$cox_slope["cox_slope_cilb"][[1]] | 1 > cali_res_byAgt_W0$cox_slope["cox_slope_ciub"][[1]],
      "cali_slp_rej_byAgt_W1" = 1 < cali_res_byAgt_W1$cox_slope["cox_slope_cilb"][[1]] | 1 > cali_res_byAgt_W1$cox_slope["cox_slope_ciub"][[1]])
  }
  
  
  out_AUC[i, c("W0_AUC_byAvg", "W1_AUC_byAvg", "W0_AUC_byAgt", "W1_AUC_byAgt", "W0_AUC_ext", "W1_AUC_ext", "W0_AUC_byAvg_estsd", "W1_AUC_byAvg_estsd", "W0_AUC_byAgt_estsd", "W1_AUC_byAgt_estsd", "W0_AUC_ext_estsd", "W1_AUC_ext_estsd")] = colMeans(res[, c("AUC_byAvg_W0", "AUC_byAvg_W1", "AUC_byAgt_W0", "AUC_byAgt_W1", "AUC_ext_W0", "AUC_ext_W1", "AUC_estsd_byAvg_W0", "AUC_estsd_byAvg_W1", "AUC_estsd_byAgt_W0", "AUC_estsd_byAgt_W1", "AUC_estsd_ext_W0", "AUC_estsd_ext_W1")])
  
  out_AUC[i, c("W0_AUC_byAvg_sd", "W1_AUC_byAvg_sd", "W0_AUC_byAgt_sd", "W1_AUC_byAgt_sd", "W0_AUC_ext_sd", "W1_AUC_ext_sd")] = apply(res[, c("AUC_byAvg_W0", "AUC_byAvg_W1", "AUC_byAgt_W0", "AUC_byAgt_W1", "AUC_ext_W0", "AUC_ext_W1")], MARGIN = 2, sd)
  
  out_EOR[i, c("W0_EOR_byAvg", "W1_EOR_byAvg", "W0_EOR_byAgt", "W1_EOR_byAgt", "W0_EOR_ext", "W1_EOR_ext", "W0_EOR_byAvg_estsd", "W1_EOR_byAvg_estsd", "W0_EOR_byAgt_estsd", "W1_EOR_byAgt_estsd", "W0_EOR_ext_estsd", "W1_EOR_ext_estsd", "W0_EOR_byAvg_rej_rate", "W1_EOR_byAvg_rej_rate", "W0_EOR_byAgt_rej_rate", "W1_EOR_byAgt_rej_rate", "W0_EOR_ext_rej_rate", "W1_EOR_ext_rej_rate")] = colMeans(res[, c("EOR_byAvg_W0", "EOR_byAvg_W1", "EOR_byAgt_W0", "EOR_byAgt_W1", "EOR_ext_W0", "EOR_ext_W1", "EOR_estsd_byAvg_W0", "EOR_estsd_byAvg_W1", "EOR_estsd_byAgt_W0", "EOR_estsd_byAgt_W1", "EOR_estsd_ext_W0", "EOR_estsd_ext_W1", "EOR_rej_byAvg_W0", "EOR_rej_byAvg_W1", "EOR_rej_byAgt_W0", "EOR_rej_byAgt_W1", "EOR_rej_ext_W0", "EOR_rej_ext_W1")])
  
  out_EOR[i, c("W0_EOR_byAvg_sd", "W1_EOR_byAvg_sd", "W0_EOR_byAgt_sd", "W1_EOR_byAgt_sd", "W0_EOR_ext_sd", "W1_EOR_ext_sd")] = apply(res[, c("EOR_byAvg_W0", "EOR_byAvg_W1", "EOR_byAgt_W0", "EOR_byAgt_W1", "EOR_ext_W0", "EOR_ext_W1")], MARGIN = 2, sd)
  
  out_cali_intc[i, c("W0_cali_intc_byAvg", "W1_cali_intc_byAvg", "W0_cali_intc_byAgt", "W1_cali_intc_byAgt", "W0_cali_intc_ext", "W1_cali_intc_ext", "W0_cali_intc_byAvg_estsd", "W1_cali_intc_byAvg_estsd", "W0_cali_intc_byAgt_estsd", "W1_cali_intc_byAgt_estsd", "W0_cali_intc_ext_estsd", "W1_cali_intc_ext_estsd", "W0_cali_intc_byAvg_rej_rate", "W1_cali_intc_byAvg_rej_rate", "W0_cali_intc_byAgt_rej_rate", "W1_cali_intc_byAgt_rej_rate", "W0_cali_intc_ext_rej_rate", "W1_cali_intc_ext_rej_rate")] = colMeans(res[, c("cali_intc_byAvg_W0", "cali_intc_byAvg_W1", "cali_intc_byAgt_W0", "cali_intc_byAgt_W1", "cali_intc_ext_W0", "cali_intc_ext_W1", "cali_intc_estsd_byAvg_W0", "cali_intc_estsd_byAvg_W1", "cali_intc_estsd_byAgt_W0", "cali_intc_estsd_byAgt_W1", "cali_intc_estsd_ext_W0", "cali_intc_estsd_ext_W1", "cali_intc_rej_byAvg_W0", "cali_intc_rej_byAvg_W1", "cali_intc_rej_byAgt_W0", "cali_intc_rej_byAgt_W1", "cali_intc_rej_ext_W0", "cali_intc_rej_ext_W1")])
  
  out_cali_intc[i, c("W0_cali_intc_byAvg_sd", "W1_cali_intc_byAvg_sd", "W0_cali_intc_byAgt_sd", "W1_cali_intc_byAgt_sd", "W0_cali_intc_ext_sd", "W1_cali_intc_ext_sd")] = apply(res[, c("cali_intc_byAvg_W0", "cali_intc_byAvg_W1", "cali_intc_byAgt_W0", "cali_intc_byAgt_W1", "cali_intc_ext_W0", "cali_intc_ext_W1")], MARGIN = 2, sd)
  
  out_cali_slp[i, c("W0_cali_slp_byAvg", "W1_cali_slp_byAvg", "W0_cali_slp_byAgt", "W1_cali_slp_byAgt", "W0_cali_slp_ext", "W1_cali_slp_ext", "W0_cali_slp_byAvg_estsd", "W1_cali_slp_byAvg_estsd", "W0_cali_slp_byAgt_estsd", "W1_cali_slp_byAgt_estsd", "W0_cali_slp_ext_estsd", "W1_cali_slp_ext_estsd", "W0_cali_slp_byAvg_rej_rate", "W1_cali_slp_byAvg_rej_rate", "W0_cali_slp_byAgt_rej_rate", "W1_cali_slp_byAgt_rej_rate", "W0_cali_slp_ext_rej_rate", "W1_cali_slp_ext_rej_rate")] = colMeans(res[, c("cali_slp_byAvg_W0", "cali_slp_byAvg_W1", "cali_slp_byAgt_W0", "cali_slp_byAgt_W1", "cali_slp_ext_W0", "cali_slp_ext_W1", "cali_slp_estsd_byAvg_W0", "cali_slp_estsd_byAvg_W1", "cali_slp_estsd_byAgt_W0", "cali_slp_estsd_byAgt_W1", "cali_slp_estsd_ext_W0", "cali_slp_estsd_ext_W1", "cali_slp_rej_byAvg_W0", "cali_slp_rej_byAvg_W1", "cali_slp_rej_byAgt_W0", "cali_slp_rej_byAgt_W1", "cali_slp_rej_ext_W0", "cali_slp_rej_ext_W1")])
  
  out_cali_slp[i, c("W0_cali_slp_byAvg_sd", "W1_cali_slp_byAvg_sd", "W0_cali_slp_byAgt_sd", "W1_cali_slp_byAgt_sd", "W0_cali_slp_ext_sd", "W1_cali_slp_ext_sd")] = apply(res[, c("cali_slp_byAvg_W0", "cali_slp_byAvg_W1", "cali_slp_byAgt_W0", "cali_slp_byAgt_W1", "cali_slp_ext_W0", "cali_slp_ext_W1")], MARGIN = 2, sd)
}
end.t = Sys.time()
cat(end.t - start.t)
stopCluster(myCluster)
out_AUC %>% write.csv("./Stratification by race/AUC.csv", row.names = FALSE)
out_EOR %>% write.csv("./Stratification by race/EOR.csv", row.names = FALSE)
out_cali_intc %>% write.csv("./Stratification by race/Cali_intercept.csv", row.names = FALSE)
out_cali_slp %>% write.csv("./Stratification by race/Cali_slope.csv", row.names = FALSE)
```


# Stratified by outcome
```{r}
out_AUC = paras

out_AUC[, c("W0_AUC_byAvg", "W1_AUC_byAvg", "W0_AUC_byAgt", "W1_AUC_byAgt", "W0_AUC_ext", "W1_AUC_ext", "W0_AUC_byAvg_estsd", "W1_AUC_byAvg_estsd", "W0_AUC_byAgt_estsd", "W1_AUC_byAgt_estsd", "W0_AUC_ext_estsd", "W1_AUC_ext_estsd", "W0_AUC_byAvg_sd", "W1_AUC_byAvg_sd", "W0_AUC_byAgt_sd", "W1_AUC_byAgt_sd", "W0_AUC_ext_sd", "W1_AUC_ext_sd")] = 0


out_EOR = paras
out_EOR[, c("W0_EOR_byAvg", "W1_EOR_byAvg", "W0_EOR_byAgt", "W1_EOR_byAgt", "W0_EOR_ext", "W1_EOR_ext", "W0_EOR_byAvg_estsd", "W1_EOR_byAvg_estsd", "W0_EOR_byAgt_estsd", "W1_EOR_byAgt_estsd", "W0_EOR_ext_estsd", "W1_EOR_ext_estsd", "W0_EOR_byAvg_rej_rate", "W1_EOR_byAvg_rej_rate", "W0_EOR_byAgt_rej_rate", "W1_EOR_byAgt_rej_rate", "W0_EOR_ext_rej_rate", "W1_EOR_ext_rej_rate", "W0_EOR_byAvg_sd", "W1_EOR_byAvg_sd", "W0_EOR_byAgt_sd", "W1_EOR_byAgt_sd", "W0_EOR_ext_sd", "W1_EOR_ext_sd")] = 0

out_cali_intc = paras
out_cali_intc[, c("W0_cali_intc_byAvg", "W1_cali_intc_byAvg", "W0_cali_intc_byAgt", "W1_cali_intc_byAgt", "W0_cali_intc_ext", "W1_cali_intc_ext", "W0_cali_intc_byAvg_estsd", "W1_cali_intc_byAvg_estsd", "W0_cali_intc_byAgt_estsd", "W1_cali_intc_byAgt_estsd", "W0_cali_intc_ext_estsd", "W1_cali_intc_ext_estsd", "W0_cali_intc_byAvg_rej_rate", "W1_cali_intc_byAvg_rej_rate", "W0_cali_intc_byAgt_rej_rate", "W1_cali_intc_byAgt_rej_rate", "W0_cali_intc_ext_rej_rate", "W1_cali_intc_ext_rej_rate", "W0_cali_intc_byAvg_sd", "W1_cali_intc_byAvg_sd", "W0_cali_intc_byAgt_sd", "W1_cali_intc_byAgt_sd", "W0_cali_intc_ext_sd", "W1_cali_intc_ext_sd")] = 0

out_cali_slp = paras
out_cali_slp[, c("W0_cali_slp_byAvg", "W1_cali_slp_byAvg", "W0_cali_slp_byAgt", "W1_cali_slp_byAgt", "W0_cali_slp_ext", "W1_cali_slp_ext", "W0_cali_slp_byAvg_estsd", "W1_cali_slp_byAvg_estsd", "W0_cali_slp_byAgt_estsd", "W1_cali_slp_byAgt_estsd", "W0_cali_slp_ext_estsd", "W1_cali_slp_ext_estsd", "W0_cali_slp_byAvg_rej_rate", "W1_cali_slp_byAvg_rej_rate", "W0_cali_slp_byAgt_rej_rate", "W1_cali_slp_byAgt_rej_rate", "W0_cali_slp_ext_rej_rate", "W1_cali_slp_ext_rej_rate", "W0_cali_slp_byAvg_sd", "W1_cali_slp_byAvg_sd", "W0_cali_slp_byAgt_sd", "W1_cali_slp_byAgt_sd", "W0_cali_slp_ext_sd", "W1_cali_slp_ext_sd")] = 0

myCluster <- makeCluster(detectCores()-1, type = "PSOCK")
registerDoParallel(myCluster)
start.t = Sys.time()
for(i in 1:nrow(paras)){
  cat("\n", i, "\n")
  p_W = paras$Proportion_White[i]
  p_case = paras$Prob_Case[i]
  a = paras$alpha[i]
  num_folds = paras$num_folds[i]
  res = foreach(iter=1:n_iter, .combine = 'rbind', .packages = c("caret", "pROC", "tidyverse")) %dopar%{
    X = MASS::mvrnorm(n = N, mu = mu_X, Sigma = Sigma_X)
    V = sapply(p_V, function(p){rbinom(n = N, size = 1, prob = p)})
    W = rbinom(n = N, size = 1, prob = p_W)
    pos_prob = exp(a + X %*% coef_X + V %*% coef_V + W * coef_W) / (1 + exp(a + X %*% coef_X + V %*% coef_V + W * coef_W))
    case = rbinom(N, 1, pos_prob)
    sim_data = data.frame(X=X, V=V, W=W, case=case)
    
    ext_X = MASS::mvrnorm(n = N, mu = mu_X, Sigma = Sigma_X)
    ext_V = sapply(p_V, function(p){rbinom(n = N, size = 1, prob = p)})
    ext_W = rbinom(n = N, size = 1, prob = p_W)
    ext_pos_prob = exp(a + ext_X %*% coef_X + ext_V %*% coef_V + ext_W * coef_W) / (1 + exp(a + ext_X %*% coef_X + ext_V %*% coef_V + ext_W * coef_W))
    ext_case = rbinom(N, 1, ext_pos_prob)
    ext_data = data.frame(X=ext_X, V=ext_V, W=ext_W, case=ext_case)
    
    full_data_model = glm(case ~ ., data = sim_data, family = binomial())
    ext_data$Y_pred = predict(full_data_model, ext_data, type = "response")
    
    suppressMessages(ext_auc_obj_W0 <- with(ext_data %>% filter(W==0), auc(case, Y_pred)))
    suppressMessages(ext_auc_obj_W1 <- with(ext_data %>% filter(W==1), auc(case, Y_pred)))
    AUC_ext_rep = c(ext_auc_obj_W0[1], ext_auc_obj_W1[1])
    AUC_estsd_ext_rep = c(sqrt(var(ext_auc_obj_W0)), sqrt(var(ext_auc_obj_W1)))
    
    ext_cali_res_W0 = ext_data %>% filter(W==0) %>% calibrationMetrics(risk_var = "Y_pred", weak_cali_ind = FALSE, correlated = FALSE)
    ext_cali_res_W1 = ext_data %>% filter(W==1) %>% calibrationMetrics(risk_var = "Y_pred", weak_cali_ind = FALSE, correlated = FALSE)
    
    CVTrainFolds = createFolds(as.factor(sim_data$case), k = num_folds, list = TRUE, returnTrain = TRUE)
    
    test_Y_true = NULL
    test_Y_pred = NULL
    test_W = NULL
    AUC_byAvg_vec_folds = matrix(0, nrow = num_folds, ncol = length(p_W) + 1)
    EOR_byAvg_vec_folds = matrix(0, nrow = num_folds, ncol = length(p_W) + 1)
    cali_intc_byAvg_vec_folds = matrix(0, nrow = num_folds, ncol = length(p_W) + 1)
    cali_slp_byAvg_vec_folds = matrix(0, nrow = num_folds, ncol = length(p_W) + 1)
    AUC_estsd_byAvg_vec_folds = matrix(0, nrow = num_folds, ncol = length(p_W) + 1)
    EOR_estsd_byAvg_vec_folds = matrix(0, nrow = num_folds, ncol = length(p_W) + 1)
    cali_intc_estsd_byAvg_vec_folds = matrix(0, nrow = num_folds, ncol = length(p_W) + 1)
    cali_slp_estsd_byAvg_vec_folds = matrix(0, nrow = num_folds, ncol = length(p_W) + 1)
    for(cv_iter in 1:num_folds){
      train_id = CVTrainFolds[[cv_iter]]
      cv_train_data = sim_data[train_id, ]
      cv_test_data = sim_data[-train_id, ]
      test_Y_true = c(test_Y_true, cv_test_data$case)
      test_W = c(test_W, cv_test_data$W)
      cv_model = glm(case ~ ., data = cv_train_data, family = binomial())
      cv_Y_ped = predict(cv_model, cv_test_data, type = "response")
      test_Y_pred = c(test_Y_pred, cv_Y_ped)
      cv_test_data$Y_pred = cv_Y_ped
      suppressMessages(auc_byAvg_obj_W0 <- with(cv_test_data %>% filter(W==0), auc(case, Y_pred)))
      suppressMessages(auc_byAvg_obj_W1 <- with(cv_test_data %>% filter(W==1), auc(case, Y_pred)))
      
      AUC_byAvg_vec_folds[cv_iter, ] = c(auc_byAvg_obj_W0[1], auc_byAvg_obj_W1[1])
      AUC_estsd_byAvg_vec_folds[cv_iter, ] = c(sqrt(var(auc_byAvg_obj_W0)), sqrt(var(auc_byAvg_obj_W1)))
      
      cv_cali_res_W0 = cv_test_data %>% filter(W==0) %>% calibrationMetrics(risk_var = "Y_pred", weak_cali_ind = FALSE, correlated = FALSE)
      cv_cali_res_W1 = cv_test_data %>% filter(W==1) %>% calibrationMetrics(risk_var = "Y_pred", weak_cali_ind = FALSE, correlated = FALSE)
      
      EOR_byAvg_vec_folds[cv_iter, ] = c(cv_cali_res_W0$EORatio["EORatio"][[1]], cv_cali_res_W1$EORatio["EORatio"][[1]])
      cali_intc_byAvg_vec_folds[cv_iter, ] = c(cv_cali_res_W0$cox_intercept["cox_intercept"][[1]], cv_cali_res_W1$cox_intercept["cox_intercept"][[1]])
      cali_slp_byAvg_vec_folds[cv_iter, ] = c(cv_cali_res_W0$cox_slope["cox_slope"][[1]], cv_cali_res_W1$cox_slope["cox_slope"][[1]])
      
      EOR_estsd_byAvg_vec_folds[cv_iter, ] = c(cv_cali_res_W0$EORatio["se_EORatio"][[1]], cv_cali_res_W1$EORatio["se_EORatio"][[1]])
      cali_intc_estsd_byAvg_vec_folds[cv_iter, ] = c(cv_cali_res_W0$cox_intercept["cox_intercept_se"][[1]], cv_cali_res_W1$cox_intercept["cox_intercept_se"][[1]])
      cali_slp_estsd_byAvg_vec_folds[cv_iter, ] = c(cv_cali_res_W0$cox_slope["cox_slope_se"][[1]], cv_cali_res_W1$cox_slope["cox_slope_se"][[1]])
    }
    AUC_byAvg_rep = colMeans(AUC_byAvg_vec_folds)
    EOR_byAvg_rep = colMeans(EOR_byAvg_vec_folds)
    cali_intc_byAvg_rep = colMeans(cali_intc_byAvg_vec_folds)
    cali_slp_byAvg_rep = colMeans(cali_slp_byAvg_vec_folds)
    
    AUC_estsd_byAvg_rep = colMeans(AUC_estsd_byAvg_vec_folds)/sqrt(num_folds)
    EOR_estsd_byAvg_rep = colMeans(EOR_estsd_byAvg_vec_folds)/sqrt(num_folds)
    cali_intc_estsd_byAvg_rep = colMeans(cali_intc_estsd_byAvg_vec_folds)/sqrt(num_folds)
    cali_slp_estsd_byAvg_rep = colMeans(cali_slp_estsd_byAvg_vec_folds)/sqrt(num_folds)
    
    all_test_dt = data.frame(W=test_W, case=test_Y_true, Y_pred=test_Y_pred)
    suppressMessages(auc_byAgt_obj_W0 <- with(all_test_dt %>% filter(W==0), auc(case, Y_pred)))
    suppressMessages(auc_byAgt_obj_W1 <- with(all_test_dt %>% filter(W==1), auc(case, Y_pred)))
    
    AUC_byAgt_rep = c(auc_byAgt_obj_W0[1], auc_byAgt_obj_W1[1])
    AUC_estsd_byAgt_rep = c(sqrt(var(auc_byAgt_obj_W0)), sqrt(var(auc_byAgt_obj_W1)))
    
    cali_res_byAgt_W0 = all_test_dt %>% filter(W==0) %>% calibrationMetrics(risk_var = "Y_pred", weak_cali_ind = FALSE, correlated = FALSE)
    cali_res_byAgt_W1 = all_test_dt %>% filter(W==1) %>% calibrationMetrics(risk_var = "Y_pred", weak_cali_ind = FALSE, correlated = FALSE)
    
    c("AUC_ext_W0"=AUC_ext_rep[1], "AUC_ext_W1"=AUC_ext_rep[2],
      "AUC_estsd_ext_W0"=AUC_estsd_ext_rep[1], "AUC_estsd_ext_W1"=AUC_estsd_ext_rep[2],
      
      "EOR_ext_W0"=ext_cali_res_W0$EORatio["EORatio"][[1]], "EOR_ext_W1"=ext_cali_res_W1$EORatio["EORatio"][[1]],
      "EOR_estsd_ext_W0"=ext_cali_res_W0$EORatio["se_EORatio"][[1]], "EOR_estsd_ext_W1"=ext_cali_res_W1$EORatio["se_EORatio"][[1]],
      "EOR_rej_ext_W0"= 1 < ext_cali_res_W0$EORatio["EORatio_cilb"][[1]] | 1 > ext_cali_res_W0$EORatio["EORatio_ciub"][[1]],
      "EOR_rej_ext_W1"= 1 < ext_cali_res_W1$EORatio["EORatio_cilb"][[1]] | 1 > ext_cali_res_W1$EORatio["EORatio_ciub"][[1]],
      
      "cali_intc_ext_W0"=ext_cali_res_W0$cox_intercept["cox_intercept"][[1]], "cali_intc_ext_W1"=ext_cali_res_W1$cox_intercept["cox_intercept"][[1]],
      "cali_intc_estsd_ext_W0"=ext_cali_res_W0$cox_intercept["cox_intercept_se"][[1]], "cali_intc_estsd_ext_W1"=ext_cali_res_W1$cox_intercept["cox_intercept_se"][[1]],
      "cali_intc_rej_ext_W0" = 0 < ext_cali_res_W0$cox_intercept["cox_intercept_cilb"][[1]] | 0 > ext_cali_res_W0$cox_intercept["cox_intercept_ciub"][[1]],
      "cali_intc_rej_ext_W1" = 0 < ext_cali_res_W1$cox_intercept["cox_intercept_cilb"][[1]] | 0 > ext_cali_res_W1$cox_intercept["cox_intercept_ciub"][[1]],
      
      "cali_slp_ext_W0"=ext_cali_res_W0$cox_slope["cox_slope"][[1]], "cali_slp_ext_W1"=ext_cali_res_W1$cox_slope["cox_slope"][[1]],
      "cali_slp_estsd_ext_W0"=ext_cali_res_W0$cox_slope["cox_slope_se"][[1]], "cali_slp_estsd_ext_W1"=ext_cali_res_W1$cox_slope["cox_slope_se"][[1]],
      "cali_slp_rej_ext_W0" = 1 < ext_cali_res_W0$cox_slope["cox_slope_cilb"][[1]] | 1 > ext_cali_res_W0$cox_slope["cox_slope_ciub"][[1]],
      "cali_slp_rej_ext_W1" = 1 < ext_cali_res_W1$cox_slope["cox_slope_cilb"][[1]] | 1 > ext_cali_res_W1$cox_slope["cox_slope_ciub"][[1]],
      
      "AUC_byAvg_W0"=AUC_byAvg_rep[1], "AUC_byAvg_W1"=AUC_byAvg_rep[2],
      "AUC_estsd_byAvg_W0"=AUC_estsd_byAvg_rep[1], "AUC_estsd_byAvg_W1"=AUC_estsd_byAvg_rep[2],
      
      "EOR_byAvg_W0"=EOR_byAvg_rep[1], "EOR_byAvg_W1"=EOR_byAvg_rep[2],
      "EOR_estsd_byAvg_W0" = EOR_estsd_byAvg_rep[1], "EOR_estsd_byAvg_W1"=EOR_estsd_byAvg_rep[2],
      "EOR_rej_byAvg_W0" = 1 < EOR_byAvg_rep[1] - qnorm(0.975) * EOR_estsd_byAvg_rep[1] | 1 > EOR_byAvg_rep[1] + qnorm(0.975) * EOR_estsd_byAvg_rep[1],
      "EOR_rej_byAvg_W1" = 1 < EOR_byAvg_rep[2] - qnorm(0.975) * EOR_estsd_byAvg_rep[2] | 1 > EOR_byAvg_rep[2] + qnorm(0.975) * EOR_estsd_byAvg_rep[2],
      
      "cali_intc_byAvg_W0"=cali_intc_byAvg_rep[1], "cali_intc_byAvg_W1"=cali_intc_byAvg_rep[2],
      "cali_intc_estsd_byAvg_W0" = cali_intc_estsd_byAvg_rep[1], "cali_intc_estsd_byAvg_W1"=cali_intc_estsd_byAvg_rep[2],
      "cali_intc_rej_byAvg_W0" = 0 < cali_intc_byAvg_rep[1] - qnorm(0.975) * cali_intc_estsd_byAvg_rep[1] | 0 > cali_intc_byAvg_rep[1] + qnorm(0.975) * cali_intc_estsd_byAvg_rep[1],
      "cali_intc_rej_byAvg_W1" = 0 < cali_intc_byAvg_rep[2] - qnorm(0.975) * cali_intc_estsd_byAvg_rep[2] | 0 > cali_intc_byAvg_rep[2] + qnorm(0.975) * cali_intc_estsd_byAvg_rep[2],
      
      "cali_slp_byAvg_W0"=cali_slp_byAvg_rep[1], "cali_slp_byAvg_W1"=cali_slp_byAvg_rep[2],
      "cali_slp_estsd_byAvg_W0" = cali_slp_estsd_byAvg_rep[1], "cali_slp_estsd_byAvg_W1"=cali_slp_estsd_byAvg_rep[2],
      "cali_slp_rej_byAvg_W0" = 1 < cali_slp_byAvg_rep[1] - qnorm(0.975) * cali_slp_estsd_byAvg_rep[1] | 1 > cali_slp_byAvg_rep[1] + qnorm(0.975) * cali_slp_estsd_byAvg_rep[1],
      "cali_slp_rej_byAvg_W1" = 1 < cali_slp_byAvg_rep[2] - qnorm(0.975) * cali_slp_estsd_byAvg_rep[2] | 1 > cali_slp_byAvg_rep[2] + qnorm(0.975) * cali_slp_estsd_byAvg_rep[2],
      
      "AUC_byAgt_W0"=AUC_byAgt_rep[1], "AUC_byAgt_W1"=AUC_byAgt_rep[2],
      "AUC_estsd_byAgt_W0"=AUC_estsd_byAgt_rep[1], "AUC_estsd_byAgt_W1"=AUC_estsd_byAgt_rep[2],
      
      "EOR_byAgt_W0"=cali_res_byAgt_W0$EORatio["EORatio"][[1]], "EOR_byAgt_W1"=cali_res_byAgt_W1$EORatio["EORatio"][[1]],
      "EOR_estsd_byAgt_W0"=cali_res_byAgt_W0$EORatio["se_EORatio"][[1]], "EOR_estsd_byAgt_W1"=cali_res_byAgt_W1$EORatio["se_EORatio"][[1]],
      "EOR_rej_byAgt_W0"= 1 < cali_res_byAgt_W0$EORatio["EORatio_cilb"][[1]] | 1 > cali_res_byAgt_W0$EORatio["EORatio_ciub"][[1]],
      "EOR_rej_byAgt_W1"= 1 < cali_res_byAgt_W1$EORatio["EORatio_cilb"][[1]] | 1 > cali_res_byAgt_W1$EORatio["EORatio_ciub"][[1]],
      
      "cali_intc_byAgt_W0"=cali_res_byAgt_W0$cox_intercept["cox_intercept"][[1]], "cali_intc_byAgt_W1"=cali_res_byAgt_W1$cox_intercept["cox_intercept"][[1]],
      "cali_intc_estsd_byAgt_W0"=cali_res_byAgt_W0$cox_intercept["cox_intercept_se"][[1]], "cali_intc_estsd_byAgt_W1"=cali_res_byAgt_W1$cox_intercept["cox_intercept_se"][[1]],
      "cali_intc_rej_byAgt_W0" = 0 < cali_res_byAgt_W0$cox_intercept["cox_intercept_cilb"][[1]] | 0 > cali_res_byAgt_W0$cox_intercept["cox_intercept_ciub"][[1]],
      "cali_intc_rej_byAgt_W1" = 0 < cali_res_byAgt_W1$cox_intercept["cox_intercept_cilb"][[1]] | 0 > cali_res_byAgt_W1$cox_intercept["cox_intercept_ciub"][[1]],
      
      "cali_slp_byAgt_W0"=cali_res_byAgt_W0$cox_slope["cox_slope"][[1]], "cali_slp_byAgt_W1"=cali_res_byAgt_W1$cox_slope["cox_slope"][[1]],
      "cali_slp_estsd_byAgt_W0"=cali_res_byAgt_W0$cox_slope["cox_slope_se"][[1]], "cali_slp_estsd_byAgt_W1"=cali_res_byAgt_W1$cox_slope["cox_slope_se"][[1]],
      "cali_slp_rej_byAgt_W0" = 1 < cali_res_byAgt_W0$cox_slope["cox_slope_cilb"][[1]] | 1 > cali_res_byAgt_W0$cox_slope["cox_slope_ciub"][[1]],
      "cali_slp_rej_byAgt_W1" = 1 < cali_res_byAgt_W1$cox_slope["cox_slope_cilb"][[1]] | 1 > cali_res_byAgt_W1$cox_slope["cox_slope_ciub"][[1]])
  }
  
  
  out_AUC[i, c("W0_AUC_byAvg", "W1_AUC_byAvg", "W0_AUC_byAgt", "W1_AUC_byAgt", "W0_AUC_ext", "W1_AUC_ext", "W0_AUC_byAvg_estsd", "W1_AUC_byAvg_estsd", "W0_AUC_byAgt_estsd", "W1_AUC_byAgt_estsd", "W0_AUC_ext_estsd", "W1_AUC_ext_estsd")] = colMeans(res[, c("AUC_byAvg_W0", "AUC_byAvg_W1", "AUC_byAgt_W0", "AUC_byAgt_W1", "AUC_ext_W0", "AUC_ext_W1", "AUC_estsd_byAvg_W0", "AUC_estsd_byAvg_W1", "AUC_estsd_byAgt_W0", "AUC_estsd_byAgt_W1", "AUC_estsd_ext_W0", "AUC_estsd_ext_W1")])
  
  out_AUC[i, c("W0_AUC_byAvg_sd", "W1_AUC_byAvg_sd", "W0_AUC_byAgt_sd", "W1_AUC_byAgt_sd", "W0_AUC_ext_sd", "W1_AUC_ext_sd")] = apply(res[, c("AUC_byAvg_W0", "AUC_byAvg_W1", "AUC_byAgt_W0", "AUC_byAgt_W1", "AUC_ext_W0", "AUC_ext_W1")], MARGIN = 2, sd)
  
  out_EOR[i, c("W0_EOR_byAvg", "W1_EOR_byAvg", "W0_EOR_byAgt", "W1_EOR_byAgt", "W0_EOR_ext", "W1_EOR_ext", "W0_EOR_byAvg_estsd", "W1_EOR_byAvg_estsd", "W0_EOR_byAgt_estsd", "W1_EOR_byAgt_estsd", "W0_EOR_ext_estsd", "W1_EOR_ext_estsd", "W0_EOR_byAvg_rej_rate", "W1_EOR_byAvg_rej_rate", "W0_EOR_byAgt_rej_rate", "W1_EOR_byAgt_rej_rate", "W0_EOR_ext_rej_rate", "W1_EOR_ext_rej_rate")] = colMeans(res[, c("EOR_byAvg_W0", "EOR_byAvg_W1", "EOR_byAgt_W0", "EOR_byAgt_W1", "EOR_ext_W0", "EOR_ext_W1", "EOR_estsd_byAvg_W0", "EOR_estsd_byAvg_W1", "EOR_estsd_byAgt_W0", "EOR_estsd_byAgt_W1", "EOR_estsd_ext_W0", "EOR_estsd_ext_W1", "EOR_rej_byAvg_W0", "EOR_rej_byAvg_W1", "EOR_rej_byAgt_W0", "EOR_rej_byAgt_W1", "EOR_rej_ext_W0", "EOR_rej_ext_W1")])
  
  out_EOR[i, c("W0_EOR_byAvg_sd", "W1_EOR_byAvg_sd", "W0_EOR_byAgt_sd", "W1_EOR_byAgt_sd", "W0_EOR_ext_sd", "W1_EOR_ext_sd")] = apply(res[, c("EOR_byAvg_W0", "EOR_byAvg_W1", "EOR_byAgt_W0", "EOR_byAgt_W1", "EOR_ext_W0", "EOR_ext_W1")], MARGIN = 2, sd)
  
  out_cali_intc[i, c("W0_cali_intc_byAvg", "W1_cali_intc_byAvg", "W0_cali_intc_byAgt", "W1_cali_intc_byAgt", "W0_cali_intc_ext", "W1_cali_intc_ext", "W0_cali_intc_byAvg_estsd", "W1_cali_intc_byAvg_estsd", "W0_cali_intc_byAgt_estsd", "W1_cali_intc_byAgt_estsd", "W0_cali_intc_ext_estsd", "W1_cali_intc_ext_estsd", "W0_cali_intc_byAvg_rej_rate", "W1_cali_intc_byAvg_rej_rate", "W0_cali_intc_byAgt_rej_rate", "W1_cali_intc_byAgt_rej_rate", "W0_cali_intc_ext_rej_rate", "W1_cali_intc_ext_rej_rate")] = colMeans(res[, c("cali_intc_byAvg_W0", "cali_intc_byAvg_W1", "cali_intc_byAgt_W0", "cali_intc_byAgt_W1", "cali_intc_ext_W0", "cali_intc_ext_W1", "cali_intc_estsd_byAvg_W0", "cali_intc_estsd_byAvg_W1", "cali_intc_estsd_byAgt_W0", "cali_intc_estsd_byAgt_W1", "cali_intc_estsd_ext_W0", "cali_intc_estsd_ext_W1", "cali_intc_rej_byAvg_W0", "cali_intc_rej_byAvg_W1", "cali_intc_rej_byAgt_W0", "cali_intc_rej_byAgt_W1", "cali_intc_rej_ext_W0", "cali_intc_rej_ext_W1")])
  
  out_cali_intc[i, c("W0_cali_intc_byAvg_sd", "W1_cali_intc_byAvg_sd", "W0_cali_intc_byAgt_sd", "W1_cali_intc_byAgt_sd", "W0_cali_intc_ext_sd", "W1_cali_intc_ext_sd")] = apply(res[, c("cali_intc_byAvg_W0", "cali_intc_byAvg_W1", "cali_intc_byAgt_W0", "cali_intc_byAgt_W1", "cali_intc_ext_W0", "cali_intc_ext_W1")], MARGIN = 2, sd)
  
  out_cali_slp[i, c("W0_cali_slp_byAvg", "W1_cali_slp_byAvg", "W0_cali_slp_byAgt", "W1_cali_slp_byAgt", "W0_cali_slp_ext", "W1_cali_slp_ext", "W0_cali_slp_byAvg_estsd", "W1_cali_slp_byAvg_estsd", "W0_cali_slp_byAgt_estsd", "W1_cali_slp_byAgt_estsd", "W0_cali_slp_ext_estsd", "W1_cali_slp_ext_estsd", "W0_cali_slp_byAvg_rej_rate", "W1_cali_slp_byAvg_rej_rate", "W0_cali_slp_byAgt_rej_rate", "W1_cali_slp_byAgt_rej_rate", "W0_cali_slp_ext_rej_rate", "W1_cali_slp_ext_rej_rate")] = colMeans(res[, c("cali_slp_byAvg_W0", "cali_slp_byAvg_W1", "cali_slp_byAgt_W0", "cali_slp_byAgt_W1", "cali_slp_ext_W0", "cali_slp_ext_W1", "cali_slp_estsd_byAvg_W0", "cali_slp_estsd_byAvg_W1", "cali_slp_estsd_byAgt_W0", "cali_slp_estsd_byAgt_W1", "cali_slp_estsd_ext_W0", "cali_slp_estsd_ext_W1", "cali_slp_rej_byAvg_W0", "cali_slp_rej_byAvg_W1", "cali_slp_rej_byAgt_W0", "cali_slp_rej_byAgt_W1", "cali_slp_rej_ext_W0", "cali_slp_rej_ext_W1")])
  
  out_cali_slp[i, c("W0_cali_slp_byAvg_sd", "W1_cali_slp_byAvg_sd", "W0_cali_slp_byAgt_sd", "W1_cali_slp_byAgt_sd", "W0_cali_slp_ext_sd", "W1_cali_slp_ext_sd")] = apply(res[, c("cali_slp_byAvg_W0", "cali_slp_byAvg_W1", "cali_slp_byAgt_W0", "cali_slp_byAgt_W1", "cali_slp_ext_W0", "cali_slp_ext_W1")], MARGIN = 2, sd)
}
end.t = Sys.time()
cat(end.t - start.t)
stopCluster(myCluster)
out_AUC %>% write.csv("./Stratification by outcome/AUC.csv", row.names = FALSE)
out_EOR %>% write.csv("./Stratification by outcome/EOR.csv", row.names = FALSE)
out_cali_intc %>% write.csv("./Stratification by outcome/Cali_intercept.csv", row.names = FALSE)
out_cali_slp %>% write.csv("./Stratification by outcome/Cali_slope.csv", row.names = FALSE)
```


# No stratification
```{r}
out_AUC = paras

out_AUC[, c("W0_AUC_byAvg", "W1_AUC_byAvg", "W0_AUC_byAgt", "W1_AUC_byAgt", "W0_AUC_ext", "W1_AUC_ext", "W0_AUC_byAvg_estsd", "W1_AUC_byAvg_estsd", "W0_AUC_byAgt_estsd", "W1_AUC_byAgt_estsd", "W0_AUC_ext_estsd", "W1_AUC_ext_estsd", "W0_AUC_byAvg_sd", "W1_AUC_byAvg_sd", "W0_AUC_byAgt_sd", "W1_AUC_byAgt_sd", "W0_AUC_ext_sd", "W1_AUC_ext_sd")] = 0


out_EOR = paras
out_EOR[, c("W0_EOR_byAvg", "W1_EOR_byAvg", "W0_EOR_byAgt", "W1_EOR_byAgt", "W0_EOR_ext", "W1_EOR_ext", "W0_EOR_byAvg_estsd", "W1_EOR_byAvg_estsd", "W0_EOR_byAgt_estsd", "W1_EOR_byAgt_estsd", "W0_EOR_ext_estsd", "W1_EOR_ext_estsd", "W0_EOR_byAvg_rej_rate", "W1_EOR_byAvg_rej_rate", "W0_EOR_byAgt_rej_rate", "W1_EOR_byAgt_rej_rate", "W0_EOR_ext_rej_rate", "W1_EOR_ext_rej_rate", "W0_EOR_byAvg_sd", "W1_EOR_byAvg_sd", "W0_EOR_byAgt_sd", "W1_EOR_byAgt_sd", "W0_EOR_ext_sd", "W1_EOR_ext_sd")] = 0

out_cali_intc = paras
out_cali_intc[, c("W0_cali_intc_byAvg", "W1_cali_intc_byAvg", "W0_cali_intc_byAgt", "W1_cali_intc_byAgt", "W0_cali_intc_ext", "W1_cali_intc_ext", "W0_cali_intc_byAvg_estsd", "W1_cali_intc_byAvg_estsd", "W0_cali_intc_byAgt_estsd", "W1_cali_intc_byAgt_estsd", "W0_cali_intc_ext_estsd", "W1_cali_intc_ext_estsd", "W0_cali_intc_byAvg_rej_rate", "W1_cali_intc_byAvg_rej_rate", "W0_cali_intc_byAgt_rej_rate", "W1_cali_intc_byAgt_rej_rate", "W0_cali_intc_ext_rej_rate", "W1_cali_intc_ext_rej_rate", "W0_cali_intc_byAvg_sd", "W1_cali_intc_byAvg_sd", "W0_cali_intc_byAgt_sd", "W1_cali_intc_byAgt_sd", "W0_cali_intc_ext_sd", "W1_cali_intc_ext_sd")] = 0

out_cali_slp = paras
out_cali_slp[, c("W0_cali_slp_byAvg", "W1_cali_slp_byAvg", "W0_cali_slp_byAgt", "W1_cali_slp_byAgt", "W0_cali_slp_ext", "W1_cali_slp_ext", "W0_cali_slp_byAvg_estsd", "W1_cali_slp_byAvg_estsd", "W0_cali_slp_byAgt_estsd", "W1_cali_slp_byAgt_estsd", "W0_cali_slp_ext_estsd", "W1_cali_slp_ext_estsd", "W0_cali_slp_byAvg_rej_rate", "W1_cali_slp_byAvg_rej_rate", "W0_cali_slp_byAgt_rej_rate", "W1_cali_slp_byAgt_rej_rate", "W0_cali_slp_ext_rej_rate", "W1_cali_slp_ext_rej_rate", "W0_cali_slp_byAvg_sd", "W1_cali_slp_byAvg_sd", "W0_cali_slp_byAgt_sd", "W1_cali_slp_byAgt_sd", "W0_cali_slp_ext_sd", "W1_cali_slp_ext_sd")] = 0

myCluster <- makeCluster(detectCores()-1, type = "PSOCK")
registerDoParallel(myCluster)
start.t = Sys.time()
for(i in 1:nrow(paras)){
  cat("\n", i, "\n")
  p_W = paras$Proportion_White[i]
  p_case = paras$Prob_Case[i]
  a = paras$alpha[i]
  num_folds = paras$num_folds[i]
  res = foreach(iter=1:n_iter, .combine = 'rbind', .packages = c("caret", "pROC", "tidyverse")) %dopar%{
    X = MASS::mvrnorm(n = N, mu = mu_X, Sigma = Sigma_X)
    V = sapply(p_V, function(p){rbinom(n = N, size = 1, prob = p)})
    W = rbinom(n = N, size = 1, prob = p_W)
    pos_prob = exp(a + X %*% coef_X + V %*% coef_V + W * coef_W) / (1 + exp(a + X %*% coef_X + V %*% coef_V + W * coef_W))
    case = rbinom(N, 1, pos_prob)
    sim_data = data.frame(X=X, V=V, W=W, case=case)
    
    ext_X = MASS::mvrnorm(n = N, mu = mu_X, Sigma = Sigma_X)
    ext_V = sapply(p_V, function(p){rbinom(n = N, size = 1, prob = p)})
    ext_W = rbinom(n = N, size = 1, prob = p_W)
    ext_pos_prob = exp(a + ext_X %*% coef_X + ext_V %*% coef_V + ext_W * coef_W) / (1 + exp(a + ext_X %*% coef_X + ext_V %*% coef_V + ext_W * coef_W))
    ext_case = rbinom(N, 1, ext_pos_prob)
    ext_data = data.frame(X=ext_X, V=ext_V, W=ext_W, case=ext_case)
    
    full_data_model = glm(case ~ ., data = sim_data, family = binomial())
    ext_data$Y_pred = predict(full_data_model, ext_data, type = "response")
    
    suppressMessages(ext_auc_obj_W0 <- with(ext_data %>% filter(W==0), auc(case, Y_pred)))
    suppressMessages(ext_auc_obj_W1 <- with(ext_data %>% filter(W==1), auc(case, Y_pred)))
    AUC_ext_rep = c(ext_auc_obj_W0[1], ext_auc_obj_W1[1])
    AUC_estsd_ext_rep = c(sqrt(var(ext_auc_obj_W0)), sqrt(var(ext_auc_obj_W1)))
    
    ext_cali_res_W0 = ext_data %>% filter(W==0) %>% calibrationMetrics(risk_var = "Y_pred", weak_cali_ind = FALSE, correlated = FALSE)
    ext_cali_res_W1 = ext_data %>% filter(W==1) %>% calibrationMetrics(risk_var = "Y_pred", weak_cali_ind = FALSE, correlated = FALSE)
    
    folds = cut(seq(1, N), breaks=num_folds, labels=FALSE)
    folds = folds[sample(1:N, size = N, replace = FALSE)]
    
    test_Y_true = NULL
    test_Y_pred = NULL
    test_W = NULL
    AUC_byAvg_vec_folds = matrix(0, nrow = num_folds, ncol = length(p_W) + 1)
    EOR_byAvg_vec_folds = matrix(0, nrow = num_folds, ncol = length(p_W) + 1)
    cali_intc_byAvg_vec_folds = matrix(0, nrow = num_folds, ncol = length(p_W) + 1)
    cali_slp_byAvg_vec_folds = matrix(0, nrow = num_folds, ncol = length(p_W) + 1)
    AUC_estsd_byAvg_vec_folds = matrix(0, nrow = num_folds, ncol = length(p_W) + 1)
    EOR_estsd_byAvg_vec_folds = matrix(0, nrow = num_folds, ncol = length(p_W) + 1)
    cali_intc_estsd_byAvg_vec_folds = matrix(0, nrow = num_folds, ncol = length(p_W) + 1)
    cali_slp_estsd_byAvg_vec_folds = matrix(0, nrow = num_folds, ncol = length(p_W) + 1)
    for(cv_iter in 1:num_folds){
      test_id = which(folds == cv_iter)
      cv_train_data = sim_data[-test_id, ]
      cv_test_data = sim_data[test_id, ]
      test_Y_true = c(test_Y_true, cv_test_data$case)
      test_W = c(test_W, cv_test_data$W)
      cv_model = glm(case ~ ., data = cv_train_data, family = binomial())
      cv_Y_ped = predict(cv_model, cv_test_data, type = "response")
      test_Y_pred = c(test_Y_pred, cv_Y_ped)
      cv_test_data$Y_pred = cv_Y_ped
      suppressMessages(auc_byAvg_obj_W0 <- with(cv_test_data %>% filter(W==0), auc(case, Y_pred)))
      suppressMessages(auc_byAvg_obj_W1 <- with(cv_test_data %>% filter(W==1), auc(case, Y_pred)))
      
      AUC_byAvg_vec_folds[cv_iter, ] = c(auc_byAvg_obj_W0[1], auc_byAvg_obj_W1[1])
      AUC_estsd_byAvg_vec_folds[cv_iter, ] = c(sqrt(var(auc_byAvg_obj_W0)), sqrt(var(auc_byAvg_obj_W1)))
      
      cv_cali_res_W0 = cv_test_data %>% filter(W==0) %>% calibrationMetrics(risk_var = "Y_pred", weak_cali_ind = FALSE, correlated = FALSE)
      cv_cali_res_W1 = cv_test_data %>% filter(W==1) %>% calibrationMetrics(risk_var = "Y_pred", weak_cali_ind = FALSE, correlated = FALSE)
      
      EOR_byAvg_vec_folds[cv_iter, ] = c(cv_cali_res_W0$EORatio["EORatio"][[1]], cv_cali_res_W1$EORatio["EORatio"][[1]])
      cali_intc_byAvg_vec_folds[cv_iter, ] = c(cv_cali_res_W0$cox_intercept["cox_intercept"][[1]], cv_cali_res_W1$cox_intercept["cox_intercept"][[1]])
      cali_slp_byAvg_vec_folds[cv_iter, ] = c(cv_cali_res_W0$cox_slope["cox_slope"][[1]], cv_cali_res_W1$cox_slope["cox_slope"][[1]])
      
      EOR_estsd_byAvg_vec_folds[cv_iter, ] = c(cv_cali_res_W0$EORatio["se_EORatio"][[1]], cv_cali_res_W1$EORatio["se_EORatio"][[1]])
      cali_intc_estsd_byAvg_vec_folds[cv_iter, ] = c(cv_cali_res_W0$cox_intercept["cox_intercept_se"][[1]], cv_cali_res_W1$cox_intercept["cox_intercept_se"][[1]])
      cali_slp_estsd_byAvg_vec_folds[cv_iter, ] = c(cv_cali_res_W0$cox_slope["cox_slope_se"][[1]], cv_cali_res_W1$cox_slope["cox_slope_se"][[1]])
    }
    AUC_byAvg_rep = colMeans(AUC_byAvg_vec_folds)
    EOR_byAvg_rep = colMeans(EOR_byAvg_vec_folds)
    cali_intc_byAvg_rep = colMeans(cali_intc_byAvg_vec_folds)
    cali_slp_byAvg_rep = colMeans(cali_slp_byAvg_vec_folds)
    
    AUC_estsd_byAvg_rep = colMeans(AUC_estsd_byAvg_vec_folds)/sqrt(num_folds)
    EOR_estsd_byAvg_rep = colMeans(EOR_estsd_byAvg_vec_folds)/sqrt(num_folds)
    cali_intc_estsd_byAvg_rep = colMeans(cali_intc_estsd_byAvg_vec_folds)/sqrt(num_folds)
    cali_slp_estsd_byAvg_rep = colMeans(cali_slp_estsd_byAvg_vec_folds)/sqrt(num_folds)
    
    all_test_dt = data.frame(W=test_W, case=test_Y_true, Y_pred=test_Y_pred)
    suppressMessages(auc_byAgt_obj_W0 <- with(all_test_dt %>% filter(W==0), auc(case, Y_pred)))
    suppressMessages(auc_byAgt_obj_W1 <- with(all_test_dt %>% filter(W==1), auc(case, Y_pred)))
    
    AUC_byAgt_rep = c(auc_byAgt_obj_W0[1], auc_byAgt_obj_W1[1])
    AUC_estsd_byAgt_rep = c(sqrt(var(auc_byAgt_obj_W0)), sqrt(var(auc_byAgt_obj_W1)))
    
    cali_res_byAgt_W0 = all_test_dt %>% filter(W==0) %>% calibrationMetrics(risk_var = "Y_pred", weak_cali_ind = FALSE, correlated = FALSE)
    cali_res_byAgt_W1 = all_test_dt %>% filter(W==1) %>% calibrationMetrics(risk_var = "Y_pred", weak_cali_ind = FALSE, correlated = FALSE)
    
    c("AUC_ext_W0"=AUC_ext_rep[1], "AUC_ext_W1"=AUC_ext_rep[2],
      "AUC_estsd_ext_W0"=AUC_estsd_ext_rep[1], "AUC_estsd_ext_W1"=AUC_estsd_ext_rep[2],
      
      "EOR_ext_W0"=ext_cali_res_W0$EORatio["EORatio"][[1]], "EOR_ext_W1"=ext_cali_res_W1$EORatio["EORatio"][[1]],
      "EOR_estsd_ext_W0"=ext_cali_res_W0$EORatio["se_EORatio"][[1]], "EOR_estsd_ext_W1"=ext_cali_res_W1$EORatio["se_EORatio"][[1]],
      "EOR_rej_ext_W0"= 1 < ext_cali_res_W0$EORatio["EORatio_cilb"][[1]] | 1 > ext_cali_res_W0$EORatio["EORatio_ciub"][[1]],
      "EOR_rej_ext_W1"= 1 < ext_cali_res_W1$EORatio["EORatio_cilb"][[1]] | 1 > ext_cali_res_W1$EORatio["EORatio_ciub"][[1]],
      
      "cali_intc_ext_W0"=ext_cali_res_W0$cox_intercept["cox_intercept"][[1]], "cali_intc_ext_W1"=ext_cali_res_W1$cox_intercept["cox_intercept"][[1]],
      "cali_intc_estsd_ext_W0"=ext_cali_res_W0$cox_intercept["cox_intercept_se"][[1]], "cali_intc_estsd_ext_W1"=ext_cali_res_W1$cox_intercept["cox_intercept_se"][[1]],
      "cali_intc_rej_ext_W0" = 0 < ext_cali_res_W0$cox_intercept["cox_intercept_cilb"][[1]] | 0 > ext_cali_res_W0$cox_intercept["cox_intercept_ciub"][[1]],
      "cali_intc_rej_ext_W1" = 0 < ext_cali_res_W1$cox_intercept["cox_intercept_cilb"][[1]] | 0 > ext_cali_res_W1$cox_intercept["cox_intercept_ciub"][[1]],
      
      "cali_slp_ext_W0"=ext_cali_res_W0$cox_slope["cox_slope"][[1]], "cali_slp_ext_W1"=ext_cali_res_W1$cox_slope["cox_slope"][[1]],
      "cali_slp_estsd_ext_W0"=ext_cali_res_W0$cox_slope["cox_slope_se"][[1]], "cali_slp_estsd_ext_W1"=ext_cali_res_W1$cox_slope["cox_slope_se"][[1]],
      "cali_slp_rej_ext_W0" = 1 < ext_cali_res_W0$cox_slope["cox_slope_cilb"][[1]] | 1 > ext_cali_res_W0$cox_slope["cox_slope_ciub"][[1]],
      "cali_slp_rej_ext_W1" = 1 < ext_cali_res_W1$cox_slope["cox_slope_cilb"][[1]] | 1 > ext_cali_res_W1$cox_slope["cox_slope_ciub"][[1]],
      
      "AUC_byAvg_W0"=AUC_byAvg_rep[1], "AUC_byAvg_W1"=AUC_byAvg_rep[2],
      "AUC_estsd_byAvg_W0"=AUC_estsd_byAvg_rep[1], "AUC_estsd_byAvg_W1"=AUC_estsd_byAvg_rep[2],
      
      "EOR_byAvg_W0"=EOR_byAvg_rep[1], "EOR_byAvg_W1"=EOR_byAvg_rep[2],
      "EOR_estsd_byAvg_W0" = EOR_estsd_byAvg_rep[1], "EOR_estsd_byAvg_W1"=EOR_estsd_byAvg_rep[2],
      "EOR_rej_byAvg_W0" = 1 < EOR_byAvg_rep[1] - qnorm(0.975) * EOR_estsd_byAvg_rep[1] | 1 > EOR_byAvg_rep[1] + qnorm(0.975) * EOR_estsd_byAvg_rep[1],
      "EOR_rej_byAvg_W1" = 1 < EOR_byAvg_rep[2] - qnorm(0.975) * EOR_estsd_byAvg_rep[2] | 1 > EOR_byAvg_rep[2] + qnorm(0.975) * EOR_estsd_byAvg_rep[2],
      
      "cali_intc_byAvg_W0"=cali_intc_byAvg_rep[1], "cali_intc_byAvg_W1"=cali_intc_byAvg_rep[2],
      "cali_intc_estsd_byAvg_W0" = cali_intc_estsd_byAvg_rep[1], "cali_intc_estsd_byAvg_W1"=cali_intc_estsd_byAvg_rep[2],
      "cali_intc_rej_byAvg_W0" = 0 < cali_intc_byAvg_rep[1] - qnorm(0.975) * cali_intc_estsd_byAvg_rep[1] | 0 > cali_intc_byAvg_rep[1] + qnorm(0.975) * cali_intc_estsd_byAvg_rep[1],
      "cali_intc_rej_byAvg_W1" = 0 < cali_intc_byAvg_rep[2] - qnorm(0.975) * cali_intc_estsd_byAvg_rep[2] | 0 > cali_intc_byAvg_rep[2] + qnorm(0.975) * cali_intc_estsd_byAvg_rep[2],
      
      "cali_slp_byAvg_W0"=cali_slp_byAvg_rep[1], "cali_slp_byAvg_W1"=cali_slp_byAvg_rep[2],
      "cali_slp_estsd_byAvg_W0" = cali_slp_estsd_byAvg_rep[1], "cali_slp_estsd_byAvg_W1"=cali_slp_estsd_byAvg_rep[2],
      "cali_slp_rej_byAvg_W0" = 1 < cali_slp_byAvg_rep[1] - qnorm(0.975) * cali_slp_estsd_byAvg_rep[1] | 1 > cali_slp_byAvg_rep[1] + qnorm(0.975) * cali_slp_estsd_byAvg_rep[1],
      "cali_slp_rej_byAvg_W1" = 1 < cali_slp_byAvg_rep[2] - qnorm(0.975) * cali_slp_estsd_byAvg_rep[2] | 1 > cali_slp_byAvg_rep[2] + qnorm(0.975) * cali_slp_estsd_byAvg_rep[2],
      
      "AUC_byAgt_W0"=AUC_byAgt_rep[1], "AUC_byAgt_W1"=AUC_byAgt_rep[2],
      "AUC_estsd_byAgt_W0"=AUC_estsd_byAgt_rep[1], "AUC_estsd_byAgt_W1"=AUC_estsd_byAgt_rep[2],
      
      "EOR_byAgt_W0"=cali_res_byAgt_W0$EORatio["EORatio"][[1]], "EOR_byAgt_W1"=cali_res_byAgt_W1$EORatio["EORatio"][[1]],
      "EOR_estsd_byAgt_W0"=cali_res_byAgt_W0$EORatio["se_EORatio"][[1]], "EOR_estsd_byAgt_W1"=cali_res_byAgt_W1$EORatio["se_EORatio"][[1]],
      "EOR_rej_byAgt_W0"= 1 < cali_res_byAgt_W0$EORatio["EORatio_cilb"][[1]] | 1 > cali_res_byAgt_W0$EORatio["EORatio_ciub"][[1]],
      "EOR_rej_byAgt_W1"= 1 < cali_res_byAgt_W1$EORatio["EORatio_cilb"][[1]] | 1 > cali_res_byAgt_W1$EORatio["EORatio_ciub"][[1]],
      
      "cali_intc_byAgt_W0"=cali_res_byAgt_W0$cox_intercept["cox_intercept"][[1]], "cali_intc_byAgt_W1"=cali_res_byAgt_W1$cox_intercept["cox_intercept"][[1]],
      "cali_intc_estsd_byAgt_W0"=cali_res_byAgt_W0$cox_intercept["cox_intercept_se"][[1]], "cali_intc_estsd_byAgt_W1"=cali_res_byAgt_W1$cox_intercept["cox_intercept_se"][[1]],
      "cali_intc_rej_byAgt_W0" = 0 < cali_res_byAgt_W0$cox_intercept["cox_intercept_cilb"][[1]] | 0 > cali_res_byAgt_W0$cox_intercept["cox_intercept_ciub"][[1]],
      "cali_intc_rej_byAgt_W1" = 0 < cali_res_byAgt_W1$cox_intercept["cox_intercept_cilb"][[1]] | 0 > cali_res_byAgt_W1$cox_intercept["cox_intercept_ciub"][[1]],
      
      "cali_slp_byAgt_W0"=cali_res_byAgt_W0$cox_slope["cox_slope"][[1]], "cali_slp_byAgt_W1"=cali_res_byAgt_W1$cox_slope["cox_slope"][[1]],
      "cali_slp_estsd_byAgt_W0"=cali_res_byAgt_W0$cox_slope["cox_slope_se"][[1]], "cali_slp_estsd_byAgt_W1"=cali_res_byAgt_W1$cox_slope["cox_slope_se"][[1]],
      "cali_slp_rej_byAgt_W0" = 1 < cali_res_byAgt_W0$cox_slope["cox_slope_cilb"][[1]] | 1 > cali_res_byAgt_W0$cox_slope["cox_slope_ciub"][[1]],
      "cali_slp_rej_byAgt_W1" = 1 < cali_res_byAgt_W1$cox_slope["cox_slope_cilb"][[1]] | 1 > cali_res_byAgt_W1$cox_slope["cox_slope_ciub"][[1]])
  }
  
  
  out_AUC[i, c("W0_AUC_byAvg", "W1_AUC_byAvg", "W0_AUC_byAgt", "W1_AUC_byAgt", "W0_AUC_ext", "W1_AUC_ext", "W0_AUC_byAvg_estsd", "W1_AUC_byAvg_estsd", "W0_AUC_byAgt_estsd", "W1_AUC_byAgt_estsd", "W0_AUC_ext_estsd", "W1_AUC_ext_estsd")] = colMeans(res[, c("AUC_byAvg_W0", "AUC_byAvg_W1", "AUC_byAgt_W0", "AUC_byAgt_W1", "AUC_ext_W0", "AUC_ext_W1", "AUC_estsd_byAvg_W0", "AUC_estsd_byAvg_W1", "AUC_estsd_byAgt_W0", "AUC_estsd_byAgt_W1", "AUC_estsd_ext_W0", "AUC_estsd_ext_W1")])
  
  out_AUC[i, c("W0_AUC_byAvg_sd", "W1_AUC_byAvg_sd", "W0_AUC_byAgt_sd", "W1_AUC_byAgt_sd", "W0_AUC_ext_sd", "W1_AUC_ext_sd")] = apply(res[, c("AUC_byAvg_W0", "AUC_byAvg_W1", "AUC_byAgt_W0", "AUC_byAgt_W1", "AUC_ext_W0", "AUC_ext_W1")], MARGIN = 2, sd)
  
  out_EOR[i, c("W0_EOR_byAvg", "W1_EOR_byAvg", "W0_EOR_byAgt", "W1_EOR_byAgt", "W0_EOR_ext", "W1_EOR_ext", "W0_EOR_byAvg_estsd", "W1_EOR_byAvg_estsd", "W0_EOR_byAgt_estsd", "W1_EOR_byAgt_estsd", "W0_EOR_ext_estsd", "W1_EOR_ext_estsd", "W0_EOR_byAvg_rej_rate", "W1_EOR_byAvg_rej_rate", "W0_EOR_byAgt_rej_rate", "W1_EOR_byAgt_rej_rate", "W0_EOR_ext_rej_rate", "W1_EOR_ext_rej_rate")] = colMeans(res[, c("EOR_byAvg_W0", "EOR_byAvg_W1", "EOR_byAgt_W0", "EOR_byAgt_W1", "EOR_ext_W0", "EOR_ext_W1", "EOR_estsd_byAvg_W0", "EOR_estsd_byAvg_W1", "EOR_estsd_byAgt_W0", "EOR_estsd_byAgt_W1", "EOR_estsd_ext_W0", "EOR_estsd_ext_W1", "EOR_rej_byAvg_W0", "EOR_rej_byAvg_W1", "EOR_rej_byAgt_W0", "EOR_rej_byAgt_W1", "EOR_rej_ext_W0", "EOR_rej_ext_W1")])
  
  out_EOR[i, c("W0_EOR_byAvg_sd", "W1_EOR_byAvg_sd", "W0_EOR_byAgt_sd", "W1_EOR_byAgt_sd", "W0_EOR_ext_sd", "W1_EOR_ext_sd")] = apply(res[, c("EOR_byAvg_W0", "EOR_byAvg_W1", "EOR_byAgt_W0", "EOR_byAgt_W1", "EOR_ext_W0", "EOR_ext_W1")], MARGIN = 2, sd)
  
  out_cali_intc[i, c("W0_cali_intc_byAvg", "W1_cali_intc_byAvg", "W0_cali_intc_byAgt", "W1_cali_intc_byAgt", "W0_cali_intc_ext", "W1_cali_intc_ext", "W0_cali_intc_byAvg_estsd", "W1_cali_intc_byAvg_estsd", "W0_cali_intc_byAgt_estsd", "W1_cali_intc_byAgt_estsd", "W0_cali_intc_ext_estsd", "W1_cali_intc_ext_estsd", "W0_cali_intc_byAvg_rej_rate", "W1_cali_intc_byAvg_rej_rate", "W0_cali_intc_byAgt_rej_rate", "W1_cali_intc_byAgt_rej_rate", "W0_cali_intc_ext_rej_rate", "W1_cali_intc_ext_rej_rate")] = colMeans(res[, c("cali_intc_byAvg_W0", "cali_intc_byAvg_W1", "cali_intc_byAgt_W0", "cali_intc_byAgt_W1", "cali_intc_ext_W0", "cali_intc_ext_W1", "cali_intc_estsd_byAvg_W0", "cali_intc_estsd_byAvg_W1", "cali_intc_estsd_byAgt_W0", "cali_intc_estsd_byAgt_W1", "cali_intc_estsd_ext_W0", "cali_intc_estsd_ext_W1", "cali_intc_rej_byAvg_W0", "cali_intc_rej_byAvg_W1", "cali_intc_rej_byAgt_W0", "cali_intc_rej_byAgt_W1", "cali_intc_rej_ext_W0", "cali_intc_rej_ext_W1")])
  
  out_cali_intc[i, c("W0_cali_intc_byAvg_sd", "W1_cali_intc_byAvg_sd", "W0_cali_intc_byAgt_sd", "W1_cali_intc_byAgt_sd", "W0_cali_intc_ext_sd", "W1_cali_intc_ext_sd")] = apply(res[, c("cali_intc_byAvg_W0", "cali_intc_byAvg_W1", "cali_intc_byAgt_W0", "cali_intc_byAgt_W1", "cali_intc_ext_W0", "cali_intc_ext_W1")], MARGIN = 2, sd)
  
  out_cali_slp[i, c("W0_cali_slp_byAvg", "W1_cali_slp_byAvg", "W0_cali_slp_byAgt", "W1_cali_slp_byAgt", "W0_cali_slp_ext", "W1_cali_slp_ext", "W0_cali_slp_byAvg_estsd", "W1_cali_slp_byAvg_estsd", "W0_cali_slp_byAgt_estsd", "W1_cali_slp_byAgt_estsd", "W0_cali_slp_ext_estsd", "W1_cali_slp_ext_estsd", "W0_cali_slp_byAvg_rej_rate", "W1_cali_slp_byAvg_rej_rate", "W0_cali_slp_byAgt_rej_rate", "W1_cali_slp_byAgt_rej_rate", "W0_cali_slp_ext_rej_rate", "W1_cali_slp_ext_rej_rate")] = colMeans(res[, c("cali_slp_byAvg_W0", "cali_slp_byAvg_W1", "cali_slp_byAgt_W0", "cali_slp_byAgt_W1", "cali_slp_ext_W0", "cali_slp_ext_W1", "cali_slp_estsd_byAvg_W0", "cali_slp_estsd_byAvg_W1", "cali_slp_estsd_byAgt_W0", "cali_slp_estsd_byAgt_W1", "cali_slp_estsd_ext_W0", "cali_slp_estsd_ext_W1", "cali_slp_rej_byAvg_W0", "cali_slp_rej_byAvg_W1", "cali_slp_rej_byAgt_W0", "cali_slp_rej_byAgt_W1", "cali_slp_rej_ext_W0", "cali_slp_rej_ext_W1")])
  
  out_cali_slp[i, c("W0_cali_slp_byAvg_sd", "W1_cali_slp_byAvg_sd", "W0_cali_slp_byAgt_sd", "W1_cali_slp_byAgt_sd", "W0_cali_slp_ext_sd", "W1_cali_slp_ext_sd")] = apply(res[, c("cali_slp_byAvg_W0", "cali_slp_byAvg_W1", "cali_slp_byAgt_W0", "cali_slp_byAgt_W1", "cali_slp_ext_W0", "cali_slp_ext_W1")], MARGIN = 2, sd)
}
end.t = Sys.time()
cat(end.t - start.t)
stopCluster(myCluster)
out_AUC %>% write.csv("./No stratification/AUC.csv", row.names = FALSE)
out_EOR %>% write.csv("./No stratification/EOR.csv", row.names = FALSE)
out_cali_intc %>% write.csv("./No stratification/Cali_intercept.csv", row.names = FALSE)
out_cali_slp %>% write.csv("./No stratification/Cali_slope.csv", row.names = FALSE)
```

```{r}
est_se = NULL
par = NULL
for(i in 1:1000){
  if(i%%100 == 0) cat(i)
  x = rnorm(100)
  y_prob = exp(1+x)/(exp(1+x)+1)
  y = sapply(y_prob, function(x){
    rbinom(1, 1, x)
  })
  mod = glm(y~x, family = "binomial")
  res = summary(mod)
  est_se[i] = res$coefficients[2, 2]
  par[i] = coef(mod)[2]
}
mean(est_se)
sd(par)
```