---
title: "Diagnosis of calibration intercept stratified CV"
author: "Qi Wang"
date: "2023/7/29"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Diagnosis - why the Monte Carlo sample standard deviation of calibration intercept is so small
```{r}
# # sample size
# N = 5e4
# # X: continuous predictors
# mu_X = c(0,0,0)
# Sigma_X = matrix(c(1, 0.5, 0.1,
#                    0.5, 1, 0.3,
#                    0.1, 0.3, 1), nrow = 3, ncol = 3, byrow = TRUE)
# coef_X = c(0.3, 0.5, 0.7)
# # V: discrete predictors
# p_V = c(0.7, 0.4)
# coef_V = c(0.4, 0.6)
# 
# # W: racial and ethnic group
# ps_W = c(0.6, 0.9) # proportion of white
# coef_W = 0.8
# 
# # The probability of case
# ps_case = c(0.2, 0.05)
# 
# paras = expand.grid(Proportion_White = ps_W, Prob_Case = ps_case)
# NN = 1e5
# candi_as = seq(-5, -1, 0.01)
# as = NULL
# for(i in 1:nrow(paras)){
#   p_W = paras$Proportion_White[i]
#   p_case = paras$Prob_Case[i]
#   candi_prevals = NULL
#   for(candi_a in candi_as){
#     X = MASS::mvrnorm(n = NN, mu = mu_X, Sigma = Sigma_X)
#     V = sapply(p_V, function(p){rbinom(n = NN, size = 1, prob = p)})
#     W = rbinom(n = NN, size = 1, prob = p_W)
#     pos_prob = exp(candi_a + X %*% coef_X + V %*% coef_V + W * coef_W) / (1 + exp(candi_a + X %*% coef_X + V %*% coef_V + W * coef_W))
#     case = rbinom(NN, 1, pos_prob)
#     candi_prevals = c(candi_prevals, mean(case))
#   }
#   cat(min(abs(candi_prevals - p_case)), "\n")
#   as[i] = candi_as[which.min(abs(candi_prevals - p_case))]
#   cat(as[i], "\n")
# }
# paras$alpha = as
# 
# for(i in 1:nrow(paras)){
#   p_W = paras$Proportion_White[i]
#   p_case = paras$Prob_Case[i]
#   a = paras$alpha[i]
#   X = MASS::mvrnorm(n = N, mu = mu_X, Sigma = Sigma_X)
#   V = sapply(p_V, function(p){rbinom(n = N, size = 1, prob = p)})
#   W = rbinom(n = N, size = 1, prob = p_W)
#   pos_prob = exp(a + X %*% coef_X + V %*% coef_V + W * coef_W) / (1 + exp(a + X %*% coef_X + V %*% coef_V + W * coef_W))
#   case = rbinom(N, 1, pos_prob)
#   print(table(case, W))
# }
# 
# # Number of iteration
# n_iter = 500
# source("funcs_calibrationMetrics.R")
# library(caret)
# library(pROC)
# library(tidyverse)
# library(doParallel)
# library(foreach)
# library(parallel)
# paras = merge(paras, data.frame(num_folds = c(5,10)))
# 
# 
# myCluster <- makeCluster(detectCores()-1, type = "PSOCK")
# registerDoParallel(myCluster)
# p_W = paras$Proportion_White[i]
# p_case = paras$Prob_Case[i]
# a = paras$alpha[i]
# num_folds = paras$num_folds[i]
# res = foreach(iter=1:n_iter, .combine = 'rbind', .packages = c("caret", "pROC", "tidyverse")) %dopar%{
#   X = MASS::mvrnorm(n = N, mu = mu_X, Sigma = Sigma_X)
#   V = sapply(p_V, function(p){rbinom(n = N, size = 1, prob = p)})
#   W = rbinom(n = N, size = 1, prob = p_W)
#   pos_prob = exp(a + X %*% coef_X + V %*% coef_V + W * coef_W) / (1 + exp(a + X %*% coef_X + V %*% coef_V + W * coef_W))
#   case = rbinom(N, 1, pos_prob)
#   sim_data = data.frame(X=X, V=V, W=W, case=case)
#   
#   ext_X = MASS::mvrnorm(n = N, mu = mu_X, Sigma = Sigma_X)
#   ext_V = sapply(p_V, function(p){rbinom(n = N, size = 1, prob = p)})
#   ext_W = rbinom(n = N, size = 1, prob = p_W)
#   ext_pos_prob = exp(a + ext_X %*% coef_X + ext_V %*% coef_V + ext_W * coef_W) / (1 + exp(a + ext_X %*% coef_X + ext_V %*% coef_V + ext_W * coef_W))
#   ext_case = rbinom(N, 1, ext_pos_prob)
#   ext_data = data.frame(X=ext_X, V=ext_V, W=ext_W, case=ext_case)
#   
#   full_data_model = glm(case ~ ., data = sim_data, family = binomial())
#   ext_data$Y_pred = predict(full_data_model, ext_data, type = "response")
#   
#   ext_cali_res_W0 = ext_data %>% filter(W==0) %>% calibrationMetrics(risk_var = "Y_pred", weak_cali_ind = FALSE, correlated = FALSE)
#   ext_cali_res_W1 = ext_data %>% filter(W==1) %>% calibrationMetrics(risk_var = "Y_pred", weak_cali_ind = FALSE, correlated = FALSE)
#   
#   group = apply(sim_data[,c("W", "case")], 1, function(x){
#     if(x[1]==0 & x[2]==0){return(1)}
#     else if(x[1]==0 & x[2]==1){return(2)}
#     else if(x[1]==1 & x[2]==0){return(3)}
#     else {return(4)}
#   })
#   CVTrainFolds = createFolds(as.factor(group), k = num_folds, list = TRUE, returnTrain = TRUE)
#   
#   test_Y_true = NULL
#   test_Y_pred = NULL
#   test_W = NULL
#   cali_intc_byAvg_vec_folds = matrix(0, nrow = num_folds, ncol = length(p_W) + 1)
#   cali_intc_estsd_byAvg_vec_folds = matrix(0, nrow = num_folds, ncol = length(p_W) + 1)
#   for(cv_iter in 1:num_folds){
#     train_id = CVTrainFolds[[cv_iter]]
#     cv_train_data = sim_data[train_id, ]
#     cv_test_data = sim_data[-train_id, ]
#     test_Y_true = c(test_Y_true, cv_test_data$case)
#     test_W = c(test_W, cv_test_data$W)
#     cv_model = glm(case ~ ., data = cv_train_data, family = binomial())
#     cv_Y_ped = predict(cv_model, cv_test_data, type = "response")
#     test_Y_pred = c(test_Y_pred, cv_Y_ped)
#     cv_test_data$Y_pred = cv_Y_ped
#     
#     cv_cali_res_W0 = cv_test_data %>% filter(W==0) %>% calibrationMetrics(risk_var = "Y_pred", weak_cali_ind = FALSE, correlated = FALSE)
#     cv_cali_res_W1 = cv_test_data %>% filter(W==1) %>% calibrationMetrics(risk_var = "Y_pred", weak_cali_ind = FALSE, correlated = FALSE)
#     
#     cali_intc_byAvg_vec_folds[cv_iter, ] = c(cv_cali_res_W0$cox_intercept["cox_intercept"][[1]], cv_cali_res_W1$cox_intercept["cox_intercept"][[1]])
#     
#     cali_intc_estsd_byAvg_vec_folds[cv_iter, ] = c(cv_cali_res_W0$cox_intercept["cox_intercept_se"][[1]], cv_cali_res_W1$cox_intercept["cox_intercept_se"][[1]])
#   }
#   
#   cali_intc_byAvg_rep = colMeans(cali_intc_byAvg_vec_folds)
#    
#   cali_intc_estsd_byAvg_rep = colMeans(cali_intc_estsd_byAvg_vec_folds)/sqrt(num_folds)
#   
#   all_test_dt = data.frame(W=test_W, case=test_Y_true, Y_pred=test_Y_pred)
#   
#   cali_res_byAgt_W0 = all_test_dt %>% filter(W==0) %>% calibrationMetrics(risk_var = "Y_pred", weak_cali_ind = FALSE, correlated = FALSE)
#   cali_res_byAgt_W1 = all_test_dt %>% filter(W==1) %>% calibrationMetrics(risk_var = "Y_pred", weak_cali_ind = FALSE, correlated = FALSE)
#   
#   c("cali_intc_ext_W0"=ext_cali_res_W0$cox_intercept["cox_intercept"][[1]], "cali_intc_ext_W1"=ext_cali_res_W1$cox_intercept["cox_intercept"][[1]],
#     "cali_intc_estsd_ext_W0"=ext_cali_res_W0$cox_intercept["cox_intercept_se"][[1]], "cali_intc_estsd_ext_W1"=ext_cali_res_W1$cox_intercept["cox_intercept_se"][[1]],
#     "cali_intc_rej_ext_W0" = 0 < ext_cali_res_W0$cox_intercept["cox_intercept_cilb"][[1]] | 0 > ext_cali_res_W0$cox_intercept["cox_intercept_ciub"][[1]],
#     "cali_intc_rej_ext_W1" = 0 < ext_cali_res_W1$cox_intercept["cox_intercept_cilb"][[1]] | 0 > ext_cali_res_W1$cox_intercept["cox_intercept_ciub"][[1]],
#     
#     
#     "cali_intc_byAvg_W0"=cali_intc_byAvg_rep[1], "cali_intc_byAvg_W1"=cali_intc_byAvg_rep[2],
#     "cali_intc_estsd_byAvg_W0" = cali_intc_estsd_byAvg_rep[1], "cali_intc_estsd_byAvg_W1"=cali_intc_estsd_byAvg_rep[2],
#     "cali_intc_rej_byAvg_W0" = 0 < cali_intc_byAvg_rep[1] - qnorm(0.975) * cali_intc_estsd_byAvg_rep[1] | 0 > cali_intc_byAvg_rep[1] + qnorm(0.975) * cali_intc_estsd_byAvg_rep[1],
#     "cali_intc_rej_byAvg_W1" = 0 < cali_intc_byAvg_rep[2] - qnorm(0.975) * cali_intc_estsd_byAvg_rep[2] | 0 > cali_intc_byAvg_rep[2] + qnorm(0.975) * cali_intc_estsd_byAvg_rep[2],
#     
#     "cali_intc_byAgt_W0"=cali_res_byAgt_W0$cox_intercept["cox_intercept"][[1]], "cali_intc_byAgt_W1"=cali_res_byAgt_W1$cox_intercept["cox_intercept"][[1]],
#     "cali_intc_estsd_byAgt_W0"=cali_res_byAgt_W0$cox_intercept["cox_intercept_se"][[1]], "cali_intc_estsd_byAgt_W1"=cali_res_byAgt_W1$cox_intercept["cox_intercept_se"][[1]],
#     "cali_intc_rej_byAgt_W0" = 0 < cali_res_byAgt_W0$cox_intercept["cox_intercept_cilb"][[1]] | 0 > cali_res_byAgt_W0$cox_intercept["cox_intercept_ciub"][[1]],
#     "cali_intc_rej_byAgt_W1" = 0 < cali_res_byAgt_W1$cox_intercept["cox_intercept_cilb"][[1]] | 0 > cali_res_byAgt_W1$cox_intercept["cox_intercept_ciub"][[1]])
# }
# 
# 
# 
# stopCluster(myCluster)
# hist(res[, "cali_intc_ext_W0"])
# hist(res[, "cali_intc_byAvg_W0"])
# hist(res[, "cali_intc_byAgt_W0"])
# 
# plot(res[, "cali_intc_ext_W0"], res[, "cali_intc_byAvg_W0"])
# plot(res[, "cali_intc_byAgt_W0"], res[, "cali_intc_byAvg_W0"])
# 
# # calibration intercept:
# # mimic average method when doing external validation: using model fit based on folds 1-4 to predict the 5th fold of external dataset
# # compare the monte carlo and formula based se within each fold for average method
```


## Mimicing average method when doing external validation and comparing the monte carlo and formula based se within each fold for average method
```{r}
# sample size
N = 5e4
# X: continuous predictors
mu_X = c(0,0,0)
Sigma_X = matrix(c(1, 0.5, 0.1,
                   0.5, 1, 0.3,
                   0.1, 0.3, 1), nrow = 3, ncol = 3, byrow = TRUE)
coef_X = c(0.3, 0.5, 0.7)
# V: discrete predictors
p_V = c(0.7, 0.4)
coef_V = c(0.4, 0.6)

# W: racial and ethnic group
ps_W = c(0.6, 0.9) # proportion of white
coef_W = 0.8

# The probability of case
ps_case = c(0.2, 0.05)

paras = expand.grid(Proportion_White = ps_W, Prob_Case = ps_case)
NN = 1e5
candi_as = seq(-5, -1, 0.01)
as = NULL
for(i in 1:nrow(paras)){
  p_W = paras$Proportion_White[i]
  p_case = paras$Prob_Case[i]
  candi_prevals = NULL
  for(candi_a in candi_as){
    X = MASS::mvrnorm(n = NN, mu = mu_X, Sigma = Sigma_X)
    V = sapply(p_V, function(p){rbinom(n = NN, size = 1, prob = p)})
    W = rbinom(n = NN, size = 1, prob = p_W)
    pos_prob = exp(candi_a + X %*% coef_X + V %*% coef_V + W * coef_W) / (1 + exp(candi_a + X %*% coef_X + V %*% coef_V + W * coef_W))
    case = rbinom(NN, 1, pos_prob)
    candi_prevals = c(candi_prevals, mean(case))
  }
  cat(min(abs(candi_prevals - p_case)), "\n")
  as[i] = candi_as[which.min(abs(candi_prevals - p_case))]
  cat(as[i], "\n")
}
paras$alpha = as

for(i in 1:nrow(paras)){
  p_W = paras$Proportion_White[i]
  p_case = paras$Prob_Case[i]
  a = paras$alpha[i]
  X = MASS::mvrnorm(n = N, mu = mu_X, Sigma = Sigma_X)
  V = sapply(p_V, function(p){rbinom(n = N, size = 1, prob = p)})
  W = rbinom(n = N, size = 1, prob = p_W)
  pos_prob = exp(a + X %*% coef_X + V %*% coef_V + W * coef_W) / (1 + exp(a + X %*% coef_X + V %*% coef_V + W * coef_W))
  case = rbinom(N, 1, pos_prob)
  print(table(case, W))
}

# Number of iteration
n_iter = 500
source("funcs_calibrationMetrics.R")
library(caret)
library(pROC)
library(tidyverse)
library(doParallel)
library(foreach)
library(parallel)
paras = merge(paras, data.frame(num_folds = c(2,10)))

i=4
myCluster <- makeCluster(detectCores()-1, type = "PSOCK")
registerDoParallel(myCluster)
p_W = paras$Proportion_White[i]
p_case = paras$Prob_Case[i]
a = paras$alpha[i]
num_folds = paras$num_folds[i]
res = foreach(iter=1:n_iter, .combine = 'rbind', .packages = c("caret", "pROC", "tidyverse")) %dopar%{
  X = MASS::mvrnorm(n = N, mu = mu_X, Sigma = Sigma_X)
  V = sapply(p_V, function(p){rbinom(n = N, size = 1, prob = p)})
  W = rbinom(n = N, size = 1, prob = p_W)
  pos_prob = exp(a + X %*% coef_X + V %*% coef_V + W * coef_W) / (1 + exp(a + X %*% coef_X + V %*% coef_V + W * coef_W))
  case = rbinom(N, 1, pos_prob)
  sim_data = data.frame(X=X, V=V, W=W, case=case)

  ext_X = MASS::mvrnorm(n = N, mu = mu_X, Sigma = Sigma_X)
  ext_V = sapply(p_V, function(p){rbinom(n = N, size = 1, prob = p)})
  ext_W = rbinom(n = N, size = 1, prob = p_W)
  ext_pos_prob = exp(a + ext_X %*% coef_X + ext_V %*% coef_V + ext_W * coef_W) / (1 + exp(a + ext_X %*% coef_X + ext_V %*% coef_V + ext_W * coef_W))
  ext_case = rbinom(N, 1, ext_pos_prob)
  ext_data = data.frame(X=ext_X, V=ext_V, W=ext_W, case=ext_case)

  group = apply(sim_data[,c("W", "case")], 1, function(x){
    if(x[1]==0 & x[2]==0){return(1)}
    else if(x[1]==0 & x[2]==1){return(2)}
    else if(x[1]==1 & x[2]==0){return(3)}
    else {return(4)}
  })
  CVTrainFolds = createFolds(as.factor(group), k = num_folds, list = TRUE, returnTrain = TRUE)

  ext_group = apply(ext_data[,c("W", "case")], 1, function(x){
    if(x[1]==0 & x[2]==0){return(1)}
    else if(x[1]==0 & x[2]==1){return(2)}
    else if(x[1]==1 & x[2]==0){return(3)}
    else {return(4)}
  })
  ext_CVTrainFolds = createFolds(as.factor(ext_group), k = num_folds, list = TRUE, returnTrain = TRUE)

  test_Y_true = NULL
  test_Y_pred = NULL
  test_W = NULL
  cali_intc_byAvg_vec_folds = matrix(0, nrow = num_folds, ncol = length(p_W) + 1)
  cali_intc_estsd_byAvg_vec_folds = matrix(0, nrow = num_folds, ncol = length(p_W) + 1)

  cali_intc_extAvg_vec_folds = matrix(0, nrow = num_folds, ncol = length(p_W) + 1)
  cali_intc_estsd_extAvg_vec_folds = matrix(0, nrow = num_folds, ncol = length(p_W) + 1)
  for(cv_iter in 1:num_folds){
    train_id = CVTrainFolds[[cv_iter]]
    cv_train_data = sim_data[train_id, ]
    cv_test_data = sim_data[-train_id, ]
    test_Y_true = c(test_Y_true, cv_test_data$case)
    test_W = c(test_W, cv_test_data$W)
    cv_model = glm(case ~ ., data = cv_train_data, family = binomial())
    cv_Y_ped = predict(cv_model, cv_test_data, type = "response")
    test_Y_pred = c(test_Y_pred, cv_Y_ped)
    cv_test_data$Y_pred = cv_Y_ped

    cv_test_ext_data = ext_data[-ext_CVTrainFolds[[cv_iter]], ]
    cv_ext_Y_ped = predict(cv_model, cv_test_ext_data, type = "response")
    cv_test_ext_data$Y_pred = cv_ext_Y_ped

    cv_cali_res_W0 = cv_test_data %>% filter(W==0) %>% calibrationMetrics(risk_var = "Y_pred", weak_cali_ind = FALSE, correlated = FALSE)
    cv_cali_res_W1 = cv_test_data %>% filter(W==1) %>% calibrationMetrics(risk_var = "Y_pred", weak_cali_ind = FALSE, correlated = FALSE)

    cv_cali_ext_res_W0 = cv_test_ext_data %>% filter(W==0) %>% calibrationMetrics(risk_var = "Y_pred", weak_cali_ind = FALSE, correlated = FALSE)
    cv_cali_ext_res_W1 = cv_test_ext_data %>% filter(W==1) %>% calibrationMetrics(risk_var = "Y_pred", weak_cali_ind = FALSE, correlated = FALSE)

    cali_intc_byAvg_vec_folds[cv_iter, ] = c(cv_cali_res_W0$cox_intercept["cox_intercept"][[1]], cv_cali_res_W1$cox_intercept["cox_intercept"][[1]])

    cali_intc_extAvg_vec_folds[cv_iter, ] = c(cv_cali_ext_res_W0$cox_intercept["cox_intercept"][[1]], cv_cali_ext_res_W1$cox_intercept["cox_intercept"][[1]])

    cali_intc_estsd_byAvg_vec_folds[cv_iter, ] = c(cv_cali_res_W0$cox_intercept["cox_intercept_se"][[1]], cv_cali_res_W1$cox_intercept["cox_intercept_se"][[1]])

    cali_intc_estsd_extAvg_vec_folds[cv_iter, ] = c(cv_cali_ext_res_W0$cox_intercept["cox_intercept_se"][[1]], cv_cali_ext_res_W0$cox_intercept["cox_intercept_se"][[1]])

    if(cv_iter == 1){
      cali_intc_byAvg_1fold_W0 = cv_cali_res_W0$cox_intercept["cox_intercept"][[1]]
      cali_intc_byAvg_1fold_W1 = cv_cali_res_W1$cox_intercept["cox_intercept"][[1]]
      cali_intc_estsd_byAvg_1fold_W0 = cv_cali_res_W0$cox_intercept["cox_intercept_se"][[1]]
      cali_intc_estsd_byAvg_1fold_W1 = cv_cali_res_W1$cox_intercept["cox_intercept_se"][[1]]
      cali_intc_rej_byAvg_1fold_W0 = cali_intc_byAvg_1fold_W0 + cali_intc_estsd_byAvg_1fold_W0 * qnorm(0.975) < 0 & cali_intc_byAvg_1fold_W0 - cali_intc_estsd_byAvg_1fold_W0 * qnorm(0.975) > 0
      cali_intc_rej_byAvg_1fold_W1 = cali_intc_byAvg_1fold_W1 + cali_intc_estsd_byAvg_1fold_W1 * qnorm(0.975) < 0 & cali_intc_byAvg_1fold_W1 - cali_intc_estsd_byAvg_1fold_W1 * qnorm(0.975) > 0
      

      cali_intc_extAvg_1fold_W0 = cv_cali_ext_res_W0$cox_intercept["cox_intercept"][[1]]
      cali_intc_extAvg_1fold_W1 = cv_cali_ext_res_W1$cox_intercept["cox_intercept"][[1]]
      cali_intc_estsd_extAvg_1fold_W0 = cv_cali_ext_res_W0$cox_intercept["cox_intercept_se"][[1]]
      cali_intc_estsd_extAvg_1fold_W1 = cv_cali_ext_res_W1$cox_intercept["cox_intercept_se"][[1]]
      cali_intc_rej_extAvg_1fold_W0 = cali_intc_extAvg_1fold_W0 + cali_intc_estsd_extAvg_1fold_W0 * qnorm(0.975) < 0 & cali_intc_extAvg_1fold_W0 - cali_intc_estsd_extAvg_1fold_W0 * qnorm(0.975) > 0
      cali_intc_rej_extAvg_1fold_W1 = cali_intc_extAvg_1fold_W1 + cali_intc_estsd_extAvg_1fold_W1 * qnorm(0.975) < 0 & cali_intc_extAvg_1fold_W1 - cali_intc_estsd_extAvg_1fold_W1 * qnorm(0.975) > 0
    }
    
    else{
      cali_intc_byAvg_2fold_W0 = cv_cali_res_W0$cox_intercept["cox_intercept"][[1]]
      cali_intc_byAvg_2fold_W1 = cv_cali_res_W1$cox_intercept["cox_intercept"][[1]]
      cali_intc_estsd_byAvg_2fold_W0 = cv_cali_res_W0$cox_intercept["cox_intercept_se"][[1]]
      cali_intc_estsd_byAvg_2fold_W1 = cv_cali_res_W1$cox_intercept["cox_intercept_se"][[1]]
      cali_intc_rej_byAvg_2fold_W0 = cali_intc_byAvg_2fold_W0 + cali_intc_estsd_byAvg_2fold_W0 * qnorm(0.975) < 0 & cali_intc_byAvg_2fold_W0 - cali_intc_estsd_byAvg_2fold_W0 * qnorm(0.975) > 0
      cali_intc_rej_byAvg_2fold_W1 = cali_intc_byAvg_2fold_W1 + cali_intc_estsd_byAvg_2fold_W1 * qnorm(0.975) < 0 & cali_intc_byAvg_2fold_W1 - cali_intc_estsd_byAvg_2fold_W1 * qnorm(0.975) > 0
      

      cali_intc_extAvg_2fold_W0 = cv_cali_ext_res_W0$cox_intercept["cox_intercept"][[1]]
      cali_intc_extAvg_2fold_W1 = cv_cali_ext_res_W1$cox_intercept["cox_intercept"][[1]]
      cali_intc_estsd_extAvg_2fold_W0 = cv_cali_ext_res_W0$cox_intercept["cox_intercept_se"][[1]]
      cali_intc_estsd_extAvg_2fold_W1 = cv_cali_ext_res_W1$cox_intercept["cox_intercept_se"][[1]]
      cali_intc_rej_extAvg_2fold_W0 = cali_intc_extAvg_2fold_W0 + cali_intc_estsd_extAvg_2fold_W0 * qnorm(0.975) < 0 | cali_intc_extAvg_2fold_W0 - cali_intc_estsd_extAvg_2fold_W0 * qnorm(0.975) > 0
      cali_intc_rej_extAvg_2fold_W1 = cali_intc_extAvg_2fold_W1 + cali_intc_estsd_extAvg_2fold_W1 * qnorm(0.975) < 0 | cali_intc_extAvg_2fold_W1 - cali_intc_estsd_extAvg_2fold_W1 * qnorm(0.975) > 0
    }
  }

  cali_intc_byAvg_rep = colMeans(cali_intc_byAvg_vec_folds)
  cali_intc_estsd_byAvg_rep = colMeans(cali_intc_estsd_byAvg_vec_folds)/sqrt(num_folds)

  cali_intc_extAvg_rep = colMeans(cali_intc_extAvg_vec_folds)
  cali_intc_estsd_extAvg_rep = colMeans(cali_intc_estsd_extAvg_vec_folds)/sqrt(num_folds)

  all_test_dt = data.frame(W=test_W, case=test_Y_true, Y_pred=test_Y_pred)

  cali_res_byAgt_W0 = all_test_dt %>% filter(W==0) %>% calibrationMetrics(risk_var = "Y_pred", weak_cali_ind = FALSE, correlated = FALSE)
  cali_res_byAgt_W1 = all_test_dt %>% filter(W==1) %>% calibrationMetrics(risk_var = "Y_pred", weak_cali_ind = FALSE, correlated = FALSE)

  c("cali_intc_extAvg_W0"=cali_intc_extAvg_rep[1], "cali_intc_extAvg_W1"=cali_intc_extAvg_rep[2],
    "cali_intc_estsd_extAvg_W0"=cali_intc_estsd_extAvg_rep[1], "cali_intc_estsd_extAvg_W1"=cali_intc_estsd_extAvg_rep[2],

    "cali_intc_byAvg_W0"=cali_intc_byAvg_rep[1], "cali_intc_byAvg_W1"=cali_intc_byAvg_rep[2],
    "cali_intc_estsd_byAvg_W0" = cali_intc_estsd_byAvg_rep[1], "cali_intc_estsd_byAvg_W1"=cali_intc_estsd_byAvg_rep[2],
    "cali_intc_rej_byAvg_W0" = cali_intc_byAvg_rep[1] + cali_intc_estsd_byAvg_rep[1] * qnorm(0.975) < 0 | cali_intc_byAvg_rep[1] - cali_intc_estsd_byAvg_rep[1] * qnorm(0.975) > 0,
    "cali_intc_rej_byAvg_W1" = cali_intc_byAvg_rep[2] + cali_intc_estsd_byAvg_rep[2] * qnorm(0.975) < 0 | cali_intc_byAvg_rep[2] - cali_intc_estsd_byAvg_rep[2] * qnorm(0.975) > 0,

    "cali_intc_byAgt_W0"=cali_res_byAgt_W0$cox_intercept["cox_intercept"][[1]], "cali_intc_byAgt_W1"=cali_res_byAgt_W1$cox_intercept["cox_intercept"][[1]],
    "cali_intc_estsd_byAgt_W0"=cali_res_byAgt_W0$cox_intercept["cox_intercept_se"][[1]], "cali_intc_estsd_byAgt_W1"=cali_res_byAgt_W1$cox_intercept["cox_intercept_se"][[1]],

    "cali_intc_byAvg_1fold_W0" = cali_intc_byAvg_1fold_W0,
    "cali_intc_byAvg_1fold_W1" = cali_intc_byAvg_1fold_W1,
    "cali_intc_estsd_byAvg_1fold_W0" = cali_intc_estsd_byAvg_1fold_W0,
    "cali_intc_estsd_byAvg_1fold_W1" = cali_intc_estsd_byAvg_1fold_W1,
    "cali_intc_rej_byAvg_1fold_W0" = cali_intc_rej_byAvg_1fold_W0,
    "cali_intc_rej_byAvg_1fold_W1" = cali_intc_rej_byAvg_1fold_W1,

    "cali_intc_extAvg_1fold_W0"=cali_intc_extAvg_1fold_W0,
    "cali_intc_extAvg_1fold_W1"=cali_intc_extAvg_1fold_W1,
    "cali_intc_estsd_extAvg_1fold_W0"=cali_intc_estsd_extAvg_1fold_W0,
    "cali_intc_estsd_extAvg_1fold_W1"=cali_intc_estsd_extAvg_1fold_W1,
    "cali_intc_rej_extAvg_1fold_W0" = cali_intc_rej_extAvg_1fold_W0,
    "cali_intc_rej_extAvg_1fold_W1" = cali_intc_rej_extAvg_1fold_W1,
    
    "cali_intc_byAvg_2fold_W0" = cali_intc_byAvg_2fold_W0,
    "cali_intc_byAvg_2fold_W1" = cali_intc_byAvg_2fold_W1,
    "cali_intc_estsd_byAvg_2fold_W0" = cali_intc_estsd_byAvg_2fold_W0,
    "cali_intc_estsd_byAvg_2fold_W1" = cali_intc_estsd_byAvg_2fold_W1,
    "cali_intc_rej_byAvg_2fold_W0" = cali_intc_rej_byAvg_2fold_W0,
    "cali_intc_rej_byAvg_2fold_W1" = cali_intc_rej_byAvg_2fold_W1,

    "cali_intc_extAvg_2fold_W0"=cali_intc_extAvg_2fold_W0,
    "cali_intc_extAvg_2fold_W1"=cali_intc_extAvg_2fold_W1,
    "cali_intc_estsd_extAvg_2fold_W0"=cali_intc_estsd_extAvg_2fold_W0,
    "cali_intc_estsd_extAvg_2fold_W1"=cali_intc_estsd_extAvg_2fold_W1,
    "cali_intc_rej_extAvg_2fold_W0" = cali_intc_rej_extAvg_2fold_W0,
    "cali_intc_rej_extAvg_2fold_W1" = cali_intc_rej_extAvg_2fold_W1)
}

stopCluster(myCluster)

# res %>% write.csv("res_0918.csv", row.names = FALSE)
# res = readr::read_csv("res_0918.csv")
# W0_cali_intc_ext_estsd = 0.0924
# W0_cali_intc_ext_sd = 0.1380
res %>% write.csv("diagnosis_stratified_2folds.csv")
res = readr::read_csv("diagnosis_stratified_2folds.csv")
mean(res$cali_intc_estsd_extAvg_W0)
sd(res$cali_intc_extAvg_W0)

# Formula-based SD by average method
mean(res$cali_intc_estsd_byAvg_W0)
# MC-based SD by average method
sd(res$cali_intc_byAvg_W0) ## 100 times smaller than formula-based
mean(res$cali_intc_estsd_byAvg_W0)/sd(res$cali_intc_byAvg_W0)

# Formula-based SD based on only 1 fold
mean(res$cali_intc_estsd_byAvg_1fold_W0)
# MC-based SD based on only 1 fold
sd(res$cali_intc_byAvg_1fold_W0)
mean(res$cali_intc_estsd_byAvg_1fold_W0)/sd(res$cali_intc_byAvg_1fold_W0)

# Formula-based SD by aggregate method
mean(res$cali_intc_estsd_byAgt_W0)
# MC-based SD by aggregate method
sd(res$cali_intc_byAgt_W0)  ## 100 times smaller than formula-based
mean(res$cali_intc_estsd_byAgt_W0)/sd(res$cali_intc_byAgt_W0)

mean(res$cali_intc_estsd_extAvg_1fold_W0)
sd(res$cali_intc_extAvg_1fold_W0)

mean(res$cali_intc_rej_byAvg_1fold_W0)
mean(res$cali_intc_rej_byAvg_2fold_W0)

cor(res$cali_intc_byAvg_1fold_W0, res$cali_intc_byAvg_2fold_W0)
cov(res$cali_intc_byAvg_1fold_W0, res$cali_intc_byAvg_2fold_W0)
plot(res$cali_intc_byAvg_1fold_W0, res$cali_intc_byAvg_2fold_W0)
```