---
title: "CV Average VS Aggregate"
author: "Qi Wang"
date: "2023/7/29"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# glm
```{r}
# sample size
N = 15000
# X: continuous predictors
mu_X = c(0,0,0)
Sigma_X = matrix(c(1, 0.5, 0.1,
                   0.5, 1, 0.3,
                   0.1, 0.3, 1), nrow = 3, ncol = 3, byrow = TRUE)
coef_X = c(0.3, 0.5, 0.7)
# V: discrete predictors
p_V = c(0.7, 0.4)
coef_V = c(0.4, 0.6)

# W: racial and ethnic group
ps_W = c(0.6, 0.9) # proportion of white
coef_W = 0.8

# The probability of case
ps_case = c(0.2, 0.05)

paras = expand.grid(Proportion_White = ps_W, Prob_Case = ps_case)
NN = 1e5
candi_as = seq(-5, -1, 0.01)
as = NULL
for(i in 1:nrow(paras)){
  p_W = paras$Proportion_White[i]
  p_case = paras$Prob_Case[i]
  candi_prevals = NULL
  for(candi_a in candi_as){
    X = MASS::mvrnorm(n = NN, mu = mu_X, Sigma = Sigma_X)
    V = sapply(p_V, function(p){rbinom(n = NN, size = 1, prob = p)})
    W = rbinom(n = NN, size = 1, prob = p_W)
    pos_prob = exp(candi_a + X %*% coef_X + V %*% coef_V + W * coef_W) / (1 + exp(candi_a + X %*% coef_X + V %*% coef_V + W * coef_W))
    case = rbinom(NN, 1, pos_prob)
    candi_prevals = c(candi_prevals, mean(case))
  }
  cat(min(abs(candi_prevals - p_case)), "\n")
  as[i] = candi_as[which.min(abs(candi_prevals - p_case))]
  cat(as[i], "\n")
}
paras$alpha = as

for(i in 1:nrow(paras)){
  p_W = paras$Proportion_White[i]
  p_case = paras$Prob_Case[i]
  a = paras$alpha[i]
  X = MASS::mvrnorm(n = N, mu = mu_X, Sigma = Sigma_X)
  V = sapply(p_V, function(p){rbinom(n = N, size = 1, prob = p)})
  W = rbinom(n = N, size = 1, prob = p_W)
  pos_prob = exp(a + X %*% coef_X + V %*% coef_V + W * coef_W) / (1 + exp(a + X %*% coef_X + V %*% coef_V + W * coef_W))
  case = rbinom(N, 1, pos_prob)
  print(table(case, W))
}

# Number of iteration
n_iter = 500
source("funcs_calibrationMetrics.R")
library(caret)
library(pROC)
library(tidyverse)
library(doParallel)
library(foreach)
library(parallel)
paras = merge(paras, data.frame(num_folds = 20))


i=1
myCluster <- makeCluster(detectCores()-1, type = "PSOCK")
registerDoParallel(myCluster)
p_W = paras$Proportion_White[i]
p_case = paras$Prob_Case[i]
a = paras$alpha[i]
num_folds = paras$num_folds[i]
res = foreach(iter=1:n_iter, .combine = 'rbind', .packages = c("caret", "pROC", "tidyverse")) %dopar%{
  X = MASS::mvrnorm(n = N, mu = mu_X, Sigma = Sigma_X)
  V = sapply(p_V, function(p){rbinom(n = N, size = 1, prob = p)})
  W = rbinom(n = N, size = 1, prob = p_W)
  pos_prob = exp(a + X %*% coef_X + V %*% coef_V + W * coef_W) / (1 + exp(a + X %*% coef_X + V %*% coef_V + W * coef_W))
  case = rbinom(N, 1, pos_prob)
  sim_data = data.frame(X=X, V=V, W=W, case=case)

  ext_X = MASS::mvrnorm(n = N, mu = mu_X, Sigma = Sigma_X)
  ext_V = sapply(p_V, function(p){rbinom(n = N, size = 1, prob = p)})
  ext_W = rbinom(n = N, size = 1, prob = p_W)
  ext_pos_prob = exp(a + ext_X %*% coef_X + ext_V %*% coef_V + ext_W * coef_W) / (1 + exp(a + ext_X %*% coef_X + ext_V %*% coef_V + ext_W * coef_W))
  ext_case = rbinom(N, 1, ext_pos_prob)
  ext_data = data.frame(X=ext_X, V=ext_V, W=ext_W, case=ext_case)
  
  folds = cut(seq(1, N), breaks=num_folds, labels=FALSE)
  folds = folds[sample(1:N, size = N, replace = FALSE)]
  
  ext_folds = cut(seq(1, N), breaks=num_folds, labels=FALSE)
  ext_folds = ext_folds[sample(1:N, size = N, replace = FALSE)]

  test_Y_true = NULL
  test_Y_pred = NULL
  test_W = NULL
  cali_intc_byAvg_vec_folds = matrix(0, nrow = num_folds, ncol = length(p_W) + 1)
  cali_intc_estsd_byAvg_vec_folds = matrix(0, nrow = num_folds, ncol = length(p_W) + 1)

  cali_intc_extAvg_vec_folds = matrix(0, nrow = num_folds, ncol = length(p_W) + 1)
  cali_intc_estsd_extAvg_vec_folds = matrix(0, nrow = num_folds, ncol = length(p_W) + 1)
  
  cali_slp_byAvg_vec_folds = matrix(0, nrow = num_folds, ncol = length(p_W) + 1)
  cali_slp_estsd_byAvg_vec_folds = matrix(0, nrow = num_folds, ncol = length(p_W) + 1)

  cali_slp_extAvg_vec_folds = matrix(0, nrow = num_folds, ncol = length(p_W) + 1)
  cali_slp_estsd_extAvg_vec_folds = matrix(0, nrow = num_folds, ncol = length(p_W) + 1)
  
  
  
  cali_intc_byAvg_allfold_W0 = matrix(0, nrow = num_folds, ncol = 1)
  cali_intc_byAvg_allfold_W1 = matrix(0, nrow = num_folds, ncol = 1)
  cali_intc_estsd_byAvg_allfold_W0 = matrix(0, nrow = num_folds, ncol = 1)
  cali_intc_estsd_byAvg_allfold_W1 = matrix(0, nrow = num_folds, ncol = 1)
  cali_intc_rej_byAvg_allfold_W0 = matrix(0, nrow = num_folds, ncol = 1)
  cali_intc_rej_byAvg_allfold_W1 = matrix(0, nrow = num_folds, ncol = 1)

  cali_intc_extAvg_allfold_W0 = matrix(0, nrow = num_folds, ncol = 1)
  cali_intc_extAvg_allfold_W1 = matrix(0, nrow = num_folds, ncol = 1)
  cali_intc_estsd_extAvg_allfold_W0 = matrix(0, nrow = num_folds, ncol = 1)
  cali_intc_estsd_extAvg_allfold_W1 = matrix(0, nrow = num_folds, ncol = 1)
  cali_intc_rej_extAvg_allfold_W0 = matrix(0, nrow = num_folds, ncol = 1)
  cali_intc_rej_extAvg_allfold_W1 = matrix(0, nrow = num_folds, ncol = 1)
  
  cali_slp_byAvg_allfold_W0 = matrix(0, nrow = num_folds, ncol = 1)
  cali_slp_byAvg_allfold_W1 = matrix(0, nrow = num_folds, ncol = 1)
  cali_slp_estsd_byAvg_allfold_W0 = matrix(0, nrow = num_folds, ncol = 1)
  cali_slp_estsd_byAvg_allfold_W1 = matrix(0, nrow = num_folds, ncol = 1)
  cali_slp_rej_byAvg_allfold_W0 = matrix(0, nrow = num_folds, ncol = 1)
  cali_slp_rej_byAvg_allfold_W1 = matrix(0, nrow = num_folds, ncol = 1)
  

  cali_slp_extAvg_allfold_W0 = matrix(0, nrow = num_folds, ncol = 1)
  cali_slp_extAvg_allfold_W1 = matrix(0, nrow = num_folds, ncol = 1)
  cali_slp_estsd_extAvg_allfold_W0 = matrix(0, nrow = num_folds, ncol = 1)
  cali_slp_estsd_extAvg_allfold_W1 = matrix(0, nrow = num_folds, ncol = 1)
  cali_slp_rej_extAvg_allfold_W0 = matrix(0, nrow = num_folds, ncol = 1)
  cali_slp_rej_extAvg_allfold_W1 = matrix(0, nrow = num_folds, ncol = 1)
  for(cv_iter in 1:num_folds){
    test_id = which(folds == cv_iter)
    cv_train_data = sim_data[-test_id, ]
    cv_test_data = sim_data[test_id, ]
    test_Y_true = c(test_Y_true, cv_test_data$case)
    test_W = c(test_W, cv_test_data$W)
    cv_model = glm(case ~ ., data = cv_train_data, family = binomial())
    cv_Y_ped = predict(cv_model, cv_test_data, type = "response")
    test_Y_pred = c(test_Y_pred, cv_Y_ped)
    cv_test_data$Y_pred = cv_Y_ped
    
    cv_test_ext_data = ext_data[which(ext_folds == cv_iter), ]
    cv_ext_Y_ped = predict(cv_model, cv_test_ext_data, type = "response")
    cv_test_ext_data$Y_pred = cv_ext_Y_ped

    cv_cali_res_W0 = cv_test_data %>% filter(W==0) %>% calibrationMetrics(risk_var = "Y_pred", weak_cali_ind = FALSE, correlated = FALSE)
    cv_cali_res_W1 = cv_test_data %>% filter(W==1) %>% calibrationMetrics(risk_var = "Y_pred", weak_cali_ind = FALSE, correlated = FALSE)

    cv_cali_ext_res_W0 = cv_test_ext_data %>% filter(W==0) %>% calibrationMetrics(risk_var = "Y_pred", weak_cali_ind = FALSE, correlated = FALSE)
    cv_cali_ext_res_W1 = cv_test_ext_data %>% filter(W==1) %>% calibrationMetrics(risk_var = "Y_pred", weak_cali_ind = FALSE, correlated = FALSE)

    cali_intc_byAvg_vec_folds[cv_iter, ] = c(cv_cali_res_W0$cox_intercept["cox_intercept"][[1]], cv_cali_res_W1$cox_intercept["cox_intercept"][[1]])

    cali_intc_extAvg_vec_folds[cv_iter, ] = c(cv_cali_ext_res_W0$cox_intercept["cox_intercept"][[1]], cv_cali_ext_res_W1$cox_intercept["cox_intercept"][[1]])

    cali_intc_estsd_byAvg_vec_folds[cv_iter, ] = c(cv_cali_res_W0$cox_intercept["cox_intercept_se"][[1]], cv_cali_res_W1$cox_intercept["cox_intercept_se"][[1]])

    cali_intc_estsd_extAvg_vec_folds[cv_iter, ] = c(cv_cali_ext_res_W0$cox_intercept["cox_intercept_se"][[1]], cv_cali_ext_res_W0$cox_intercept["cox_intercept_se"][[1]])
    
    cali_slp_byAvg_vec_folds[cv_iter, ] = c(cv_cali_res_W0$cox_slope["cox_slope"][[1]], cv_cali_res_W1$cox_slope["cox_slope"][[1]])

    cali_slp_extAvg_vec_folds[cv_iter, ] = c(cv_cali_ext_res_W0$cox_slope["cox_slope"][[1]], cv_cali_ext_res_W1$cox_slope["cox_slope"][[1]])

    cali_slp_estsd_byAvg_vec_folds[cv_iter, ] = c(cv_cali_res_W0$cox_slope["cox_slope_se"][[1]], cv_cali_res_W1$cox_slope["cox_slope_se"][[1]])

    cali_slp_estsd_extAvg_vec_folds[cv_iter, ] = c(cv_cali_ext_res_W0$cox_slope["cox_slope_se"][[1]], cv_cali_ext_res_W0$cox_slope["cox_slope_se"][[1]])
    
    
    
    cali_intc_byAvg_allfold_W0[cv_iter,1] = cv_cali_res_W0$cox_intercept["cox_intercept"][[1]]
    cali_intc_byAvg_allfold_W1[cv_iter,1] = cv_cali_res_W1$cox_intercept["cox_intercept"][[1]]
    cali_intc_estsd_byAvg_allfold_W0[cv_iter,1] = cv_cali_res_W0$cox_intercept["cox_intercept_se"][[1]]
    cali_intc_estsd_byAvg_allfold_W1[cv_iter,1] = cv_cali_res_W1$cox_intercept["cox_intercept_se"][[1]]
    cali_intc_rej_byAvg_allfold_W0[cv_iter,1] = cali_intc_byAvg_allfold_W0[cv_iter,1] + cali_intc_estsd_byAvg_allfold_W0[cv_iter,1] * qnorm(0.975) < 0 & cali_intc_byAvg_allfold_W0[cv_iter,1] - cali_intc_estsd_byAvg_allfold_W0[cv_iter,1] * qnorm(0.975) > 0
    cali_intc_rej_byAvg_allfold_W1[cv_iter,1] = cali_intc_byAvg_allfold_W1[cv_iter,1] + cali_intc_estsd_byAvg_allfold_W1[cv_iter,1] * qnorm(0.975) < 0 & cali_intc_byAvg_allfold_W1[cv_iter,1] - cali_intc_estsd_byAvg_allfold_W1[cv_iter,1] * qnorm(0.975) > 0
    

    cali_intc_extAvg_allfold_W0[cv_iter,1] = cv_cali_ext_res_W0$cox_intercept["cox_intercept"][[1]]
    cali_intc_extAvg_allfold_W1[cv_iter,1] = cv_cali_ext_res_W1$cox_intercept["cox_intercept"][[1]]
    cali_intc_estsd_extAvg_allfold_W0[cv_iter,1] = cv_cali_ext_res_W0$cox_intercept["cox_intercept_se"][[1]]
    cali_intc_estsd_extAvg_allfold_W1[cv_iter,1] = cv_cali_ext_res_W1$cox_intercept["cox_intercept_se"][[1]]
    cali_intc_rej_extAvg_allfold_W0[cv_iter,1] = cali_intc_extAvg_allfold_W0[cv_iter,1] + cali_intc_estsd_extAvg_allfold_W0[cv_iter,1] * qnorm(0.975) < 0 & cali_intc_extAvg_allfold_W0[cv_iter,1] - cali_intc_estsd_extAvg_allfold_W0[cv_iter,1] * qnorm(0.975) > 0
    cali_intc_rej_extAvg_allfold_W1[cv_iter,1] = cali_intc_extAvg_allfold_W1[cv_iter,1] + cali_intc_estsd_extAvg_allfold_W1[cv_iter,1] * qnorm(0.975) < 0 & cali_intc_extAvg_allfold_W1[cv_iter,1] - cali_intc_estsd_extAvg_allfold_W1[cv_iter,1] * qnorm(0.975) > 0
    
    cali_slp_byAvg_allfold_W0[cv_iter,1] = cv_cali_res_W0$cox_slope["cox_slope"][[1]]
    cali_slp_byAvg_allfold_W1[cv_iter,1] = cv_cali_res_W1$cox_slope["cox_slope"][[1]]
    cali_slp_estsd_byAvg_allfold_W0[cv_iter,1] = cv_cali_res_W0$cox_slope["cox_slope_se"][[1]]
    cali_slp_estsd_byAvg_allfold_W1[cv_iter,1] = cv_cali_res_W1$cox_slope["cox_slope_se"][[1]]
    cali_slp_rej_byAvg_allfold_W0[cv_iter,1] = cali_slp_byAvg_allfold_W0[cv_iter,1] + cali_slp_estsd_byAvg_allfold_W0[cv_iter,1] * qnorm(0.975) < 0 & cali_slp_byAvg_allfold_W0[cv_iter,1] - cali_slp_estsd_byAvg_allfold_W0[cv_iter,1] * qnorm(0.975) > 0
    cali_slp_rej_byAvg_allfold_W1[cv_iter,1] = cali_slp_byAvg_allfold_W1[cv_iter,1] + cali_slp_estsd_byAvg_allfold_W1[cv_iter,1] * qnorm(0.975) < 0 & cali_slp_byAvg_allfold_W1[cv_iter,1] - cali_slp_estsd_byAvg_allfold_W1[cv_iter,1] * qnorm(0.975) > 0
    

    cali_slp_extAvg_allfold_W0[cv_iter,1] = cv_cali_ext_res_W0$cox_slope["cox_slope"][[1]]
    cali_slp_extAvg_allfold_W1[cv_iter,1] = cv_cali_ext_res_W1$cox_slope["cox_slope"][[1]]
    cali_slp_estsd_extAvg_allfold_W0[cv_iter,1] = cv_cali_ext_res_W0$cox_slope["cox_slope_se"][[1]]
    cali_slp_estsd_extAvg_allfold_W1[cv_iter,1] = cv_cali_ext_res_W1$cox_slope["cox_slope_se"][[1]]
    cali_slp_rej_extAvg_allfold_W0[cv_iter,1] = cali_slp_extAvg_allfold_W0[cv_iter,1] + cali_slp_estsd_extAvg_allfold_W0[cv_iter,1] * qnorm(0.975) < 0 & cali_slp_extAvg_allfold_W0[cv_iter,1] - cali_slp_estsd_extAvg_allfold_W0[cv_iter,1] * qnorm(0.975) > 0
    cali_slp_rej_extAvg_allfold_W1[cv_iter,1] = cali_slp_extAvg_allfold_W1[cv_iter,1] + cali_slp_estsd_extAvg_allfold_W1[cv_iter,1] * qnorm(0.975) < 0 & cali_slp_extAvg_allfold_W1[cv_iter,1] - cali_slp_estsd_extAvg_allfold_W1[cv_iter,1] * qnorm(0.975) > 0
  }

  cali_intc_byAvg_rep = colMeans(cali_intc_byAvg_vec_folds)
  cali_intc_estsd_byAvg_rep = colMeans(cali_intc_estsd_byAvg_vec_folds)/sqrt(num_folds)

  cali_intc_extAvg_rep = colMeans(cali_intc_extAvg_vec_folds)
  cali_intc_estsd_extAvg_rep = colMeans(cali_intc_estsd_extAvg_vec_folds)/sqrt(num_folds)
  
  cali_slp_byAvg_rep = colMeans(cali_slp_byAvg_vec_folds)
  cali_slp_estsd_byAvg_rep = colMeans(cali_slp_estsd_byAvg_vec_folds)/sqrt(num_folds)

  cali_slp_extAvg_rep = colMeans(cali_slp_extAvg_vec_folds)
  cali_slp_estsd_extAvg_rep = colMeans(cali_slp_estsd_extAvg_vec_folds)/sqrt(num_folds)

  all_test_dt = data.frame(W=test_W, case=test_Y_true, Y_pred=test_Y_pred)

  cali_res_byAgt_W0 = all_test_dt %>% filter(W==0) %>% calibrationMetrics(risk_var = "Y_pred", weak_cali_ind = FALSE, correlated = FALSE)
  cali_res_byAgt_W1 = all_test_dt %>% filter(W==1) %>% calibrationMetrics(risk_var = "Y_pred", weak_cali_ind = FALSE, correlated = FALSE)

  tmp = c("cali_intc_extAvg_W0"=cali_intc_extAvg_rep[1], "cali_intc_extAvg_W1"=cali_intc_extAvg_rep[2],
    "cali_intc_estsd_extAvg_W0"=cali_intc_estsd_extAvg_rep[1], "cali_intc_estsd_extAvg_W1"=cali_intc_estsd_extAvg_rep[2],

    "cali_intc_byAvg_W0"=cali_intc_byAvg_rep[1], "cali_intc_byAvg_W1"=cali_intc_byAvg_rep[2],
    "cali_intc_estsd_byAvg_W0" = cali_intc_estsd_byAvg_rep[1], "cali_intc_estsd_byAvg_W1"=cali_intc_estsd_byAvg_rep[2],
    "cali_intc_rej_byAvg_W0" = cali_intc_byAvg_rep[1] + cali_intc_estsd_byAvg_rep[1] * qnorm(0.975) < 0 | cali_intc_byAvg_rep[1] - cali_intc_estsd_byAvg_rep[1] * qnorm(0.975) > 0,
    "cali_intc_rej_byAvg_W1" = cali_intc_byAvg_rep[2] + cali_intc_estsd_byAvg_rep[2] * qnorm(0.975) < 0 | cali_intc_byAvg_rep[2] - cali_intc_estsd_byAvg_rep[2] * qnorm(0.975) > 0,

    "cali_intc_byAgt_W0"=cali_res_byAgt_W0$cox_intercept["cox_intercept"][[1]], "cali_intc_byAgt_W1"=cali_res_byAgt_W1$cox_intercept["cox_intercept"][[1]],
    "cali_intc_estsd_byAgt_W0"=cali_res_byAgt_W0$cox_intercept["cox_intercept_se"][[1]], "cali_intc_estsd_byAgt_W1"=cali_res_byAgt_W1$cox_intercept["cox_intercept_se"][[1]],
    
    "cali_slp_extAvg_W0"=cali_slp_extAvg_rep[1], "cali_slp_extAvg_W1"=cali_slp_extAvg_rep[2],
    "cali_slp_estsd_extAvg_W0"=cali_slp_estsd_extAvg_rep[1], "cali_slp_estsd_extAvg_W1"=cali_slp_estsd_extAvg_rep[2],

    "cali_slp_byAvg_W0"=cali_slp_byAvg_rep[1], "cali_slp_byAvg_W1"=cali_slp_byAvg_rep[2],
    "cali_slp_estsd_byAvg_W0" = cali_slp_estsd_byAvg_rep[1], "cali_slp_estsd_byAvg_W1"=cali_slp_estsd_byAvg_rep[2],
    "cali_slp_rej_byAvg_W0" = cali_slp_byAvg_rep[1] + cali_slp_estsd_byAvg_rep[1] * qnorm(0.975) < 0 | cali_slp_byAvg_rep[1] - cali_slp_estsd_byAvg_rep[1] * qnorm(0.975) > 0,
    "cali_slp_rej_byAvg_W1" = cali_slp_byAvg_rep[2] + cali_slp_estsd_byAvg_rep[2] * qnorm(0.975) < 0 | cali_slp_byAvg_rep[2] - cali_slp_estsd_byAvg_rep[2] * qnorm(0.975) > 0,

    "cali_slp_byAgt_W0"=cali_res_byAgt_W0$cox_slope["cox_slope"][[1]], "cali_slp_byAgt_W1"=cali_res_byAgt_W1$cox_slope["cox_slope"][[1]],
    "cali_slp_estsd_byAgt_W0"=cali_res_byAgt_W0$cox_slope["cox_slope_se"][[1]], "cali_slp_estsd_byAgt_W1"=cali_res_byAgt_W1$cox_slope["cox_slope_se"][[1]])
  
  for(cv_iter in 1:num_folds){
    tmp2 = c(cali_intc_byAvg_allfold_W0[cv_iter, 1],
             cali_intc_byAvg_allfold_W1[cv_iter, 1],
             cali_intc_estsd_byAvg_allfold_W0[cv_iter, 1],
             cali_intc_estsd_byAvg_allfold_W1[cv_iter, 1],
             cali_intc_rej_byAvg_allfold_W0[cv_iter, 1],
             cali_intc_rej_byAvg_allfold_W1[cv_iter, 1],

             cali_intc_extAvg_allfold_W0[cv_iter, 1],
             cali_intc_extAvg_allfold_W1[cv_iter, 1],
             cali_intc_estsd_extAvg_allfold_W0[cv_iter, 1],
             cali_intc_estsd_extAvg_allfold_W1[cv_iter, 1],
             cali_intc_rej_extAvg_allfold_W0[cv_iter, 1],
             cali_intc_rej_extAvg_allfold_W1[cv_iter, 1],
             
             cali_slp_byAvg_allfold_W0[cv_iter, 1],
             cali_slp_byAvg_allfold_W1[cv_iter, 1],
             cali_slp_estsd_byAvg_allfold_W0[cv_iter, 1],
             cali_slp_estsd_byAvg_allfold_W1[cv_iter, 1],
             cali_slp_rej_byAvg_allfold_W0[cv_iter, 1],
             cali_slp_rej_byAvg_allfold_W1[cv_iter, 1],

             cali_slp_extAvg_allfold_W0[cv_iter, 1],
             cali_slp_extAvg_allfold_W1[cv_iter, 1],
             cali_slp_estsd_extAvg_allfold_W0[cv_iter, 1],
             cali_slp_estsd_extAvg_allfold_W1[cv_iter, 1],
             cali_slp_rej_extAvg_allfold_W0[cv_iter, 1],
             cali_slp_rej_extAvg_allfold_W1[cv_iter, 1])
    
    names(tmp2) = c(paste0("cali_intc_byAvg_", cv_iter, "fold_W0"),
                    paste0("cali_intc_byAvg_", cv_iter, "fold_W1"),
                    paste0("cali_intc_estsd_byAvg_", cv_iter, "fold_W0"),
                    paste0("cali_intc_estsd_byAvg_", cv_iter, "fold_W1"),
                    paste0("cali_intc_rej_byAvg_", cv_iter, "fold_W0"),
                    paste0("cali_intc_rej_byAvg_", cv_iter, "fold_W1"),
                    paste0("cali_intc_extAvg_", cv_iter, "fold_W0"),
                    paste0("cali_intc_extAvg_", cv_iter, "fold_W1"),
                    paste0("cali_intc_estsd_extAvg_", cv_iter, "fold_W0"),
                    paste0("cali_intc_estsd_extAvg_", cv_iter, "fold_W1"),
                    paste0("cali_intc_rej_extAvg_", cv_iter, "fold_W0"),
                    paste0("cali_intc_rej_extAvg_", cv_iter, "fold_W1"),
                    
                    paste0("cali_slp_byAvg_", cv_iter, "fold_W0"),
                    paste0("cali_slp_byAvg_", cv_iter, "fold_W1"),
                    paste0("cali_slp_estsd_byAvg_", cv_iter, "fold_W0"),
                    paste0("cali_slp_estsd_byAvg_", cv_iter, "fold_W1"),
                    paste0("cali_slp_rej_byAvg_", cv_iter, "fold_W0"),
                    paste0("cali_slp_rej_byAvg_", cv_iter, "fold_W1"),
                    paste0("cali_slp_extAvg_", cv_iter, "fold_W0"),
                    paste0("cali_slp_extAvg_", cv_iter, "fold_W1"),
                    paste0("cali_slp_estsd_extAvg_", cv_iter, "fold_W0"),
                    paste0("cali_slp_estsd_extAvg_", cv_iter, "fold_W1"),
                    paste0("cali_slp_rej_extAvg_", cv_iter, "fold_W0"),
                    paste0("cali_slp_rej_extAvg_", cv_iter, "fold_W1"))
    
    tmp = c(tmp, tmp2)
  }
  tmp
}

stopCluster(myCluster)


out_size = ifelse(N==3e5, "large", "small")
# careful !!!!!!!!!!!!!!!!!!!!!!!!
res %>% write.csv(paste0("diagnosis_nonstratified_", out_size, "_", num_folds,"folds.csv"))
```

```{r}
out_size = "large"
res = readr::read_csv(paste0("diagnosis_nonstratified_", out_size, "_", num_folds,"folds.csv"))
mean(res$cali_intc_estsd_extAvg_W0)
sd(res$cali_intc_extAvg_W0)

# Formula-based SD by average method
mean(res$cali_intc_estsd_byAvg_W0)
# MC-based SD by average method
sd(res$cali_intc_byAvg_W0) ## 100 times smaller than formula-based
mean(res$cali_intc_estsd_byAvg_W0)/sd(res$cali_intc_byAvg_W0)

# Formula-based SD based on only 1 fold
mean(res$cali_intc_estsd_byAvg_1fold_W0)
# MC-based SD based on only 1 fold
sd(res$cali_intc_byAvg_1fold_W0)
mean(res$cali_intc_estsd_byAvg_1fold_W0)/sd(res$cali_intc_byAvg_1fold_W0)

# Formula-based SD by aggregate method
mean(res$cali_intc_estsd_byAgt_W0)
# MC-based SD by aggregate method
sd(res$cali_intc_byAgt_W0)  ## 100 times smaller than formula-based
mean(res$cali_intc_estsd_byAgt_W0)/sd(res$cali_intc_byAgt_W0)

mean(res$cali_intc_estsd_extAvg_1fold_W0)
sd(res$cali_intc_extAvg_1fold_W0)

mean(res$cali_intc_rej_byAvg_1fold_W0)
mean(res$cali_intc_rej_byAvg_2fold_W0)

cor(res[, c("cali_intc_byAvg_1fold_W0", "cali_intc_byAvg_2fold_W0",
            "cali_intc_byAvg_3fold_W0", "cali_intc_byAvg_4fold_W0",
            "cali_intc_byAvg_5fold_W0", "cali_intc_byAvg_6fold_W0",
            "cali_intc_byAvg_7fold_W0", "cali_intc_byAvg_8fold_W0",
            "cali_intc_byAvg_9fold_W0", "cali_intc_byAvg_10fold_W0",
            "cali_intc_byAvg_11fold_W0", "cali_intc_byAvg_12fold_W0",
            "cali_intc_byAvg_13fold_W0", "cali_intc_byAvg_14fold_W0",
            "cali_intc_byAvg_15fold_W0", "cali_intc_byAvg_16fold_W0",
            "cali_intc_byAvg_17fold_W0", "cali_intc_byAvg_18fold_W0",
            "cali_intc_byAvg_19fold_W0", "cali_intc_byAvg_20fold_W0")])



mean(res$cali_slp_estsd_extAvg_W0)
sd(res$cali_slp_extAvg_W0)

# Formula-based SD by average method
mean(res$cali_slp_estsd_byAvg_W0)
# MC-based SD by average method
sd(res$cali_slp_byAvg_W0) ## 100 times smaller than formula-based
mean(res$cali_slp_estsd_byAvg_W0)/sd(res$cali_slp_byAvg_W0)

# Formula-based SD based on only 1 fold
mean(res$cali_slp_estsd_byAvg_1fold_W0)
# MC-based SD based on only 1 fold
sd(res$cali_slp_byAvg_1fold_W0)
mean(res$cali_slp_estsd_byAvg_1fold_W0)/sd(res$cali_slp_byAvg_1fold_W0)

# Formula-based SD by aggregate method
mean(res$cali_slp_estsd_byAgt_W0)
# MC-based SD by aggregate method
sd(res$cali_slp_byAgt_W0)  ## 100 times smaller than formula-based
mean(res$cali_slp_estsd_byAgt_W0)/sd(res$cali_slp_byAgt_W0)

mean(res$cali_slp_estsd_extAvg_1fold_W0)
sd(res$cali_slp_extAvg_1fold_W0)

mean(res$cali_slp_rej_byAvg_1fold_W0)
mean(res$cali_slp_rej_byAvg_2fold_W0)

cor(res[, c("cali_slp_byAvg_1fold_W0", "cali_slp_byAvg_2fold_W0",
            "cali_slp_byAvg_3fold_W0", "cali_slp_byAvg_4fold_W0",
            "cali_slp_byAvg_5fold_W0")])

```

```{r}
res = readr::read_csv(paste0("diagnosis_nonstratified_large", "_", "5folds.csv"))
mean(res$cali_intc_estsd_extAvg_W0)
sd(res$cali_intc_extAvg_W0)

# Formula-based SD by average method
mean(res$cali_intc_estsd_byAvg_W0)
# MC-based SD by average method
sd(res$cali_intc_byAvg_W0) ## 100 times smaller than formula-based
mean(res$cali_intc_estsd_byAvg_W0)/sd(res$cali_intc_byAvg_W0)

# Formula-based SD based on only 1 fold
mean(res$cali_intc_estsd_byAvg_1fold_W0)
# MC-based SD based on only 1 fold
sd(res$cali_intc_byAvg_1fold_W0)
mean(res$cali_intc_estsd_byAvg_1fold_W0)/sd(res$cali_intc_byAvg_1fold_W0)

# Formula-based SD by aggregate method
mean(res$cali_intc_estsd_byAgt_W0)
# MC-based SD by aggregate method
sd(res$cali_intc_byAgt_W0)  ## 100 times smaller than formula-based
mean(res$cali_intc_estsd_byAgt_W0)/sd(res$cali_intc_byAgt_W0)

mean(res$cali_intc_estsd_extAvg_1fold_W0)
sd(res$cali_intc_extAvg_1fold_W0)

mean(res$cali_intc_rej_byAvg_1fold_W0)
mean(res$cali_intc_rej_byAvg_2fold_W0)

cor(res[, c("cali_intc_byAvg_1fold_W0", "cali_intc_byAvg_2fold_W0",
            "cali_intc_byAvg_3fold_W0", "cali_intc_byAvg_4fold_W0",
            "cali_intc_byAvg_5fold_W0")])
```


# gee
```{r}
# sample size
N = 5000
# X: continuous predictors
mu_X = c(0,0,0)
Sigma_X = matrix(c(1, 0.5, 0.1,
                   0.5, 1, 0.3,
                   0.1, 0.3, 1), nrow = 3, ncol = 3, byrow = TRUE)
coef_X = c(0.3, 0.5, 0.7)
# V: discrete predictors
p_V = c(0.7, 0.4)
coef_V = c(0.4, 0.6)

# W: racial and ethnic group
ps_W = c(0.6, 0.9) # proportion of white
coef_W = 0.8

# The probability of case
ps_case = c(0.2, 0.05)

paras = expand.grid(Proportion_White = ps_W, Prob_Case = ps_case)
NN = 1e5
candi_as = seq(-5, -1, 0.01)
as = NULL
for(i in 1:nrow(paras)){
  p_W = paras$Proportion_White[i]
  p_case = paras$Prob_Case[i]
  candi_prevals = NULL
  for(candi_a in candi_as){
    X = MASS::mvrnorm(n = NN, mu = mu_X, Sigma = Sigma_X)
    V = sapply(p_V, function(p){rbinom(n = NN, size = 1, prob = p)})
    W = rbinom(n = NN, size = 1, prob = p_W)
    pos_prob = exp(candi_a + X %*% coef_X + V %*% coef_V + W * coef_W) / (1 + exp(candi_a + X %*% coef_X + V %*% coef_V + W * coef_W))
    case = rbinom(NN, 1, pos_prob)
    candi_prevals = c(candi_prevals, mean(case))
  }
  cat(min(abs(candi_prevals - p_case)), "\n")
  as[i] = candi_as[which.min(abs(candi_prevals - p_case))]
  cat(as[i], "\n")
}
paras$alpha = as

for(i in 1:nrow(paras)){
  p_W = paras$Proportion_White[i]
  p_case = paras$Prob_Case[i]
  a = paras$alpha[i]
  X = MASS::mvrnorm(n = N, mu = mu_X, Sigma = Sigma_X)
  V = sapply(p_V, function(p){rbinom(n = N, size = 1, prob = p)})
  W = rbinom(n = N, size = 1, prob = p_W)
  pos_prob = exp(a + X %*% coef_X + V %*% coef_V + W * coef_W) / (1 + exp(a + X %*% coef_X + V %*% coef_V + W * coef_W))
  case = rbinom(N, 1, pos_prob)
  print(table(case, W))
}

# Number of iteration
n_iter = 500
source("funcs_calibrationMetrics.R")
library(caret)
library(pROC)
library(tidyverse)
library(doParallel)
library(foreach)
library(parallel)
paras = merge(paras, data.frame(num_folds = c(5,10)))


i=1
myCluster <- makeCluster(detectCores()-1, type = "PSOCK")
registerDoParallel(myCluster)
p_W = paras$Proportion_White[i]
p_case = paras$Prob_Case[i]
a = paras$alpha[i]
num_folds = paras$num_folds[i]
res = foreach(iter=1:n_iter, .combine = 'rbind', .packages = c("caret", "pROC", "tidyverse")) %dopar%{
  X = MASS::mvrnorm(n = N, mu = mu_X, Sigma = Sigma_X)
  V = sapply(p_V, function(p){rbinom(n = N, size = 1, prob = p)})
  W = rbinom(n = N, size = 1, prob = p_W)
  pos_prob = exp(a + X %*% coef_X + V %*% coef_V + W * coef_W) / (1 + exp(a + X %*% coef_X + V %*% coef_V + W * coef_W))
  case = rbinom(N, 1, pos_prob)
  sim_data = data.frame(X=X, V=V, W=W, case=case)

  ext_X = MASS::mvrnorm(n = N, mu = mu_X, Sigma = Sigma_X)
  ext_V = sapply(p_V, function(p){rbinom(n = N, size = 1, prob = p)})
  ext_W = rbinom(n = N, size = 1, prob = p_W)
  ext_pos_prob = exp(a + ext_X %*% coef_X + ext_V %*% coef_V + ext_W * coef_W) / (1 + exp(a + ext_X %*% coef_X + ext_V %*% coef_V + ext_W * coef_W))
  ext_case = rbinom(N, 1, ext_pos_prob)
  ext_data = data.frame(X=ext_X, V=ext_V, W=ext_W, case=ext_case)
  
  folds = cut(seq(1, N), breaks=num_folds, labels=FALSE)
  folds = folds[sample(1:N, size = N, replace = FALSE)]
  
  ext_folds = cut(seq(1, N), breaks=num_folds, labels=FALSE)
  ext_folds = ext_folds[sample(1:N, size = N, replace = FALSE)]

  test_Y_true = NULL
  test_Y_pred = NULL
  test_W = NULL
  test_StudyID_c = NULL
  cali_intc_byAvg_vec_folds = matrix(0, nrow = num_folds, ncol = length(p_W) + 1)
  cali_intc_estsd_byAvg_vec_folds = matrix(0, nrow = num_folds, ncol = length(p_W) + 1)

  cali_intc_extAvg_vec_folds = matrix(0, nrow = num_folds, ncol = length(p_W) + 1)
  cali_intc_estsd_extAvg_vec_folds = matrix(0, nrow = num_folds, ncol = length(p_W) + 1)
  
  cali_slp_byAvg_vec_folds = matrix(0, nrow = num_folds, ncol = length(p_W) + 1)
  cali_slp_estsd_byAvg_vec_folds = matrix(0, nrow = num_folds, ncol = length(p_W) + 1)

  cali_slp_extAvg_vec_folds = matrix(0, nrow = num_folds, ncol = length(p_W) + 1)
  cali_slp_estsd_extAvg_vec_folds = matrix(0, nrow = num_folds, ncol = length(p_W) + 1)
  
  cali_intc_byAvg_allfold_W0 = matrix(0, nrow = num_folds, ncol = 1)
  cali_intc_byAvg_allfold_W1 = matrix(0, nrow = num_folds, ncol = 1)
  cali_intc_estsd_byAvg_allfold_W0 = matrix(0, nrow = num_folds, ncol = 1)
  cali_intc_estsd_byAvg_allfold_W1 = matrix(0, nrow = num_folds, ncol = 1)
  cali_intc_rej_byAvg_allfold_W0 = matrix(0, nrow = num_folds, ncol = 1)
  cali_intc_rej_byAvg_allfold_W1 = matrix(0, nrow = num_folds, ncol = 1)

  cali_intc_extAvg_allfold_W0 = matrix(0, nrow = num_folds, ncol = 1)
  cali_intc_extAvg_allfold_W1 = matrix(0, nrow = num_folds, ncol = 1)
  cali_intc_estsd_extAvg_allfold_W0 = matrix(0, nrow = num_folds, ncol = 1)
  cali_intc_estsd_extAvg_allfold_W1 = matrix(0, nrow = num_folds, ncol = 1)
  cali_intc_rej_extAvg_allfold_W0 = matrix(0, nrow = num_folds, ncol = 1)
  cali_intc_rej_extAvg_allfold_W1 = matrix(0, nrow = num_folds, ncol = 1)
  
  cali_slp_byAvg_allfold_W0 = matrix(0, nrow = num_folds, ncol = 1)
  cali_slp_byAvg_allfold_W1 = matrix(0, nrow = num_folds, ncol = 1)
  cali_slp_estsd_byAvg_allfold_W0 = matrix(0, nrow = num_folds, ncol = 1)
  cali_slp_estsd_byAvg_allfold_W1 = matrix(0, nrow = num_folds, ncol = 1)
  cali_slp_rej_byAvg_allfold_W0 = matrix(0, nrow = num_folds, ncol = 1)
  cali_slp_rej_byAvg_allfold_W1 = matrix(0, nrow = num_folds, ncol = 1)
  

  cali_slp_extAvg_allfold_W0 = matrix(0, nrow = num_folds, ncol = 1)
  cali_slp_extAvg_allfold_W1 = matrix(0, nrow = num_folds, ncol = 1)
  cali_slp_estsd_extAvg_allfold_W0 = matrix(0, nrow = num_folds, ncol = 1)
  cali_slp_estsd_extAvg_allfold_W1 = matrix(0, nrow = num_folds, ncol = 1)
  cali_slp_rej_extAvg_allfold_W0 = matrix(0, nrow = num_folds, ncol = 1)
  cali_slp_rej_extAvg_allfold_W1 = matrix(0, nrow = num_folds, ncol = 1)
  for(cv_iter in 1:num_folds){
    test_id = which(folds == cv_iter)
    cv_train_data = sim_data[-test_id, ]
    cv_test_data = sim_data[test_id, ]
    test_Y_true = c(test_Y_true, cv_test_data$case)
    test_W = c(test_W, cv_test_data$W)
    cv_model = glm(case ~ ., data = cv_train_data, family = binomial())
    cv_Y_ped = predict(cv_model, cv_test_data, type = "response")
    test_Y_pred = c(test_Y_pred, cv_Y_ped)
    cv_test_data$Y_pred = cv_Y_ped
    
    cv_test_ext_data = ext_data[which(ext_folds == cv_iter), ]
    cv_ext_Y_ped = predict(cv_model, cv_test_ext_data, type = "response")
    cv_test_ext_data$Y_pred = cv_ext_Y_ped
    
    cv_test_data$StudyID_c = cv_iter
    test_StudyID_c = c(test_StudyID_c, cv_test_data$StudyID_c)
    cv_cali_res_W0 = cv_test_data %>% filter(W==0) %>% calibrationMetrics(risk_var = "Y_pred", weak_cali_ind = FALSE, correlated = TRUE)
    cv_cali_res_W1 = cv_test_data %>% filter(W==1) %>% calibrationMetrics(risk_var = "Y_pred", weak_cali_ind = FALSE, correlated = TRUE)
    
    cv_test_ext_data$StudyID_c = cv_iter
    cv_cali_ext_res_W0 = cv_test_ext_data %>% filter(W==0) %>% calibrationMetrics(risk_var = "Y_pred", weak_cali_ind = FALSE, correlated = TRUE)
    cv_cali_ext_res_W1 = cv_test_ext_data %>% filter(W==1) %>% calibrationMetrics(risk_var = "Y_pred", weak_cali_ind = FALSE, correlated = TRUE)

    cali_intc_byAvg_vec_folds[cv_iter, ] = c(cv_cali_res_W0$cox_intercept["cox_intercept"][[1]], cv_cali_res_W1$cox_intercept["cox_intercept"][[1]])

    cali_intc_extAvg_vec_folds[cv_iter, ] = c(cv_cali_ext_res_W0$cox_intercept["cox_intercept"][[1]], cv_cali_ext_res_W1$cox_intercept["cox_intercept"][[1]])

    cali_intc_estsd_byAvg_vec_folds[cv_iter, ] = c(cv_cali_res_W0$cox_intercept["cox_intercept_se"][[1]], cv_cali_res_W1$cox_intercept["cox_intercept_se"][[1]])

    cali_intc_estsd_extAvg_vec_folds[cv_iter, ] = c(cv_cali_ext_res_W0$cox_intercept["cox_intercept_se"][[1]], cv_cali_ext_res_W0$cox_intercept["cox_intercept_se"][[1]])
    
    cali_slp_byAvg_vec_folds[cv_iter, ] = c(cv_cali_res_W0$cox_slope["cox_slope"][[1]], cv_cali_res_W1$cox_slope["cox_slope"][[1]])

    cali_slp_extAvg_vec_folds[cv_iter, ] = c(cv_cali_ext_res_W0$cox_slope["cox_slope"][[1]], cv_cali_ext_res_W1$cox_slope["cox_slope"][[1]])

    cali_slp_estsd_byAvg_vec_folds[cv_iter, ] = c(cv_cali_res_W0$cox_slope["cox_slope_se"][[1]], cv_cali_res_W1$cox_slope["cox_slope_se"][[1]])

    cali_slp_estsd_extAvg_vec_folds[cv_iter, ] = c(cv_cali_ext_res_W0$cox_slope["cox_slope_se"][[1]], cv_cali_ext_res_W0$cox_slope["cox_slope_se"][[1]])
    
    cali_intc_byAvg_allfold_W0[cv_iter,1] = cv_cali_res_W0$cox_intercept["cox_intercept"][[1]]
    cali_intc_byAvg_allfold_W1[cv_iter,1] = cv_cali_res_W1$cox_intercept["cox_intercept"][[1]]
    cali_intc_estsd_byAvg_allfold_W0[cv_iter,1] = cv_cali_res_W0$cox_intercept["cox_intercept_se"][[1]]
    cali_intc_estsd_byAvg_allfold_W1[cv_iter,1] = cv_cali_res_W1$cox_intercept["cox_intercept_se"][[1]]
    cali_intc_rej_byAvg_allfold_W0[cv_iter,1] = cali_intc_byAvg_allfold_W0[cv_iter,1] + cali_intc_estsd_byAvg_allfold_W0[cv_iter,1] * qnorm(0.975) < 0 & cali_intc_byAvg_allfold_W0[cv_iter,1] - cali_intc_estsd_byAvg_allfold_W0[cv_iter,1] * qnorm(0.975) > 0
    cali_intc_rej_byAvg_allfold_W1[cv_iter,1] = cali_intc_byAvg_allfold_W1[cv_iter,1] + cali_intc_estsd_byAvg_allfold_W1[cv_iter,1] * qnorm(0.975) < 0 & cali_intc_byAvg_allfold_W1[cv_iter,1] - cali_intc_estsd_byAvg_allfold_W1[cv_iter,1] * qnorm(0.975) > 0
    

    cali_intc_extAvg_allfold_W0[cv_iter,1] = cv_cali_ext_res_W0$cox_intercept["cox_intercept"][[1]]
    cali_intc_extAvg_allfold_W1[cv_iter,1] = cv_cali_ext_res_W1$cox_intercept["cox_intercept"][[1]]
    cali_intc_estsd_extAvg_allfold_W0[cv_iter,1] = cv_cali_ext_res_W0$cox_intercept["cox_intercept_se"][[1]]
    cali_intc_estsd_extAvg_allfold_W1[cv_iter,1] = cv_cali_ext_res_W1$cox_intercept["cox_intercept_se"][[1]]
    cali_intc_rej_extAvg_allfold_W0[cv_iter,1] = cali_intc_extAvg_allfold_W0[cv_iter,1] + cali_intc_estsd_extAvg_allfold_W0[cv_iter,1] * qnorm(0.975) < 0 & cali_intc_extAvg_allfold_W0[cv_iter,1] - cali_intc_estsd_extAvg_allfold_W0[cv_iter,1] * qnorm(0.975) > 0
    cali_intc_rej_extAvg_allfold_W1[cv_iter,1] = cali_intc_extAvg_allfold_W1[cv_iter,1] + cali_intc_estsd_extAvg_allfold_W1[cv_iter,1] * qnorm(0.975) < 0 & cali_intc_extAvg_allfold_W1[cv_iter,1] - cali_intc_estsd_extAvg_allfold_W1[cv_iter,1] * qnorm(0.975) > 0
    
    cali_slp_byAvg_allfold_W0[cv_iter,1] = cv_cali_res_W0$cox_slope["cox_slope"][[1]]
    cali_slp_byAvg_allfold_W1[cv_iter,1] = cv_cali_res_W1$cox_slope["cox_slope"][[1]]
    cali_slp_estsd_byAvg_allfold_W0[cv_iter,1] = cv_cali_res_W0$cox_slope["cox_slope_se"][[1]]
    cali_slp_estsd_byAvg_allfold_W1[cv_iter,1] = cv_cali_res_W1$cox_slope["cox_slope_se"][[1]]
    cali_slp_rej_byAvg_allfold_W0[cv_iter,1] = cali_slp_byAvg_allfold_W0[cv_iter,1] + cali_slp_estsd_byAvg_allfold_W0[cv_iter,1] * qnorm(0.975) < 0 & cali_slp_byAvg_allfold_W0[cv_iter,1] - cali_slp_estsd_byAvg_allfold_W0[cv_iter,1] * qnorm(0.975) > 0
    cali_slp_rej_byAvg_allfold_W1[cv_iter,1] = cali_slp_byAvg_allfold_W1[cv_iter,1] + cali_slp_estsd_byAvg_allfold_W1[cv_iter,1] * qnorm(0.975) < 0 & cali_slp_byAvg_allfold_W1[cv_iter,1] - cali_slp_estsd_byAvg_allfold_W1[cv_iter,1] * qnorm(0.975) > 0
    

    cali_slp_extAvg_allfold_W0[cv_iter,1] = cv_cali_ext_res_W0$cox_slope["cox_slope"][[1]]
    cali_slp_extAvg_allfold_W1[cv_iter,1] = cv_cali_ext_res_W1$cox_slope["cox_slope"][[1]]
    cali_slp_estsd_extAvg_allfold_W0[cv_iter,1] = cv_cali_ext_res_W0$cox_slope["cox_slope_se"][[1]]
    cali_slp_estsd_extAvg_allfold_W1[cv_iter,1] = cv_cali_ext_res_W1$cox_slope["cox_slope_se"][[1]]
    cali_slp_rej_extAvg_allfold_W0[cv_iter,1] = cali_slp_extAvg_allfold_W0[cv_iter,1] + cali_slp_estsd_extAvg_allfold_W0[cv_iter,1] * qnorm(0.975) < 0 & cali_slp_extAvg_allfold_W0[cv_iter,1] - cali_slp_estsd_extAvg_allfold_W0[cv_iter,1] * qnorm(0.975) > 0
    cali_slp_rej_extAvg_allfold_W1[cv_iter,1] = cali_slp_extAvg_allfold_W1[cv_iter,1] + cali_slp_estsd_extAvg_allfold_W1[cv_iter,1] * qnorm(0.975) < 0 & cali_slp_extAvg_allfold_W1[cv_iter,1] - cali_slp_estsd_extAvg_allfold_W1[cv_iter,1] * qnorm(0.975) > 0
  }

  cali_intc_byAvg_rep = colMeans(cali_intc_byAvg_vec_folds)
  cali_intc_estsd_byAvg_rep = colMeans(cali_intc_estsd_byAvg_vec_folds)/sqrt(num_folds)

  cali_intc_extAvg_rep = colMeans(cali_intc_extAvg_vec_folds)
  cali_intc_estsd_extAvg_rep = colMeans(cali_intc_estsd_extAvg_vec_folds)/sqrt(num_folds)
  
  cali_slp_byAvg_rep = colMeans(cali_slp_byAvg_vec_folds)
  cali_slp_estsd_byAvg_rep = colMeans(cali_slp_estsd_byAvg_vec_folds)/sqrt(num_folds)

  cali_slp_extAvg_rep = colMeans(cali_slp_extAvg_vec_folds)
  cali_slp_estsd_extAvg_rep = colMeans(cali_slp_estsd_extAvg_vec_folds)/sqrt(num_folds)

  all_test_dt = data.frame(W=test_W, case=test_Y_true, Y_pred=test_Y_pred, StudyID_c = test_StudyID_c)

  cali_res_byAgt_W0 = all_test_dt %>% filter(W==0) %>% calibrationMetrics(risk_var = "Y_pred", weak_cali_ind = FALSE, correlated = TRUE)
  cali_res_byAgt_W1 = all_test_dt %>% filter(W==1) %>% calibrationMetrics(risk_var = "Y_pred", weak_cali_ind = FALSE, correlated = TRUE)

  tmp = c("cali_intc_extAvg_W0"=cali_intc_extAvg_rep[1], "cali_intc_extAvg_W1"=cali_intc_extAvg_rep[2],
    "cali_intc_estsd_extAvg_W0"=cali_intc_estsd_extAvg_rep[1], "cali_intc_estsd_extAvg_W1"=cali_intc_estsd_extAvg_rep[2],

    "cali_intc_byAvg_W0"=cali_intc_byAvg_rep[1], "cali_intc_byAvg_W1"=cali_intc_byAvg_rep[2],
    "cali_intc_estsd_byAvg_W0" = cali_intc_estsd_byAvg_rep[1], "cali_intc_estsd_byAvg_W1"=cali_intc_estsd_byAvg_rep[2],
    "cali_intc_rej_byAvg_W0" = cali_intc_byAvg_rep[1] + cali_intc_estsd_byAvg_rep[1] * qnorm(0.975) < 0 | cali_intc_byAvg_rep[1] - cali_intc_estsd_byAvg_rep[1] * qnorm(0.975) > 0,
    "cali_intc_rej_byAvg_W1" = cali_intc_byAvg_rep[2] + cali_intc_estsd_byAvg_rep[2] * qnorm(0.975) < 0 | cali_intc_byAvg_rep[2] - cali_intc_estsd_byAvg_rep[2] * qnorm(0.975) > 0,

    "cali_intc_byAgt_W0"=cali_res_byAgt_W0$cox_intercept["cox_intercept"][[1]], "cali_intc_byAgt_W1"=cali_res_byAgt_W1$cox_intercept["cox_intercept"][[1]],
    "cali_intc_estsd_byAgt_W0"=cali_res_byAgt_W0$cox_intercept["cox_intercept_se"][[1]], "cali_intc_estsd_byAgt_W1"=cali_res_byAgt_W1$cox_intercept["cox_intercept_se"][[1]],
    
    "cali_slp_extAvg_W0"=cali_slp_extAvg_rep[1], "cali_slp_extAvg_W1"=cali_slp_extAvg_rep[2],
    "cali_slp_estsd_extAvg_W0"=cali_slp_estsd_extAvg_rep[1], "cali_slp_estsd_extAvg_W1"=cali_slp_estsd_extAvg_rep[2],

    "cali_slp_byAvg_W0"=cali_slp_byAvg_rep[1], "cali_slp_byAvg_W1"=cali_slp_byAvg_rep[2],
    "cali_slp_estsd_byAvg_W0" = cali_slp_estsd_byAvg_rep[1], "cali_slp_estsd_byAvg_W1"=cali_slp_estsd_byAvg_rep[2],
    "cali_slp_rej_byAvg_W0" = cali_slp_byAvg_rep[1] + cali_slp_estsd_byAvg_rep[1] * qnorm(0.975) < 0 | cali_slp_byAvg_rep[1] - cali_slp_estsd_byAvg_rep[1] * qnorm(0.975) > 0,
    "cali_slp_rej_byAvg_W1" = cali_slp_byAvg_rep[2] + cali_slp_estsd_byAvg_rep[2] * qnorm(0.975) < 0 | cali_slp_byAvg_rep[2] - cali_slp_estsd_byAvg_rep[2] * qnorm(0.975) > 0,

    "cali_slp_byAgt_W0"=cali_res_byAgt_W0$cox_slope["cox_slope"][[1]], "cali_slp_byAgt_W1"=cali_res_byAgt_W1$cox_slope["cox_slope"][[1]],
    "cali_slp_estsd_byAgt_W0"=cali_res_byAgt_W0$cox_slope["cox_slope_se"][[1]], "cali_slp_estsd_byAgt_W1"=cali_res_byAgt_W1$cox_slope["cox_slope_se"][[1]])
  
  for(cv_iter in 1:num_folds){
    tmp2 = c(cali_intc_byAvg_allfold_W0[cv_iter, 1],
             cali_intc_byAvg_allfold_W1[cv_iter, 1],
             cali_intc_estsd_byAvg_allfold_W0[cv_iter, 1],
             cali_intc_estsd_byAvg_allfold_W1[cv_iter, 1],
             cali_intc_rej_byAvg_allfold_W0[cv_iter, 1],
             cali_intc_rej_byAvg_allfold_W1[cv_iter, 1],

             cali_intc_extAvg_allfold_W0[cv_iter, 1],
             cali_intc_extAvg_allfold_W1[cv_iter, 1],
             cali_intc_estsd_extAvg_allfold_W0[cv_iter, 1],
             cali_intc_estsd_extAvg_allfold_W1[cv_iter, 1],
             cali_intc_rej_extAvg_allfold_W0[cv_iter, 1],
             cali_intc_rej_extAvg_allfold_W1[cv_iter, 1],
             
             cali_slp_byAvg_allfold_W0[cv_iter, 1],
             cali_slp_byAvg_allfold_W1[cv_iter, 1],
             cali_slp_estsd_byAvg_allfold_W0[cv_iter, 1],
             cali_slp_estsd_byAvg_allfold_W1[cv_iter, 1],
             cali_slp_rej_byAvg_allfold_W0[cv_iter, 1],
             cali_slp_rej_byAvg_allfold_W1[cv_iter, 1],

             cali_slp_extAvg_allfold_W0[cv_iter, 1],
             cali_slp_extAvg_allfold_W1[cv_iter, 1],
             cali_slp_estsd_extAvg_allfold_W0[cv_iter, 1],
             cali_slp_estsd_extAvg_allfold_W1[cv_iter, 1],
             cali_slp_rej_extAvg_allfold_W0[cv_iter, 1],
             cali_slp_rej_extAvg_allfold_W1[cv_iter, 1])
    
    names(tmp2) = c(paste0("cali_intc_byAvg_", cv_iter, "fold_W0"),
                    paste0("cali_intc_byAvg_", cv_iter, "fold_W1"),
                    paste0("cali_intc_estsd_byAvg_", cv_iter, "fold_W0"),
                    paste0("cali_intc_estsd_byAvg_", cv_iter, "fold_W1"),
                    paste0("cali_intc_rej_byAvg_", cv_iter, "fold_W0"),
                    paste0("cali_intc_rej_byAvg_", cv_iter, "fold_W1"),
                    paste0("cali_intc_extAvg_", cv_iter, "fold_W0"),
                    paste0("cali_intc_extAvg_", cv_iter, "fold_W1"),
                    paste0("cali_intc_estsd_extAvg_", cv_iter, "fold_W0"),
                    paste0("cali_intc_estsd_extAvg_", cv_iter, "fold_W1"),
                    paste0("cali_intc_rej_extAvg_", cv_iter, "fold_W0"),
                    paste0("cali_intc_rej_extAvg_", cv_iter, "fold_W1"),
                    
                    paste0("cali_slp_byAvg_", cv_iter, "fold_W0"),
                    paste0("cali_slp_byAvg_", cv_iter, "fold_W1"),
                    paste0("cali_slp_estsd_byAvg_", cv_iter, "fold_W0"),
                    paste0("cali_slp_estsd_byAvg_", cv_iter, "fold_W1"),
                    paste0("cali_slp_rej_byAvg_", cv_iter, "fold_W0"),
                    paste0("cali_slp_rej_byAvg_", cv_iter, "fold_W1"),
                    paste0("cali_slp_extAvg_", cv_iter, "fold_W0"),
                    paste0("cali_slp_extAvg_", cv_iter, "fold_W1"),
                    paste0("cali_slp_estsd_extAvg_", cv_iter, "fold_W0"),
                    paste0("cali_slp_estsd_extAvg_", cv_iter, "fold_W1"),
                    paste0("cali_slp_rej_extAvg_", cv_iter, "fold_W0"),
                    paste0("cali_slp_rej_extAvg_", cv_iter, "fold_W1"))
    
    tmp = c(tmp, tmp2)
  }
  tmp
}

stopCluster(myCluster)

out_size = ifelse(N==3e5, "large", "small")
# careful !!!!!!!!!!!!!
res %>% write.csv(paste0("GEE_diagnosis_nonstratified_", out_size, "_", num_folds,"folds.csv"))
```

```{r}
res = readr::read_csv(paste0("GEE_diagnosis_nonstratified_", out_size, "_", num_folds,"folds.csv"))
mean(res$cali_intc_estsd_extAvg_W0)
sd(res$cali_intc_extAvg_W0)

# Formula-based SD by average method
mean(res$cali_intc_estsd_byAvg_W0)
# MC-based SD by average method
sd(res$cali_intc_byAvg_W0) ## 100 times smaller than formula-based
mean(res$cali_intc_estsd_byAvg_W0)/sd(res$cali_intc_byAvg_W0)

# Formula-based SD based on only 1 fold
mean(res$cali_intc_estsd_byAvg_1fold_W0)
# MC-based SD based on only 1 fold
sd(res$cali_intc_byAvg_1fold_W0)
mean(res$cali_intc_estsd_byAvg_1fold_W0)/sd(res$cali_intc_byAvg_1fold_W0)

# Formula-based SD by aggregate method
mean(res$cali_intc_estsd_byAgt_W0)
# MC-based SD by aggregate method
sd(res$cali_intc_byAgt_W0)  ## 100 times smaller than formula-based
mean(res$cali_intc_estsd_byAgt_W0)/sd(res$cali_intc_byAgt_W0)

mean(res$cali_intc_estsd_extAvg_1fold_W0)
sd(res$cali_intc_extAvg_1fold_W0)

mean(res$cali_intc_rej_byAvg_1fold_W0)
mean(res$cali_intc_rej_byAvg_2fold_W0)

cor(res[, c("cali_intc_byAvg_1fold_W0", "cali_intc_byAvg_2fold_W0",
            "cali_intc_byAvg_3fold_W0", "cali_intc_byAvg_4fold_W0",
            "cali_intc_byAvg_5fold_W0")])



mean(res$cali_slp_estsd_extAvg_W0)
sd(res$cali_slp_extAvg_W0)

# Formula-based SD by average method
mean(res$cali_slp_estsd_byAvg_W0)
# MC-based SD by average method
sd(res$cali_slp_byAvg_W0) ## 100 times smaller than formula-based
mean(res$cali_slp_estsd_byAvg_W0)/sd(res$cali_slp_byAvg_W0)

# Formula-based SD based on only 1 fold
mean(res$cali_slp_estsd_byAvg_1fold_W0)
# MC-based SD based on only 1 fold
sd(res$cali_slp_byAvg_1fold_W0)
mean(res$cali_slp_estsd_byAvg_1fold_W0)/sd(res$cali_slp_byAvg_1fold_W0)

# Formula-based SD by aggregate method
mean(res$cali_slp_estsd_byAgt_W0)
# MC-based SD by aggregate method
sd(res$cali_slp_byAgt_W0)  ## 100 times smaller than formula-based
mean(res$cali_slp_estsd_byAgt_W0)/sd(res$cali_slp_byAgt_W0)

mean(res$cali_slp_estsd_extAvg_1fold_W0)
sd(res$cali_slp_extAvg_1fold_W0)

mean(res$cali_slp_rej_byAvg_1fold_W0)
mean(res$cali_slp_rej_byAvg_2fold_W0)

cor(res[, c("cali_slp_byAvg_1fold_W0", "cali_slp_byAvg_2fold_W0",
            "cali_slp_byAvg_3fold_W0", "cali_slp_byAvg_4fold_W0",
            "cali_slp_byAvg_5fold_W0")])
```